// DO NOT EDIT
// Code generated by ./cmd/codegen/codegen

// This file contains CURRENTLY valid constants.
// It is not a full list of all possible historic and/or future values.

package dxccentitycode

var (
	NONE                              DXCC = 0   // 0    =
	CANADA                            DXCC = 1   // 1    = CANADA
	AFGHANISTAN                       DXCC = 3   // 3    = AFGHANISTAN
	AGALEGA_AND_ST_BRANDON_IS         DXCC = 4   // 4    = AGALEGA & ST. BRANDON IS.
	ALAND_IS                          DXCC = 5   // 5    = ALAND IS.
	ALASKA                            DXCC = 6   // 6    = ALASKA
	ALBANIA                           DXCC = 7   // 7    = ALBANIA
	AMERICAN_SAMOA                    DXCC = 9   // 9    = AMERICAN SAMOA
	AMSTERDAM_AND_ST_PAUL_IS          DXCC = 10  // 10   = AMSTERDAM & ST. PAUL IS.
	ANDAMAN_AND_NICOBAR_IS            DXCC = 11  // 11   = ANDAMAN & NICOBAR IS.
	ANGUILLA                          DXCC = 12  // 12   = ANGUILLA
	ANTARCTICA                        DXCC = 13  // 13   = ANTARCTICA
	ARMENIA                           DXCC = 14  // 14   = ARMENIA
	ASIATIC_RUSSIA                    DXCC = 15  // 15   = ASIATIC RUSSIA
	NEW_ZEALAND_SUBANTARCTIC_ISLANDS  DXCC = 16  // 16   = NEW ZEALAND SUBANTARCTIC ISLANDS
	AVES_I                            DXCC = 17  // 17   = AVES I.
	AZERBAIJAN                        DXCC = 18  // 18   = AZERBAIJAN
	BAKER_AND_HOWLAND_IS              DXCC = 20  // 20   = BAKER & HOWLAND IS.
	BALEARIC_IS                       DXCC = 21  // 21   = BALEARIC IS.
	PALAU                             DXCC = 22  // 22   = PALAU
	BOUVET                            DXCC = 24  // 24   = BOUVET
	BELARUS                           DXCC = 27  // 27   = BELARUS
	CANARY_IS                         DXCC = 29  // 29   = CANARY IS.
	C_KIRIBATI_BRITISH_PHOENIX_IS     DXCC = 31  // 31   = C. KIRIBATI (BRITISH PHOENIX IS.)
	CEUTA_AND_MELILLA                 DXCC = 32  // 32   = CEUTA & MELILLA
	CHAGOS_IS                         DXCC = 33  // 33   = CHAGOS IS.
	CHATHAM_IS                        DXCC = 34  // 34   = CHATHAM IS.
	CHRISTMAS_I                       DXCC = 35  // 35   = CHRISTMAS I.
	CLIPPERTON_I                      DXCC = 36  // 36   = CLIPPERTON I.
	COCOS_I                           DXCC = 37  // 37   = COCOS I.
	COCOS_KEELING_IS                  DXCC = 38  // 38   = COCOS (KEELING) IS.
	CRETE                             DXCC = 40  // 40   = CRETE
	CROZET_I                          DXCC = 41  // 41   = CROZET I.
	DESECHEO_I                        DXCC = 43  // 43   = DESECHEO I.
	DODECANESE                        DXCC = 45  // 45   = DODECANESE
	EAST_MALAYSIA                     DXCC = 46  // 46   = EAST MALAYSIA
	EASTER_I                          DXCC = 47  // 47   = EASTER I.
	E_KIRIBATI_LINE_IS                DXCC = 48  // 48   = E. KIRIBATI (LINE IS.)
	EQUATORIAL_GUINEA                 DXCC = 49  // 49   = EQUATORIAL GUINEA
	MEXICO                            DXCC = 50  // 50   = MEXICO
	ERITREA                           DXCC = 51  // 51   = ERITREA
	ESTONIA                           DXCC = 52  // 52   = ESTONIA
	ETHIOPIA                          DXCC = 53  // 53   = ETHIOPIA
	EUROPEAN_RUSSIA                   DXCC = 54  // 54   = EUROPEAN RUSSIA
	FERNANDO_DE_NORONHA               DXCC = 56  // 56   = FERNANDO DE NORONHA
	BAHAMAS                           DXCC = 60  // 60   = BAHAMAS
	FRANZ_JOSEF_LAND                  DXCC = 61  // 61   = FRANZ JOSEF LAND
	BARBADOS                          DXCC = 62  // 62   = BARBADOS
	FRENCH_GUIANA                     DXCC = 63  // 63   = FRENCH GUIANA
	BERMUDA                           DXCC = 64  // 64   = BERMUDA
	BRITISH_VIRGIN_IS                 DXCC = 65  // 65   = BRITISH VIRGIN IS.
	BELIZE                            DXCC = 66  // 66   = BELIZE
	CAYMAN_IS                         DXCC = 69  // 69   = CAYMAN IS.
	CUBA                              DXCC = 70  // 70   = CUBA
	GALAPAGOS_IS                      DXCC = 71  // 71   = GALAPAGOS IS.
	DOMINICAN_REPUBLIC                DXCC = 72  // 72   = DOMINICAN REPUBLIC
	EL_SALVADOR                       DXCC = 74  // 74   = EL SALVADOR
	GEORGIA                           DXCC = 75  // 75   = GEORGIA
	GUATEMALA                         DXCC = 76  // 76   = GUATEMALA
	GRENADA                           DXCC = 77  // 77   = GRENADA
	HAITI                             DXCC = 78  // 78   = HAITI
	GUADELOUPE                        DXCC = 79  // 79   = GUADELOUPE
	HONDURAS                          DXCC = 80  // 80   = HONDURAS
	JAMAICA                           DXCC = 82  // 82   = JAMAICA
	MARTINIQUE                        DXCC = 84  // 84   = MARTINIQUE
	NICARAGUA                         DXCC = 86  // 86   = NICARAGUA
	PANAMA                            DXCC = 88  // 88   = PANAMA
	TURKS_AND_CAICOS_IS               DXCC = 89  // 89   = TURKS & CAICOS IS.
	TRINIDAD_AND_TOBAGO               DXCC = 90  // 90   = TRINIDAD & TOBAGO
	ARUBA                             DXCC = 91  // 91   = ARUBA
	ANTIGUA_AND_BARBUDA               DXCC = 94  // 94   = ANTIGUA & BARBUDA
	DOMINICA                          DXCC = 95  // 95   = DOMINICA
	MONTSERRAT                        DXCC = 96  // 96   = MONTSERRAT
	ST_LUCIA                          DXCC = 97  // 97   = ST. LUCIA
	ST_VINCENT                        DXCC = 98  // 98   = ST. VINCENT
	GLORIOSO_IS                       DXCC = 99  // 99   = GLORIOSO IS.
	ARGENTINA                         DXCC = 100 // 100  = ARGENTINA
	GUAM                              DXCC = 103 // 103  = GUAM
	BOLIVIA                           DXCC = 104 // 104  = BOLIVIA
	GUANTANAMO_BAY                    DXCC = 105 // 105  = GUANTANAMO BAY
	GUERNSEY                          DXCC = 106 // 106  = GUERNSEY
	GUINEA                            DXCC = 107 // 107  = GUINEA
	BRAZIL                            DXCC = 108 // 108  = BRAZIL
	GUINEA_BISSAU                     DXCC = 109 // 109  = GUINEA-BISSAU
	HAWAII                            DXCC = 110 // 110  = HAWAII
	HEARD_I                           DXCC = 111 // 111  = HEARD I.
	CHILE                             DXCC = 112 // 112  = CHILE
	ISLE_OF_MAN                       DXCC = 114 // 114  = ISLE OF MAN
	COLOMBIA                          DXCC = 116 // 116  = COLOMBIA
	ITU_HQ                            DXCC = 117 // 117  = ITU HQ
	JAN_MAYEN                         DXCC = 118 // 118  = JAN MAYEN
	ECUADOR                           DXCC = 120 // 120  = ECUADOR
	JERSEY                            DXCC = 122 // 122  = JERSEY
	JOHNSTON_I                        DXCC = 123 // 123  = JOHNSTON I.
	JUAN_DE_NOVA_EUROPA               DXCC = 124 // 124  = JUAN DE NOVA, EUROPA
	JUAN_FERNANDEZ_IS                 DXCC = 125 // 125  = JUAN FERNANDEZ IS.
	KALININGRAD                       DXCC = 126 // 126  = KALININGRAD
	GUYANA                            DXCC = 129 // 129  = GUYANA
	KAZAKHSTAN                        DXCC = 130 // 130  = KAZAKHSTAN
	KERGUELEN_IS                      DXCC = 131 // 131  = KERGUELEN IS.
	PARAGUAY                          DXCC = 132 // 132  = PARAGUAY
	KERMADEC_IS                       DXCC = 133 // 133  = KERMADEC IS.
	KYRGYZSTAN                        DXCC = 135 // 135  = KYRGYZSTAN
	PERU                              DXCC = 136 // 136  = PERU
	REPUBLIC_OF_KOREA                 DXCC = 137 // 137  = REPUBLIC OF KOREA
	KURE_I                            DXCC = 138 // 138  = KURE I.
	SURINAME                          DXCC = 140 // 140  = SURINAME
	FALKLAND_IS                       DXCC = 141 // 141  = FALKLAND IS.
	LAKSHADWEEP_IS                    DXCC = 142 // 142  = LAKSHADWEEP IS.
	LAOS                              DXCC = 143 // 143  = LAOS
	URUGUAY                           DXCC = 144 // 144  = URUGUAY
	LATVIA                            DXCC = 145 // 145  = LATVIA
	LITHUANIA                         DXCC = 146 // 146  = LITHUANIA
	LORD_HOWE_I                       DXCC = 147 // 147  = LORD HOWE I.
	VENEZUELA                         DXCC = 148 // 148  = VENEZUELA
	AZORES                            DXCC = 149 // 149  = AZORES
	AUSTRALIA                         DXCC = 150 // 150  = AUSTRALIA
	MACAO                             DXCC = 152 // 152  = MACAO
	MACQUARIE_I                       DXCC = 153 // 153  = MACQUARIE I.
	NAURU                             DXCC = 157 // 157  = NAURU
	VANUATU                           DXCC = 158 // 158  = VANUATU
	MALDIVES                          DXCC = 159 // 159  = MALDIVES
	TONGA                             DXCC = 160 // 160  = TONGA
	MALPELO_I                         DXCC = 161 // 161  = MALPELO I.
	NEW_CALEDONIA                     DXCC = 162 // 162  = NEW CALEDONIA
	PAPUA_NEW_GUINEA                  DXCC = 163 // 163  = PAPUA NEW GUINEA
	MAURITIUS                         DXCC = 165 // 165  = MAURITIUS
	MARIANA_IS                        DXCC = 166 // 166  = MARIANA IS.
	MARKET_REEF                       DXCC = 167 // 167  = MARKET REEF
	MARSHALL_IS                       DXCC = 168 // 168  = MARSHALL IS.
	MAYOTTE                           DXCC = 169 // 169  = MAYOTTE
	NEW_ZEALAND                       DXCC = 170 // 170  = NEW ZEALAND
	MELLISH_REEF                      DXCC = 171 // 171  = MELLISH REEF
	PITCAIRN_I                        DXCC = 172 // 172  = PITCAIRN I.
	MICRONESIA                        DXCC = 173 // 173  = MICRONESIA
	MIDWAY_I                          DXCC = 174 // 174  = MIDWAY I.
	FRENCH_POLYNESIA                  DXCC = 175 // 175  = FRENCH POLYNESIA
	FIJI                              DXCC = 176 // 176  = FIJI
	MINAMI_TORISHIMA                  DXCC = 177 // 177  = MINAMI TORISHIMA
	MOLDOVA                           DXCC = 179 // 179  = MOLDOVA
	MOUNT_ATHOS                       DXCC = 180 // 180  = MOUNT ATHOS
	MOZAMBIQUE                        DXCC = 181 // 181  = MOZAMBIQUE
	NAVASSA_I                         DXCC = 182 // 182  = NAVASSA I.
	SOLOMON_IS                        DXCC = 185 // 185  = SOLOMON IS.
	NIGER                             DXCC = 187 // 187  = NIGER
	NIUE                              DXCC = 188 // 188  = NIUE
	NORFOLK_I                         DXCC = 189 // 189  = NORFOLK I.
	SAMOA                             DXCC = 190 // 190  = SAMOA
	NORTH_COOK_IS                     DXCC = 191 // 191  = NORTH COOK IS.
	OGASAWARA                         DXCC = 192 // 192  = OGASAWARA
	ANNOBON_I                         DXCC = 195 // 195  = ANNOBON I.
	PALMYRA_AND_JARVIS_IS             DXCC = 197 // 197  = PALMYRA & JARVIS IS.
	PETER_1_I                         DXCC = 199 // 199  = PETER 1 I.
	PRINCE_EDWARD_AND_MARION_IS       DXCC = 201 // 201  = PRINCE EDWARD & MARION IS.
	PUERTO_RICO                       DXCC = 202 // 202  = PUERTO RICO
	ANDORRA                           DXCC = 203 // 203  = ANDORRA
	REVILLAGIGEDO                     DXCC = 204 // 204  = REVILLAGIGEDO
	ASCENSION_I                       DXCC = 205 // 205  = ASCENSION I.
	AUSTRIA                           DXCC = 206 // 206  = AUSTRIA
	RODRIGUES_I                       DXCC = 207 // 207  = RODRIGUES I.
	BELGIUM                           DXCC = 209 // 209  = BELGIUM
	SABLE_I                           DXCC = 211 // 211  = SABLE I.
	BULGARIA                          DXCC = 212 // 212  = BULGARIA
	SAINT_MARTIN                      DXCC = 213 // 213  = SAINT MARTIN
	CORSICA                           DXCC = 214 // 214  = CORSICA
	CYPRUS                            DXCC = 215 // 215  = CYPRUS
	SAN_ANDRES_AND_PROVIDENCIA        DXCC = 216 // 216  = SAN ANDRES & PROVIDENCIA
	SAN_FELIX_AND_SAN_AMBROSIO        DXCC = 217 // 217  = SAN FELIX & SAN AMBROSIO
	SAO_TOME_AND_PRINCIPE             DXCC = 219 // 219  = SAO TOME & PRINCIPE
	DENMARK                           DXCC = 221 // 221  = DENMARK
	FAROE_IS                          DXCC = 222 // 222  = FAROE IS.
	ENGLAND                           DXCC = 223 // 223  = ENGLAND
	FINLAND                           DXCC = 224 // 224  = FINLAND
	SARDINIA                          DXCC = 225 // 225  = SARDINIA
	FRANCE                            DXCC = 227 // 227  = FRANCE
	FEDERAL_REPUBLIC_OF_GERMANY       DXCC = 230 // 230  = FEDERAL REPUBLIC OF GERMANY
	SOMALIA                           DXCC = 232 // 232  = SOMALIA
	GIBRALTAR                         DXCC = 233 // 233  = GIBRALTAR
	SOUTH_COOK_IS                     DXCC = 234 // 234  = SOUTH COOK IS.
	SOUTH_GEORGIA_I                   DXCC = 235 // 235  = SOUTH GEORGIA I.
	GREECE                            DXCC = 236 // 236  = GREECE
	GREENLAND                         DXCC = 237 // 237  = GREENLAND
	SOUTH_ORKNEY_IS                   DXCC = 238 // 238  = SOUTH ORKNEY IS.
	HUNGARY                           DXCC = 239 // 239  = HUNGARY
	SOUTH_SANDWICH_IS                 DXCC = 240 // 240  = SOUTH SANDWICH IS.
	SOUTH_SHETLAND_IS                 DXCC = 241 // 241  = SOUTH SHETLAND IS.
	ICELAND                           DXCC = 242 // 242  = ICELAND
	IRELAND                           DXCC = 245 // 245  = IRELAND
	SOVEREIGN_MILITARY_ORDER_OF_MALTA DXCC = 246 // 246  = SOVEREIGN MILITARY ORDER OF MALTA
	SPRATLY_IS                        DXCC = 247 // 247  = SPRATLY IS.
	ITALY                             DXCC = 248 // 248  = ITALY
	ST_KITTS_AND_NEVIS                DXCC = 249 // 249  = ST. KITTS & NEVIS
	ST_HELENA                         DXCC = 250 // 250  = ST. HELENA
	LIECHTENSTEIN                     DXCC = 251 // 251  = LIECHTENSTEIN
	ST_PAUL_I                         DXCC = 252 // 252  = ST. PAUL I.
	ST_PETER_AND_ST_PAUL_ROCKS        DXCC = 253 // 253  = ST. PETER & ST. PAUL ROCKS
	LUXEMBOURG                        DXCC = 254 // 254  = LUXEMBOURG
	MADEIRA_IS                        DXCC = 256 // 256  = MADEIRA IS.
	MALTA                             DXCC = 257 // 257  = MALTA
	SVALBARD                          DXCC = 259 // 259  = SVALBARD
	MONACO                            DXCC = 260 // 260  = MONACO
	TAJIKISTAN                        DXCC = 262 // 262  = TAJIKISTAN
	NETHERLANDS                       DXCC = 263 // 263  = NETHERLANDS
	NORTHERN_IRELAND                  DXCC = 265 // 265  = NORTHERN IRELAND
	NORWAY                            DXCC = 266 // 266  = NORWAY
	POLAND                            DXCC = 269 // 269  = POLAND
	TOKELAU_IS                        DXCC = 270 // 270  = TOKELAU IS.
	PORTUGAL                          DXCC = 272 // 272  = PORTUGAL
	TRINDADE_AND_MARTIM_VAZ_IS        DXCC = 273 // 273  = TRINDADE & MARTIM VAZ IS.
	TRISTAN_DA_CUNHA_AND_GOUGH_I      DXCC = 274 // 274  = TRISTAN DA CUNHA & GOUGH I.
	ROMANIA                           DXCC = 275 // 275  = ROMANIA
	TROMELIN_I                        DXCC = 276 // 276  = TROMELIN I.
	ST_PIERRE_AND_MIQUELON            DXCC = 277 // 277  = ST. PIERRE & MIQUELON
	SAN_MARINO                        DXCC = 278 // 278  = SAN MARINO
	SCOTLAND                          DXCC = 279 // 279  = SCOTLAND
	TURKMENISTAN                      DXCC = 280 // 280  = TURKMENISTAN
	SPAIN                             DXCC = 281 // 281  = SPAIN
	TUVALU                            DXCC = 282 // 282  = TUVALU
	UK_SOVEREIGN_BASE_AREAS_ON_CYPRUS DXCC = 283 // 283  = UK SOVEREIGN BASE AREAS ON CYPRUS
	SWEDEN                            DXCC = 284 // 284  = SWEDEN
	VIRGIN_IS                         DXCC = 285 // 285  = VIRGIN IS.
	UGANDA                            DXCC = 286 // 286  = UGANDA
	SWITZERLAND                       DXCC = 287 // 287  = SWITZERLAND
	UKRAINE                           DXCC = 288 // 288  = UKRAINE
	UNITED_NATIONS_HQ                 DXCC = 289 // 289  = UNITED NATIONS HQ
	UNITED_STATES_OF_AMERICA          DXCC = 291 // 291  = UNITED STATES OF AMERICA
	UZBEKISTAN                        DXCC = 292 // 292  = UZBEKISTAN
	VIET_NAM                          DXCC = 293 // 293  = VIET NAM
	WALES                             DXCC = 294 // 294  = WALES
	VATICAN                           DXCC = 295 // 295  = VATICAN
	SERBIA                            DXCC = 296 // 296  = SERBIA
	WAKE_I                            DXCC = 297 // 297  = WAKE I.
	WALLIS_AND_FUTUNA_IS              DXCC = 298 // 298  = WALLIS & FUTUNA IS.
	WEST_MALAYSIA                     DXCC = 299 // 299  = WEST MALAYSIA
	W_KIRIBATI_GILBERT_IS             DXCC = 301 // 301  = W. KIRIBATI (GILBERT IS. )
	WESTERN_SAHARA                    DXCC = 302 // 302  = WESTERN SAHARA
	WILLIS_I                          DXCC = 303 // 303  = WILLIS I.
	BAHRAIN                           DXCC = 304 // 304  = BAHRAIN
	BANGLADESH                        DXCC = 305 // 305  = BANGLADESH
	BHUTAN                            DXCC = 306 // 306  = BHUTAN
	COSTA_RICA                        DXCC = 308 // 308  = COSTA RICA
	MYANMAR                           DXCC = 309 // 309  = MYANMAR
	CAMBODIA                          DXCC = 312 // 312  = CAMBODIA
	SRI_LANKA                         DXCC = 315 // 315  = SRI LANKA
	CHINA                             DXCC = 318 // 318  = CHINA
	HONG_KONG                         DXCC = 321 // 321  = HONG KONG
	INDIA                             DXCC = 324 // 324  = INDIA
	INDONESIA                         DXCC = 327 // 327  = INDONESIA
	IRAN                              DXCC = 330 // 330  = IRAN
	IRAQ                              DXCC = 333 // 333  = IRAQ
	ISRAEL                            DXCC = 336 // 336  = ISRAEL
	JAPAN                             DXCC = 339 // 339  = JAPAN
	JORDAN                            DXCC = 342 // 342  = JORDAN
	DEMOCRATIC_PEOPLES_REP_OF_KOREA   DXCC = 344 // 344  = DEMOCRATIC PEOPLE'S REP. OF KOREA
	BRUNEI_DARUSSALAM                 DXCC = 345 // 345  = BRUNEI DARUSSALAM
	KUWAIT                            DXCC = 348 // 348  = KUWAIT
	LEBANON                           DXCC = 354 // 354  = LEBANON
	MONGOLIA                          DXCC = 363 // 363  = MONGOLIA
	NEPAL                             DXCC = 369 // 369  = NEPAL
	OMAN                              DXCC = 370 // 370  = OMAN
	PAKISTAN                          DXCC = 372 // 372  = PAKISTAN
	PHILIPPINES                       DXCC = 375 // 375  = PHILIPPINES
	QATAR                             DXCC = 376 // 376  = QATAR
	SAUDI_ARABIA                      DXCC = 378 // 378  = SAUDI ARABIA
	SEYCHELLES                        DXCC = 379 // 379  = SEYCHELLES
	SINGAPORE                         DXCC = 381 // 381  = SINGAPORE
	DJIBOUTI                          DXCC = 382 // 382  = DJIBOUTI
	SYRIA                             DXCC = 384 // 384  = SYRIA
	TAIWAN                            DXCC = 386 // 386  = TAIWAN
	THAILAND                          DXCC = 387 // 387  = THAILAND
	TURKEY                            DXCC = 390 // 390  = TURKEY
	UNITED_ARAB_EMIRATES              DXCC = 391 // 391  = UNITED ARAB EMIRATES
	ALGERIA                           DXCC = 400 // 400  = ALGERIA
	ANGOLA                            DXCC = 401 // 401  = ANGOLA
	BOTSWANA                          DXCC = 402 // 402  = BOTSWANA
	BURUNDI                           DXCC = 404 // 404  = BURUNDI
	CAMEROON                          DXCC = 406 // 406  = CAMEROON
	CENTRAL_AFRICA                    DXCC = 408 // 408  = CENTRAL AFRICA
	CAPE_VERDE                        DXCC = 409 // 409  = CAPE VERDE
	CHAD                              DXCC = 410 // 410  = CHAD
	COMOROS                           DXCC = 411 // 411  = COMOROS
	REPUBLIC_OF_THE_CONGO             DXCC = 412 // 412  = REPUBLIC OF THE CONGO
	DEMOCRATIC_REPUBLIC_OF_THE_CONGO  DXCC = 414 // 414  = DEMOCRATIC REPUBLIC OF THE CONGO
	BENIN                             DXCC = 416 // 416  = BENIN
	GABON                             DXCC = 420 // 420  = GABON
	THE_GAMBIA                        DXCC = 422 // 422  = THE GAMBIA
	GHANA                             DXCC = 424 // 424  = GHANA
	COTE_DIVOIRE                      DXCC = 428 // 428  = COTE D'IVOIRE
	KENYA                             DXCC = 430 // 430  = KENYA
	LESOTHO                           DXCC = 432 // 432  = LESOTHO
	LIBERIA                           DXCC = 434 // 434  = LIBERIA
	LIBYA                             DXCC = 436 // 436  = LIBYA
	MADAGASCAR                        DXCC = 438 // 438  = MADAGASCAR
	MALAWI                            DXCC = 440 // 440  = MALAWI
	MALI                              DXCC = 442 // 442  = MALI
	MAURITANIA                        DXCC = 444 // 444  = MAURITANIA
	MOROCCO                           DXCC = 446 // 446  = MOROCCO
	NIGERIA                           DXCC = 450 // 450  = NIGERIA
	ZIMBABWE                          DXCC = 452 // 452  = ZIMBABWE
	REUNION_I                         DXCC = 453 // 453  = REUNION I.
	RWANDA                            DXCC = 454 // 454  = RWANDA
	SENEGAL                           DXCC = 456 // 456  = SENEGAL
	SIERRA_LEONE                      DXCC = 458 // 458  = SIERRA LEONE
	ROTUMA_I                          DXCC = 460 // 460  = ROTUMA I.
	REPUBLIC_OF_SOUTH_AFRICA          DXCC = 462 // 462  = REPUBLIC OF SOUTH AFRICA
	NAMIBIA                           DXCC = 464 // 464  = NAMIBIA
	SUDAN                             DXCC = 466 // 466  = SUDAN
	KINGDOM_OF_ESWATINI               DXCC = 468 // 468  = KINGDOM OF ESWATINI
	TANZANIA                          DXCC = 470 // 470  = TANZANIA
	TUNISIA                           DXCC = 474 // 474  = TUNISIA
	EGYPT                             DXCC = 478 // 478  = EGYPT
	BURKINA_FASO                      DXCC = 480 // 480  = BURKINA FASO
	ZAMBIA                            DXCC = 482 // 482  = ZAMBIA
	TOGO                              DXCC = 483 // 483  = TOGO
	CONWAY_REEF                       DXCC = 489 // 489  = CONWAY REEF
	BANABA_I_OCEAN_I                  DXCC = 490 // 490  = BANABA I. (OCEAN I.)
	YEMEN                             DXCC = 492 // 492  = YEMEN
	CROATIA                           DXCC = 497 // 497  = CROATIA
	SLOVENIA                          DXCC = 499 // 499  = SLOVENIA
	BOSNIA_HERZEGOVINA                DXCC = 501 // 501  = BOSNIA-HERZEGOVINA
	NORTH_MACEDONIA_REPUBLIC_OF       DXCC = 502 // 502  = NORTH MACEDONIA (REPUBLIC OF)
	CZECH_REPUBLIC                    DXCC = 503 // 503  = CZECH REPUBLIC
	SLOVAK_REPUBLIC                   DXCC = 504 // 504  = SLOVAK REPUBLIC
	PRATAS_I                          DXCC = 505 // 505  = PRATAS I.
	SCARBOROUGH_REEF                  DXCC = 506 // 506  = SCARBOROUGH REEF
	TEMOTU_PROVINCE                   DXCC = 507 // 507  = TEMOTU PROVINCE
	AUSTRAL_I                         DXCC = 508 // 508  = AUSTRAL I.
	MARQUESAS_IS                      DXCC = 509 // 509  = MARQUESAS IS.
	PALESTINE                         DXCC = 510 // 510  = PALESTINE
	TIMOR_LESTE                       DXCC = 511 // 511  = TIMOR-LESTE
	CHESTERFIELD_IS                   DXCC = 512 // 512  = CHESTERFIELD IS.
	DUCIE_I                           DXCC = 513 // 513  = DUCIE I.
	MONTENEGRO                        DXCC = 514 // 514  = MONTENEGRO
	SWAINS_I                          DXCC = 515 // 515  = SWAINS I.
	SAINT_BARTHELEMY                  DXCC = 516 // 516  = SAINT BARTHELEMY
	CURACAO                           DXCC = 517 // 517  = CURACAO
	SINT_MAARTEN                      DXCC = 518 // 518  = SINT MAARTEN
	SABA_AND_ST_EUSTATIUS             DXCC = 519 // 519  = SABA & ST. EUSTATIUS
	BONAIRE                           DXCC = 520 // 520  = BONAIRE
	SOUTH_SUDAN_REPUBLIC_OF           DXCC = 521 // 521  = SOUTH SUDAN (REPUBLIC OF)
	REPUBLIC_OF_KOSOVO                DXCC = 522 // 522  = REPUBLIC OF KOSOVO
)
