package main

import (
	"go/format"
	"os"
	"path/filepath"

	"github.com/hamradiolog-net/spec"
)

func main() {
	writeToFile("aditype", "adi_data_type_gen.go", GenerateGoCodeForDataTypeDefinition(spec.DataTypeList))
	writeToFile("adifield", "field_gen.go", GenerateGoCodeForFieldDefinition(spec.FieldList))

	writeToFile("antpath", "enum_ant_path_gen.go", GenerateGoCodeForAntPathEnumItem(spec.EnumAntPathList))
	writeToFile("arrlsection", "enum_arrl_section_gen.go", GenerateGoCodeForARRLSectionEnumItem(spec.EnumARRLSectionList))
	writeToFile("awardsponsor", "enum_award_sponsor_gen.go", GenerateGoCodeForAwardSponsorEnumItem(spec.EnumAwardSponsorList))
	writeToFile("award", "enum_award_gen.go", GenerateGoCodeForAwardEnumItem(spec.EnumAwardList))
	writeToFile("band", "enum_band_gen.go", GenerateGoCodeForBandEnumItem(spec.EnumBandList))
	writeToFile("contest", "enum_contest_gen.go", GenerateGoCodeForContestEnumItem(spec.EnumContestList))
	writeToFile("continent", "enum_continent_gen.go", GenerateGoCodeForContinentEnumItem(spec.EnumContinentList))
	writeToFile("credit", "enum_credit_gen.go", GenerateGoCodeForCreditEnumItem(spec.EnumCreditList))
	writeToFile("dxccentitycode", "enum_dxcc_entity_code_gen.go", GenerateGoCodeForDXCCEnumItem(spec.EnumDXCCEntityCodeList))
	writeToFile("mode", "enum_mode_gen.go", GenerateGoCodeForModeEnumItem(spec.EnumModeList))
	writeToFile("morsekey", "enum_morse_key_gen.go", GenerateGoCodeForMorseKeyEnumItem(spec.EnumMorseKeyList))
	// These codes are not unique, so for now, we don't want to generate the list of constants...
	// writeToFile("enum_primary_administrative_subdivision_gen.go", GenerateGoCodeForPrimaryAdministrativeSubdivisionEnumItem(spec.EnumPrimaryAdministrativeSubdivisionList))
	writeToFile("propagationmode", "enum_propagation_mode_gen.go", GenerateGoCodeForPropagationModeEnumItem(spec.EnumPropagationModeList))
	writeToFile("qslmedium", "enum_qsl_medium_gen.go", GenerateGoCodeForQSLMediumEnumItem(spec.EnumQSLMediumList))
	writeToFile("qslrcvd", "enum_qsl_rcvd_gen.go", GenerateGoCodeForQSLRcvdEnumItem(spec.EnumQSLRcvdList))
	writeToFile("qslsent", "enum_qsl_sent_gen.go", GenerateGoCodeForQSLSentEnumItem(spec.EnumQSLSentList))
	writeToFile("qslvia", "enum_qsl_via_gen.go", GenerateGoCodeForQSLViaEnumItem(spec.EnumQSLViaList))
	writeToFile("qsocomplete", "enum_qso_complete_gen.go", GenerateGoCodeForQSOCompleteEnumItem(spec.EnumQSOCompleteList))
	writeToFile("qsodownloadstatus", "enum_qso_download_status_gen.go", GenerateGoCodeForQSODownloadStatusEnumItem(spec.EnumQSODownloadStatusList))
	writeToFile("qsouploadstatus", "enum_qso_upload_status_gen.go", GenerateGoCodeForQSOUploadStatusEnumItem(spec.EnumQSOUploadStatusList))
	writeToFile("region", "enum_region_gen.go", GenerateGoCodeForRegionEnumItem(spec.EnumRegionList))
	writeToFile("secondaryadministrativesubdivisionalt", "enum_secondary_administrative_subdivision_alt_gen.go", GenerateGoCodeForSecondaryAdministrativeSubdivisionAltEnumItem(spec.EnumSecondaryAdministrativeSubdivisionAltList))
	writeToFile("secondaryadministrativesubdivision", "enum_secondary_administrative_subdivision_gen.go", GenerateGoCodeForSecondaryAdministrativeSubdivisionEnumItem(spec.EnumSecondaryAdministrativeSubdivisionList))
	writeToFile("mode", "enum_submode_gen.go", GenerateGoCodeForSubModeEnumItem(spec.EnumSubModeList))
}

func writeToFile(dir, filename, content string) {
	fullPath := filepath.Join("../../pkg", dir, filename)
	os.MkdirAll(filepath.Dir(fullPath), 0755)

	content = "// DO NOT EDIT\n// Code generated by ./cmd/codegen/codegen\n\n// This file contains CURRENTLY valid constants.\n// It is not a full list of all possible historic and/or future values.\n\n" + content

	formatted, fmtErr := format.Source([]byte(content))
	if fmtErr != nil {
		panic(fmtErr)
		// formatted = []byte(content)
	}

	err := os.WriteFile(fullPath, formatted, 0644)
	if err != nil {
		panic(err)
	}
}
