// DO NOT EDIT
// Code generated by ./cmd/codegen/codegen

// This file contains CURRENTLY valid constants.
// It is not a full list of all possible historic and/or future values.

package qsocomplete

var (
	Y         QSOComplete = "Y"   // Y = yes
	N         QSOComplete = "N"   // N = no
	NIL       QSOComplete = "NIL" // NIL = not heard
	Uncertain QSOComplete = "?"   // ? = uncertain
)
