// DO NOT EDIT
// Code generated by ./cmd/codegen/codegen

// This file contains CURRENTLY valid constants.
// It is not a full list of all possible historic and/or future values.

package morsekey

var (
	SK  MorseKey = "SK"  // SK  = Straight Key
	SS  MorseKey = "SS"  // SS  = Sideswiper
	BUG MorseKey = "BUG" // BUG = Mechanical semi-automatic keyer or Bug
	FAB MorseKey = "FAB" // FAB = Mechanical fully-automatic keyer or Bug
	SP  MorseKey = "SP"  // SP  = Single Paddle
	DP  MorseKey = "DP"  // DP  = Dual Paddle
	CPU MorseKey = "CPU" // CPU = Computer Driven
)
