// DO NOT EDIT
// Code generated by ./cmd/codegen/codegen

// This file contains CURRENTLY valid constants.
// It is not a full list of all possible historic and/or future values.

package qslsent

var (
	Y QSLSent = "Y" // Y = yes
	N QSLSent = "N" // N = no
	R QSLSent = "R" // R = requested
	Q QSLSent = "Q" // Q = queued
	I QSLSent = "I" // I = ignore or invalid
)
