// DO NOT EDIT
// Code generated by ./cmd/codegen/codegen

// This file contains CURRENTLY valid constants.
// It is not a full list of all possible historic and/or future values.

package mode

var (
	ModeAM           Mode = "AM"           // AM
	ModeARDOP        Mode = "ARDOP"        // ARDOP
	ModeATV          Mode = "ATV"          // ATV
	ModeCHIP         Mode = "CHIP"         // CHIP            = [ CHIP64, CHIP128 ]
	ModeCLO          Mode = "CLO"          // CLO
	ModeCONTESTI     Mode = "CONTESTI"     // CONTESTI
	ModeCW           Mode = "CW"           // CW              = [ PCW ]
	ModeDIGITALVOICE Mode = "DIGITALVOICE" // DIGITALVOICE    = [ C4FM, DMR, DSTAR, FREEDV, M17 ]
	ModeDOMINO       Mode = "DOMINO"       // DOMINO          = [ DOM-M, DOM4, DOM5, DOM8, DOM11, DOM16, DOM22, DOM44, DOM88, DOMINOEX, DOMINOF ]
	ModeDYNAMIC      Mode = "DYNAMIC"      // DYNAMIC         = [ VARA HF, VARA SATELLITE, VARA FM 1200, VARA FM 9600 ]
	ModeFAX          Mode = "FAX"          // FAX
	ModeFM           Mode = "FM"           // FM
	ModeFSK441       Mode = "FSK441"       // FSK441
	ModeFT8          Mode = "FT8"          // FT8
	ModeHELL         Mode = "HELL"         // HELL            = [ FMHELL, FSKH105, FSKH245, FSKHELL, HELL80, HELLX5, HELLX9, HFSK, PSKHELL, SLOWHELL ]
	ModeISCAT        Mode = "ISCAT"        // ISCAT           = [ ISCAT-A, ISCAT-B ]
	ModeJT4          Mode = "JT4"          // JT4             = [ JT4A, JT4B, JT4C, JT4D, JT4E, JT4F, JT4G ]
	ModeJT6M         Mode = "JT6M"         // JT6M
	ModeJT9          Mode = "JT9"          // JT9             = [ JT9-1, JT9-2, JT9-5, JT9-10, JT9-30, JT9A, JT9B, JT9C, JT9D, JT9E, JT9E FAST, JT9F, JT9F FAST, JT9G, JT9G FAST, JT9H, JT9H FAST ]
	ModeJT44         Mode = "JT44"         // JT44
	ModeJT65         Mode = "JT65"         // JT65            = [ JT65A, JT65B, JT65B2, JT65C, JT65C2 ]
	ModeMFSK         Mode = "MFSK"         // MFSK            = [ FSQCALL, FST4, FST4W, FT4, JS8, JTMS, MFSK4, MFSK8, MFSK11, MFSK16, MFSK22, MFSK31, MFSK32, MFSK64, MFSK64L, MFSK128 MFSK128L, Q65 ]
	ModeMSK144       Mode = "MSK144"       // MSK144
	ModeMT63         Mode = "MT63"         // MT63
	ModeOLIVIA       Mode = "OLIVIA"       // OLIVIA          = [ OLIVIA 4/125, OLIVIA 4/250, OLIVIA 8/250, OLIVIA 8/500, OLIVIA 16/500, OLIVIA 16/1000, OLIVIA 32/1000 ]
	ModeOPERA        Mode = "OPERA"        // OPERA           = [ OPERA-BEACON, OPERA-QSO ]
	ModePAC          Mode = "PAC"          // PAC             = [ PAC2, PAC3, PAC4 ]
	ModePAX          Mode = "PAX"          // PAX             = [ PAX2 ]
	ModePKT          Mode = "PKT"          // PKT
	ModePSK          Mode = "PSK"          // PSK             = [ 8PSK125, 8PSK125F, 8PSK125FL, 8PSK250, 8PSK250F, 8PSK250FL, 8PSK500, 8PSK500F, 8PSK1000, 8PSK1000F, 8PSK1200F, FSK31, PSK10, PSK31, PSK63, PSK63F, PSK63RC4, PSK63RC5, PSK63RC10, PSK63RC20, PSK63RC32, PSK125, PSK125C12, PSK125R, PSK125RC10, PSK125RC12, PSK125RC16, PSK125RC4, PSK125RC5, PSK250, PSK250C6, PSK250R, PSK250RC2, PSK250RC3, PSK250RC5, PSK250RC6, PSK250RC7, PSK500, PSK500C2, PSK500C4, PSK500R, PSK500RC2, PSK500RC3, PSK500RC4, PSK800C2, PSK800RC2, PSK1000, PSK1000C2, PSK1000R, PSK1000RC2, PSKAM10, PSKAM31, PSKAM50, PSKFEC31, QPSK31, QPSK63, QPSK125, QPSK250, QPSK500, SIM31 ]
	ModePSK2K        Mode = "PSK2K"        // PSK2K
	ModeQ15          Mode = "Q15"          // Q15
	ModeQRA64        Mode = "QRA64"        // QRA64           = [ QRA64A, QRA64B, QRA64C, QRA64D, QRA64E ]
	ModeROS          Mode = "ROS"          // ROS             = [ ROS-EME, ROS-HF, ROS-MF ]
	ModeRTTY         Mode = "RTTY"         // RTTY            = [ ASCI ]
	ModeRTTYM        Mode = "RTTYM"        // RTTYM
	ModeSSB          Mode = "SSB"          // SSB             = [ LSB, USB ]
	ModeSSTV         Mode = "SSTV"         // SSTV
	ModeT10          Mode = "T10"          // T10
	ModeTHOR         Mode = "THOR"         // THOR            = [ THOR-M, THOR4, THOR5, THOR8, THOR11, THOR16, THOR22, THOR25X4, THOR50X1, THOR50X2, THOR100 ]
	ModeTHRB         Mode = "THRB"         // THRB            = [ THRBX, THRBX1, THRBX2, THRBX4, THROB1, THROB2, THROB4 ]
	ModeTOR          Mode = "TOR"          // TOR             = [ AMTORFEC, GTOR, NAVTEX, SITORB ]
	ModeV4           Mode = "V4"           // V4
	ModeVOI          Mode = "VOI"          // VOI
	ModeWINMOR       Mode = "WINMOR"       // WINMOR
	ModeWSPR         Mode = "WSPR"         // WSPR
)
