// DO NOT EDIT
// Code generated by ./cmd/codegen/codegen

// This file contains CURRENTLY valid constants.
// It is not a full list of all possible historic and/or future values.

package band

var (
	Band2190m  Band = "2190m"  //       0.1357 MHz -       0.1378 MHz = 2190m
	Band630m   Band = "630m"   //       0.4720 MHz -       0.4790 MHz = 630m
	Band560m   Band = "560m"   //       0.5010 MHz -       0.5040 MHz = 560m
	Band160m   Band = "160m"   //       1.8000 MHz -       2.0000 MHz = 160m
	Band80m    Band = "80m"    //       3.5000 MHz -       4.0000 MHz = 80m
	Band60m    Band = "60m"    //       5.0600 MHz -       5.4500 MHz = 60m
	Band40m    Band = "40m"    //       7.0000 MHz -       7.3000 MHz = 40m
	Band30m    Band = "30m"    //      10.1000 MHz -      10.1500 MHz = 30m
	Band20m    Band = "20m"    //      14.0000 MHz -      14.3500 MHz = 20m
	Band17m    Band = "17m"    //      18.0680 MHz -      18.1680 MHz = 17m
	Band15m    Band = "15m"    //      21.0000 MHz -      21.4500 MHz = 15m
	Band12m    Band = "12m"    //      24.8900 MHz -      24.9900 MHz = 12m
	Band10m    Band = "10m"    //      28.0000 MHz -      29.7000 MHz = 10m
	Band8m     Band = "8m"     //      40.0000 MHz -      45.0000 MHz = 8m
	Band6m     Band = "6m"     //      50.0000 MHz -      54.0000 MHz = 6m
	Band5m     Band = "5m"     //      54.0000 MHz -      69.9000 MHz = 5m
	Band4m     Band = "4m"     //      70.0000 MHz -      71.0000 MHz = 4m
	Band2m     Band = "2m"     //     144.0000 MHz -     148.0000 MHz = 2m
	Band1_25m  Band = "1.25m"  //     222.0000 MHz -     225.0000 MHz = 1.25m
	Band70cm   Band = "70cm"   //     420.0000 MHz -     450.0000 MHz = 70cm
	Band33cm   Band = "33cm"   //     902.0000 MHz -     928.0000 MHz = 33cm
	Band23cm   Band = "23cm"   //    1240.0000 MHz -    1300.0000 MHz = 23cm
	Band13cm   Band = "13cm"   //    2300.0000 MHz -    2450.0000 MHz = 13cm
	Band9cm    Band = "9cm"    //    3300.0000 MHz -    3500.0000 MHz = 9cm
	Band6cm    Band = "6cm"    //    5650.0000 MHz -    5925.0000 MHz = 6cm
	Band3cm    Band = "3cm"    //   10000.0000 MHz -   10500.0000 MHz = 3cm
	Band1_25cm Band = "1.25cm" //   24000.0000 MHz -   24250.0000 MHz = 1.25cm
	Band6mm    Band = "6mm"    //   47000.0000 MHz -   47200.0000 MHz = 6mm
	Band4mm    Band = "4mm"    //   75500.0000 MHz -   81000.0000 MHz = 4mm
	Band2_5mm  Band = "2.5mm"  //  119980.0000 MHz -  123000.0000 MHz = 2.5mm
	Band2mm    Band = "2mm"    //  134000.0000 MHz -  149000.0000 MHz = 2mm
	Band1mm    Band = "1mm"    //  241000.0000 MHz -  250000.0000 MHz = 1mm
	Bandsubmm  Band = "submm"  //  300000.0000 MHz - 7500000.0000 MHz = submm
)
