// DO NOT EDIT
// Code generated by ./cmd/codegen/codegen

// This file contains CURRENTLY valid constants.
// It is not a full list of all possible historic and/or future values.

package qsouploadstatus

var (
	Y QSOUploadStatus = "Y" // Y = the QSO has been uploaded to, and accepted by, the online service
	N QSOUploadStatus = "N" // N = do not upload the QSO to the online service
	M QSOUploadStatus = "M" // M = the QSO has been modified since being uploaded to the online service
)
