// DO NOT EDIT
// Code generated by ./cmd/codegen/codegen

// This file contains CURRENTLY valid constants.
// It is not a full list of all possible historic and/or future values.

package qsouploadstatus

var (
	Y QSOUploadStatus = "Y" // Y = the QSO has been downloaded from the online service
	N QSOUploadStatus = "N" // N = the QSO has not been downloaded from the online service
	I QSOUploadStatus = "I" // I = ignore or invalid
)
