// DO NOT EDIT
// Code generated by ./cmd/codegen/codegen

// This file contains CURRENTLY valid constants.
// It is not a full list of all possible historic and/or future values.

package qsodownloadstatus

var (
	Y QSODownloadStatus = "Y" // Y = the QSO has been downloaded from the online service
	N QSODownloadStatus = "N" // N = the QSO has not been downloaded from the online service
	I QSODownloadStatus = "I" // I = ignore or invalid
)
