// DO NOT EDIT
// Code generated by ./cmd/codegen/codegen

// This file contains CURRENTLY valid constants.
// It is not a full list of all possible historic and/or future values.

package antpath

var (
	G AntPath = "G" // G = grayline
	O AntPath = "O" // O = other
	S AntPath = "S" // S = short path
	L AntPath = "L" // L = long path
)
