// DO NOT EDIT
// Code generated by ./cmd/codegen/codegen

// This file contains CURRENTLY valid constants.
// It is not a full list of all possible historic and/or future values.

package qslmedium

var (
	CARD QSLMedium = "CARD" // CARD  = QSO confirmation via paper QSL card
	EQSL QSLMedium = "EQSL" // EQSL  = QSO confirmation via eQSL.cc
	LOTW QSLMedium = "LOTW" // LOTW  = QSO confirmation via ARRL Logbook of the World
)
