// DO NOT EDIT
// Code generated by ./cmd/codegen/codegen

// This file contains CURRENTLY valid constants.
// It is not a full list of all possible historic and/or future values.

package credit

var (
	CQDX                Credit = "CQDX"                // CQDX                 Mixed      CQ Magazine     DX
	CQDX_BAND           Credit = "CQDX_BAND"           // CQDX_BAND            Band       CQ Magazine     DX
	CQDX_MODE           Credit = "CQDX_MODE"           // CQDX_MODE            Mode       CQ Magazine     DX
	CQDX_MOBILE         Credit = "CQDX_MOBILE"         // CQDX_MOBILE          Mobile     CQ Magazine     DX
	CQDX_QRP            Credit = "CQDX_QRP"            // CQDX_QRP             QRP        CQ Magazine     DX
	CQDX_SATELLITE      Credit = "CQDX_SATELLITE"      // CQDX_SATELLITE       Satellite  CQ Magazine     DX
	CQDXFIELD           Credit = "CQDXFIELD"           // CQDXFIELD            Mixed      CQ Magazine     DX Field
	CQDXFIELD_BAND      Credit = "CQDXFIELD_BAND"      // CQDXFIELD_BAND       Band       CQ Magazine     DX Field
	CQDXFIELD_MODE      Credit = "CQDXFIELD_MODE"      // CQDXFIELD_MODE       Mode       CQ Magazine     DX Field
	CQDXFIELD_MOBILE    Credit = "CQDXFIELD_MOBILE"    // CQDXFIELD_MOBILE     Mobile     CQ Magazine     DX Field
	CQDXFIELD_QRP       Credit = "CQDXFIELD_QRP"       // CQDXFIELD_QRP        QRP        CQ Magazine     DX Field
	CQDXFIELD_SATELLITE Credit = "CQDXFIELD_SATELLITE" // CQDXFIELD_SATELLITE  Satellite  CQ Magazine     DX Field
	CQWAZ_MIXED         Credit = "CQWAZ_MIXED"         // CQWAZ_MIXED          Mixed      CQ Magazine     Worked All Zones (WAZ)
	CQWAZ_BAND          Credit = "CQWAZ_BAND"          // CQWAZ_BAND           Band       CQ Magazine     Worked All Zones (WAZ)
	CQWAZ_MODE          Credit = "CQWAZ_MODE"          // CQWAZ_MODE           Mode       CQ Magazine     Worked All Zones (WAZ)
	CQWAZ_SATELLITE     Credit = "CQWAZ_SATELLITE"     // CQWAZ_SATELLITE      Satellite  CQ Magazine     Worked All Zones (WAZ)
	CQWAZ_EME           Credit = "CQWAZ_EME"           // CQWAZ_EME            EME        CQ Magazine     Worked All Zones (WAZ)
	CQWAZ_MOBILE        Credit = "CQWAZ_MOBILE"        // CQWAZ_MOBILE         Mobile     CQ Magazine     Worked All Zones (WAZ)
	CQWAZ_QRP           Credit = "CQWAZ_QRP"           // CQWAZ_QRP            QRP        CQ Magazine     Worked All Zones (WAZ)
	CQWPX               Credit = "CQWPX"               // CQWPX                Mixed      CQ Magazine     WPX
	CQWPX_BAND          Credit = "CQWPX_BAND"          // CQWPX_BAND           Band       CQ Magazine     WPX
	CQWPX_MODE          Credit = "CQWPX_MODE"          // CQWPX_MODE           Mode       CQ Magazine     WPX
	DXCC                Credit = "DXCC"                // DXCC                 Mixed      ARRL            DX Century Club (DXCC)
	DXCC_BAND           Credit = "DXCC_BAND"           // DXCC_BAND            Band       ARRL            DX Century Club (DXCC)
	DXCC_MODE           Credit = "DXCC_MODE"           // DXCC_MODE            Mode       ARRL            DX Century Club (DXCC)
	DXCC_SATELLITE      Credit = "DXCC_SATELLITE"      // DXCC_SATELLITE       Satellite  ARRL            DX Century Club (DXCC)
	EAUSTRALIA          Credit = "EAUSTRALIA"          // EAUSTRALIA           Mixed      eQSL            eAustralia
	ECANADA             Credit = "ECANADA"             // ECANADA              Mixed      eQSL            eCanada
	ECOUNTY_STATE       Credit = "ECOUNTY_STATE"       // ECOUNTY_STATE        State      eQSL            eCounty
	EDX                 Credit = "EDX"                 // EDX                  Mixed      eQSL            eDX
	EDX100              Credit = "EDX100"              // EDX100               Mixed      eQSL            eDX100
	EDX100_BAND         Credit = "EDX100_BAND"         // EDX100_BAND          Band       eQSL            eDX100
	EDX100_MODE         Credit = "EDX100_MODE"         // EDX100_MODE          Mode       eQSL            eDX100
	EECHOLINK50         Credit = "EECHOLINK50"         // EECHOLINK50          Echolink   eQSL            eEcholink50
	EGRID_BAND          Credit = "EGRID_BAND"          // EGRID_BAND           Band       eQSL            eGrid
	EGRID_SATELLITE     Credit = "EGRID_SATELLITE"     // EGRID_SATELLITE      Satellite  eQSL            eGrid
	EPFX300             Credit = "EPFX300"             // EPFX300              Mixed      eQSL            ePfx300
	EPFX300_MODE        Credit = "EPFX300_MODE"        // EPFX300_MODE         Mode       eQSL            ePfx300
	EWAS                Credit = "EWAS"                // EWAS                 Mixed      eQSL            eWAS
	EWAS_BAND           Credit = "EWAS_BAND"           // EWAS_BAND            Band       eQSL            eWAS
	EWAS_MODE           Credit = "EWAS_MODE"           // EWAS_MODE            Mode       eQSL            eWAS
	EWAS_SATELLITE      Credit = "EWAS_SATELLITE"      // EWAS_SATELLITE       Satellite  eQSL            eWAS
	EZ40                Credit = "EZ40"                // EZ40                 Mixed      eQSL            eZ40
	EZ40_MODE           Credit = "EZ40_MODE"           // EZ40_MODE            Mode       eQSL            eZ40
	FFMA                Credit = "FFMA"                // FFMA                 Mixed      ARRL            Fred Fish Memorial Award (FFMA)
	IOTA                Credit = "IOTA"                // IOTA                 Mixed      RSGB            Islands on the Air (IOTA)
	IOTA_BASIC          Credit = "IOTA_BASIC"          // IOTA_BASIC           Mixed      RSGB            Islands on the Air (IOTA)
	IOTA_CONT           Credit = "IOTA_CONT"           // IOTA_CONT            Continent  RSGB            Islands on the Air (IOTA)
	IOTA_GROUP          Credit = "IOTA_GROUP"          // IOTA_GROUP           Group      RSGB            Islands on the Air (IOTA)
	RDA                 Credit = "RDA"                 // RDA                  Mixed      TAG             Russian Districts Award (RDA)
	USACA               Credit = "USACA"               // USACA                Mixed      CQ Magazine     United States of America Counties (USA-CA)
	VUCC_BAND           Credit = "VUCC_BAND"           // VUCC_BAND            Band       ARRL            VHF/UHF Century Club Program (VUCC)
	VUCC_SATELLITE      Credit = "VUCC_SATELLITE"      // VUCC_SATELLITE       Satellite  ARRL            VHF/UHF Century Club Program (VUCC)
	WAB                 Credit = "WAB"                 // WAB                  Mixed      WAB AG          Worked All Britain (WAB)
	WAC                 Credit = "WAC"                 // WAC                  Mixed      IARU            Worked All Continents (WAC)
	WAC_BAND            Credit = "WAC_BAND"            // WAC_BAND             Band       IARU            Worked All Continents (WAC)
	WAE                 Credit = "WAE"                 // WAE                  Mixed      DARC            Worked All Europe (WAE)
	WAE_BAND            Credit = "WAE_BAND"            // WAE_BAND             Band       DARC            Worked All Europe (WAE)
	WAE_MODE            Credit = "WAE_MODE"            // WAE_MODE             Mode       DARC            Worked All Europe (WAE)
	WAIP                Credit = "WAIP"                // WAIP                 Mixed      ARI             Worked All Italian Provinces (WAIP)
	WAIP_BAND           Credit = "WAIP_BAND"           // WAIP_BAND            Band       ARI             Worked All Italian Provinces (WAIP)
	WAIP_MODE           Credit = "WAIP_MODE"           // WAIP_MODE            Mode       ARI             Worked All Italian Provinces (WAIP)
	WAS                 Credit = "WAS"                 // WAS                  Mixed      ARRL            Worked All States (WAS)
	WAS_BAND            Credit = "WAS_BAND"            // WAS_BAND             Band       ARRL            Worked All States (WAS)
	WAS_EME             Credit = "WAS_EME"             // WAS_EME              EME        ARRL            Worked All States (WAS)
	WAS_MODE            Credit = "WAS_MODE"            // WAS_MODE             Mode       ARRL            Worked All States (WAS)
	WAS_NOVICE          Credit = "WAS_NOVICE"          // WAS_NOVICE           Novice     ARRL            Worked All States (WAS)
	WAS_QRP             Credit = "WAS_QRP"             // WAS_QRP              QRP        ARRL            Worked All States (WAS)
	WAS_SATELLITE       Credit = "WAS_SATELLITE"       // WAS_SATELLITE        Satellite  ARRL            Worked All States (WAS)
	WITUZ               Credit = "WITUZ"               // WITUZ                Mixed      RSGB            Worked ITU Zones (WITUZ)
	WITUZ_BAND          Credit = "WITUZ_BAND"          // WITUZ_BAND           Band       RSGB            Worked ITU Zones (WITUZ)
)
