// DO NOT EDIT
// Code generated by ./cmd/codegen/codegen

// This file contains CURRENTLY valid constants.
// It is not a full list of all possible historic and/or future values.

package region

var (
	NONE Region = "NONE" // NONE  = DXCC: 0   /       / Not within a WAE or CQ region that is within a DXCC entity
	IV   Region = "IV"   // IV    = DXCC: 206 / 4U1V  / ITU Vienna
	AI   Region = "AI"   // AI    = DXCC: 248 / IG9   / African Italy
	SY   Region = "SY"   // SY    = DXCC: 248 / IT9   / Sicily
	BI   Region = "BI"   // BI    = DXCC: 259 / JW/B  / Bear Island
	SI   Region = "SI"   // SI    = DXCC: 279 / GM/S  / Shetland Islands
	KO   Region = "KO"   // KO    = DXCC: 296 / Z6    / Kosovo
	ET   Region = "ET"   // ET    = DXCC: 390 / TA1   / European Turkey
)
