// GENERATED CODE; DO NOT EDIT
// ADIF: 3.1.6 Proposed

package dxccentitycode

var (
	NONE                                     DXCCEntityCode = 0   // None (the contacted station is known to not be within a DXCC entity)
	CANADA                                   DXCCEntityCode = 1   // CANADA
	ABU_AIL_IS_DELETED                       DXCCEntityCode = 2   // ABU AIL IS.
	AFGHANISTAN                              DXCCEntityCode = 3   // AFGHANISTAN
	AGALEGA_AND_ST_BRANDON_IS                DXCCEntityCode = 4   // AGALEGA & ST. BRANDON IS.
	ALAND_IS                                 DXCCEntityCode = 5   // ALAND IS.
	ALASKA                                   DXCCEntityCode = 6   // ALASKA
	ALBANIA                                  DXCCEntityCode = 7   // ALBANIA
	ALDABRA_DELETED                          DXCCEntityCode = 8   // ALDABRA
	AMERICAN_SAMOA                           DXCCEntityCode = 9   // AMERICAN SAMOA
	AMSTERDAM_AND_ST_PAUL_IS                 DXCCEntityCode = 10  // AMSTERDAM & ST. PAUL IS.
	ANDAMAN_AND_NICOBAR_IS                   DXCCEntityCode = 11  // ANDAMAN & NICOBAR IS.
	ANGUILLA                                 DXCCEntityCode = 12  // ANGUILLA
	ANTARCTICA                               DXCCEntityCode = 13  // ANTARCTICA
	ARMENIA                                  DXCCEntityCode = 14  // ARMENIA
	ASIATIC_RUSSIA                           DXCCEntityCode = 15  // ASIATIC RUSSIA
	NEW_ZEALAND_SUBANTARCTIC_ISLANDS         DXCCEntityCode = 16  // NEW ZEALAND SUBANTARCTIC ISLANDS
	AVES_I                                   DXCCEntityCode = 17  // AVES I.
	AZERBAIJAN                               DXCCEntityCode = 18  // AZERBAIJAN
	BAJO_NUEVO_DELETED                       DXCCEntityCode = 19  // BAJO NUEVO
	BAKER_AND_HOWLAND_IS                     DXCCEntityCode = 20  // BAKER & HOWLAND IS.
	BALEARIC_IS                              DXCCEntityCode = 21  // BALEARIC IS.
	PALAU                                    DXCCEntityCode = 22  // PALAU
	BLENHEIM_REEF_DELETED                    DXCCEntityCode = 23  // BLENHEIM REEF
	BOUVET                                   DXCCEntityCode = 24  // BOUVET
	BRITISH_NORTH_BORNEO_DELETED             DXCCEntityCode = 25  // BRITISH NORTH BORNEO
	BRITISH_SOMALILAND_DELETED               DXCCEntityCode = 26  // BRITISH SOMALILAND
	BELARUS                                  DXCCEntityCode = 27  // BELARUS
	CANAL_ZONE_DELETED                       DXCCEntityCode = 28  // CANAL ZONE
	CANARY_IS                                DXCCEntityCode = 29  // CANARY IS.
	CELEBE_AND_MOLUCCA_IS_DELETED            DXCCEntityCode = 30  // CELEBE & MOLUCCA IS.
	C_KIRIBATI_BRITISH_PHOENIX_IS            DXCCEntityCode = 31  // C. KIRIBATI (BRITISH PHOENIX IS.)
	CEUTA_AND_MELILLA                        DXCCEntityCode = 32  // CEUTA & MELILLA
	CHAGOS_IS                                DXCCEntityCode = 33  // CHAGOS IS.
	CHATHAM_IS                               DXCCEntityCode = 34  // CHATHAM IS.
	CHRISTMAS_I                              DXCCEntityCode = 35  // CHRISTMAS I.
	CLIPPERTON_I                             DXCCEntityCode = 36  // CLIPPERTON I.
	COCOS_I                                  DXCCEntityCode = 37  // COCOS I.
	COCOS_KEELING_IS                         DXCCEntityCode = 38  // COCOS (KEELING) IS.
	COMOROS_DELETED                          DXCCEntityCode = 39  // COMOROS
	CRETE                                    DXCCEntityCode = 40  // CRETE
	CROZET_I                                 DXCCEntityCode = 41  // CROZET I.
	DAMAO_DIU_DELETED                        DXCCEntityCode = 42  // DAMAO, DIU
	DESECHEO_I                               DXCCEntityCode = 43  // DESECHEO I.
	DESROCHES_DELETED                        DXCCEntityCode = 44  // DESROCHES
	DODECANESE                               DXCCEntityCode = 45  // DODECANESE
	EAST_MALAYSIA                            DXCCEntityCode = 46  // EAST MALAYSIA
	EASTER_I                                 DXCCEntityCode = 47  // EASTER I.
	E_KIRIBATI_LINE_IS                       DXCCEntityCode = 48  // E. KIRIBATI (LINE IS.)
	EQUATORIAL_GUINEA                        DXCCEntityCode = 49  // EQUATORIAL GUINEA
	MEXICO                                   DXCCEntityCode = 50  // MEXICO
	ERITREA                                  DXCCEntityCode = 51  // ERITREA
	ESTONIA                                  DXCCEntityCode = 52  // ESTONIA
	ETHIOPIA                                 DXCCEntityCode = 53  // ETHIOPIA
	EUROPEAN_RUSSIA                          DXCCEntityCode = 54  // EUROPEAN RUSSIA
	FARQUHAR_DELETED                         DXCCEntityCode = 55  // FARQUHAR
	FERNANDO_DE_NORONHA                      DXCCEntityCode = 56  // FERNANDO DE NORONHA
	FRENCH_EQUATORIAL_AFRICA_DELETED         DXCCEntityCode = 57  // FRENCH EQUATORIAL AFRICA
	FRENCH_INDO_CHINA_DELETED                DXCCEntityCode = 58  // FRENCH INDO-CHINA
	FRENCH_WEST_AFRICA_DELETED               DXCCEntityCode = 59  // FRENCH WEST AFRICA
	BAHAMAS                                  DXCCEntityCode = 60  // BAHAMAS
	FRANZ_JOSEF_LAND                         DXCCEntityCode = 61  // FRANZ JOSEF LAND
	BARBADOS                                 DXCCEntityCode = 62  // BARBADOS
	FRENCH_GUIANA                            DXCCEntityCode = 63  // FRENCH GUIANA
	BERMUDA                                  DXCCEntityCode = 64  // BERMUDA
	BRITISH_VIRGIN_IS                        DXCCEntityCode = 65  // BRITISH VIRGIN IS.
	BELIZE                                   DXCCEntityCode = 66  // BELIZE
	FRENCH_INDIA_DELETED                     DXCCEntityCode = 67  // FRENCH INDIA
	KUWAIT_SAUDI_ARABIA_NEUTRAL_ZONE_DELETED DXCCEntityCode = 68  // KUWAIT/SAUDI ARABIA NEUTRAL ZONE
	CAYMAN_IS                                DXCCEntityCode = 69  // CAYMAN IS.
	CUBA                                     DXCCEntityCode = 70  // CUBA
	GALAPAGOS_IS                             DXCCEntityCode = 71  // GALAPAGOS IS.
	DOMINICAN_REPUBLIC                       DXCCEntityCode = 72  // DOMINICAN REPUBLIC
	EL_SALVADOR                              DXCCEntityCode = 74  // EL SALVADOR
	GEORGIA                                  DXCCEntityCode = 75  // GEORGIA
	GUATEMALA                                DXCCEntityCode = 76  // GUATEMALA
	GRENADA                                  DXCCEntityCode = 77  // GRENADA
	HAITI                                    DXCCEntityCode = 78  // HAITI
	GUADELOUPE                               DXCCEntityCode = 79  // GUADELOUPE
	HONDURAS                                 DXCCEntityCode = 80  // HONDURAS
	GERMANY_DELETED                          DXCCEntityCode = 81  // GERMANY
	JAMAICA                                  DXCCEntityCode = 82  // JAMAICA
	MARTINIQUE                               DXCCEntityCode = 84  // MARTINIQUE
	BONAIRE_CURACAO_DELETED                  DXCCEntityCode = 85  // BONAIRE, CURACAO
	NICARAGUA                                DXCCEntityCode = 86  // NICARAGUA
	PANAMA                                   DXCCEntityCode = 88  // PANAMA
	TURKS_AND_CAICOS_IS                      DXCCEntityCode = 89  // TURKS & CAICOS IS.
	TRINIDAD_AND_TOBAGO                      DXCCEntityCode = 90  // TRINIDAD & TOBAGO
	ARUBA                                    DXCCEntityCode = 91  // ARUBA
	GEYSER_REEF_DELETED                      DXCCEntityCode = 93  // GEYSER REEF
	ANTIGUA_AND_BARBUDA                      DXCCEntityCode = 94  // ANTIGUA & BARBUDA
	DOMINICA                                 DXCCEntityCode = 95  // DOMINICA
	MONTSERRAT                               DXCCEntityCode = 96  // MONTSERRAT
	ST_LUCIA                                 DXCCEntityCode = 97  // ST. LUCIA
	ST_VINCENT                               DXCCEntityCode = 98  // ST. VINCENT
	GLORIOSO_IS                              DXCCEntityCode = 99  // GLORIOSO IS.
	ARGENTINA                                DXCCEntityCode = 100 // ARGENTINA
	GOA_DELETED                              DXCCEntityCode = 101 // GOA
	GOLD_COAST_TOGOLAND_DELETED              DXCCEntityCode = 102 // GOLD COAST, TOGOLAND
	GUAM                                     DXCCEntityCode = 103 // GUAM
	BOLIVIA                                  DXCCEntityCode = 104 // BOLIVIA
	GUANTANAMO_BAY                           DXCCEntityCode = 105 // GUANTANAMO BAY
	GUERNSEY                                 DXCCEntityCode = 106 // GUERNSEY
	GUINEA                                   DXCCEntityCode = 107 // GUINEA
	BRAZIL                                   DXCCEntityCode = 108 // BRAZIL
	GUINEA_BISSAU                            DXCCEntityCode = 109 // GUINEA-BISSAU
	HAWAII                                   DXCCEntityCode = 110 // HAWAII
	HEARD_I                                  DXCCEntityCode = 111 // HEARD I.
	CHILE                                    DXCCEntityCode = 112 // CHILE
	IFNI_DELETED                             DXCCEntityCode = 113 // IFNI
	ISLE_OF_MAN                              DXCCEntityCode = 114 // ISLE OF MAN
	ITALIAN_SOMALILAND_DELETED               DXCCEntityCode = 115 // ITALIAN SOMALILAND
	COLOMBIA                                 DXCCEntityCode = 116 // COLOMBIA
	ITU_HQ                                   DXCCEntityCode = 117 // ITU HQ
	JAN_MAYEN                                DXCCEntityCode = 118 // JAN MAYEN
	JAVA_DELETED                             DXCCEntityCode = 119 // JAVA
	ECUADOR                                  DXCCEntityCode = 120 // ECUADOR
	JERSEY                                   DXCCEntityCode = 122 // JERSEY
	JOHNSTON_I                               DXCCEntityCode = 123 // JOHNSTON I.
	JUAN_DE_NOVA_EUROPA                      DXCCEntityCode = 124 // JUAN DE NOVA, EUROPA
	JUAN_FERNANDEZ_IS                        DXCCEntityCode = 125 // JUAN FERNANDEZ IS.
	KALININGRAD                              DXCCEntityCode = 126 // KALININGRAD
	KAMARAN_IS_DELETED                       DXCCEntityCode = 127 // KAMARAN IS.
	KARELO_FINNISH_REPUBLIC_DELETED          DXCCEntityCode = 128 // KARELO-FINNISH REPUBLIC
	GUYANA                                   DXCCEntityCode = 129 // GUYANA
	KAZAKHSTAN                               DXCCEntityCode = 130 // KAZAKHSTAN
	KERGUELEN_IS                             DXCCEntityCode = 131 // KERGUELEN IS.
	PARAGUAY                                 DXCCEntityCode = 132 // PARAGUAY
	KERMADEC_IS                              DXCCEntityCode = 133 // KERMADEC IS.
	KINGMAN_REEF_DELETED                     DXCCEntityCode = 134 // KINGMAN REEF
	KYRGYZSTAN                               DXCCEntityCode = 135 // KYRGYZSTAN
	PERU                                     DXCCEntityCode = 136 // PERU
	REPUBLIC_OF_KOREA                        DXCCEntityCode = 137 // REPUBLIC OF KOREA
	KURE_I                                   DXCCEntityCode = 138 // KURE I.
	KURIA_MURIA_I_DELETED                    DXCCEntityCode = 139 // KURIA MURIA I.
	SURINAME                                 DXCCEntityCode = 140 // SURINAME
	FALKLAND_IS                              DXCCEntityCode = 141 // FALKLAND IS.
	LAKSHADWEEP_IS                           DXCCEntityCode = 142 // LAKSHADWEEP IS.
	LAOS                                     DXCCEntityCode = 143 // LAOS
	URUGUAY                                  DXCCEntityCode = 144 // URUGUAY
	LATVIA                                   DXCCEntityCode = 145 // LATVIA
	LITHUANIA                                DXCCEntityCode = 146 // LITHUANIA
	LORD_HOWE_I                              DXCCEntityCode = 147 // LORD HOWE I.
	VENEZUELA                                DXCCEntityCode = 148 // VENEZUELA
	AZORES                                   DXCCEntityCode = 149 // AZORES
	AUSTRALIA                                DXCCEntityCode = 150 // AUSTRALIA
	MALYJ_VYSOTSKIJ_I_DELETED                DXCCEntityCode = 151 // MALYJ VYSOTSKIJ I.
	MACAO                                    DXCCEntityCode = 152 // MACAO
	MACQUARIE_I                              DXCCEntityCode = 153 // MACQUARIE I.
	YEMEN_ARAB_REPUBLIC_DELETED              DXCCEntityCode = 154 // YEMEN ARAB REPUBLIC
	MALAYA_DELETED                           DXCCEntityCode = 155 // MALAYA
	NAURU                                    DXCCEntityCode = 157 // NAURU
	VANUATU                                  DXCCEntityCode = 158 // VANUATU
	MALDIVES                                 DXCCEntityCode = 159 // MALDIVES
	TONGA                                    DXCCEntityCode = 160 // TONGA
	MALPELO_I                                DXCCEntityCode = 161 // MALPELO I.
	NEW_CALEDONIA                            DXCCEntityCode = 162 // NEW CALEDONIA
	PAPUA_NEW_GUINEA                         DXCCEntityCode = 163 // PAPUA NEW GUINEA
	MANCHURIA_DELETED                        DXCCEntityCode = 164 // MANCHURIA
	MAURITIUS                                DXCCEntityCode = 165 // MAURITIUS
	MARIANA_IS                               DXCCEntityCode = 166 // MARIANA IS.
	MARKET_REEF                              DXCCEntityCode = 167 // MARKET REEF
	MARSHALL_IS                              DXCCEntityCode = 168 // MARSHALL IS.
	MAYOTTE                                  DXCCEntityCode = 169 // MAYOTTE
	NEW_ZEALAND                              DXCCEntityCode = 170 // NEW ZEALAND
	MELLISH_REEF                             DXCCEntityCode = 171 // MELLISH REEF
	PITCAIRN_I                               DXCCEntityCode = 172 // PITCAIRN I.
	MICRONESIA                               DXCCEntityCode = 173 // MICRONESIA
	MIDWAY_I                                 DXCCEntityCode = 174 // MIDWAY I.
	FRENCH_POLYNESIA                         DXCCEntityCode = 175 // FRENCH POLYNESIA
	FIJI                                     DXCCEntityCode = 176 // FIJI
	MINAMI_TORISHIMA                         DXCCEntityCode = 177 // MINAMI TORISHIMA
	MINERVA_REEF_DELETED                     DXCCEntityCode = 178 // MINERVA REEF
	MOLDOVA                                  DXCCEntityCode = 179 // MOLDOVA
	MOUNT_ATHOS                              DXCCEntityCode = 180 // MOUNT ATHOS
	MOZAMBIQUE                               DXCCEntityCode = 181 // MOZAMBIQUE
	NAVASSA_I                                DXCCEntityCode = 182 // NAVASSA I.
	NETHERLANDS_BORNEO_DELETED               DXCCEntityCode = 183 // NETHERLANDS BORNEO
	NETHERLANDS_NEW_GUINEA_DELETED           DXCCEntityCode = 184 // NETHERLANDS NEW GUINEA
	SOLOMON_IS                               DXCCEntityCode = 185 // SOLOMON IS.
	NEWFOUNDLAND_LABRADOR_DELETED            DXCCEntityCode = 186 // NEWFOUNDLAND, LABRADOR
	NIGER                                    DXCCEntityCode = 187 // NIGER
	NIUE                                     DXCCEntityCode = 188 // NIUE
	NORFOLK_I                                DXCCEntityCode = 189 // NORFOLK I.
	SAMOA                                    DXCCEntityCode = 190 // SAMOA
	NORTH_COOK_IS                            DXCCEntityCode = 191 // NORTH COOK IS.
	OGASAWARA                                DXCCEntityCode = 192 // OGASAWARA
	OKINAWA_RYUKYU_IS_DELETED                DXCCEntityCode = 193 // OKINAWA (RYUKYU IS.)
	OKINO_TORI_SHIMA_DELETED                 DXCCEntityCode = 194 // OKINO TORI-SHIMA
	ANNOBON_I                                DXCCEntityCode = 195 // ANNOBON I.
	PALESTINE_DELETED                        DXCCEntityCode = 196 // PALESTINE
	PALMYRA_AND_JARVIS_IS                    DXCCEntityCode = 197 // PALMYRA & JARVIS IS.
	PAPUA_TERRITORY_DELETED                  DXCCEntityCode = 198 // PAPUA TERRITORY
	PETER_1_I                                DXCCEntityCode = 199 // PETER 1 I.
	PORTUGUESE_TIMOR_DELETED                 DXCCEntityCode = 200 // PORTUGUESE TIMOR
	PRINCE_EDWARD_AND_MARION_IS              DXCCEntityCode = 201 // PRINCE EDWARD & MARION IS.
	PUERTO_RICO                              DXCCEntityCode = 202 // PUERTO RICO
	ANDORRA                                  DXCCEntityCode = 203 // ANDORRA
	REVILLAGIGEDO                            DXCCEntityCode = 204 // REVILLAGIGEDO
	ASCENSION_I                              DXCCEntityCode = 205 // ASCENSION I.
	AUSTRIA                                  DXCCEntityCode = 206 // AUSTRIA
	RODRIGUES_I                              DXCCEntityCode = 207 // RODRIGUES I.
	RUANDA_URUNDI_DELETED                    DXCCEntityCode = 208 // RUANDA-URUNDI
	BELGIUM                                  DXCCEntityCode = 209 // BELGIUM
	SAAR_DELETED                             DXCCEntityCode = 210 // SAAR
	SABLE_I                                  DXCCEntityCode = 211 // SABLE I.
	BULGARIA                                 DXCCEntityCode = 212 // BULGARIA
	SAINT_MARTIN                             DXCCEntityCode = 213 // SAINT MARTIN
	CORSICA                                  DXCCEntityCode = 214 // CORSICA
	CYPRUS                                   DXCCEntityCode = 215 // CYPRUS
	SAN_ANDRES_AND_PROVIDENCIA               DXCCEntityCode = 216 // SAN ANDRES & PROVIDENCIA
	SAN_FELIX_AND_SAN_AMBROSIO               DXCCEntityCode = 217 // SAN FELIX & SAN AMBROSIO
	CZECHOSLOVAKIA_DELETED                   DXCCEntityCode = 218 // CZECHOSLOVAKIA
	SAO_TOME_AND_PRINCIPE                    DXCCEntityCode = 219 // SAO TOME & PRINCIPE
	SARAWAK_DELETED                          DXCCEntityCode = 220 // SARAWAK
	DENMARK                                  DXCCEntityCode = 221 // DENMARK
	FAROE_IS                                 DXCCEntityCode = 222 // FAROE IS.
	ENGLAND                                  DXCCEntityCode = 223 // ENGLAND
	FINLAND                                  DXCCEntityCode = 224 // FINLAND
	SARDINIA                                 DXCCEntityCode = 225 // SARDINIA
	SAUDI_ARABIA_IRAQ_NEUTRAL_ZONE_DELETED   DXCCEntityCode = 226 // SAUDI ARABIA/IRAQ NEUTRAL ZONE
	FRANCE                                   DXCCEntityCode = 227 // FRANCE
	SERRANA_BANK_AND_RONCADOR_CAY_DELETED    DXCCEntityCode = 228 // SERRANA BANK & RONCADOR CAY
	GERMAN_DEMOCRATIC_REPUBLIC_DELETED       DXCCEntityCode = 229 // GERMAN DEMOCRATIC REPUBLIC
	FEDERAL_REPUBLIC_OF_GERMANY              DXCCEntityCode = 230 // FEDERAL REPUBLIC OF GERMANY
	SIKKIM_DELETED                           DXCCEntityCode = 231 // SIKKIM
	SOMALIA                                  DXCCEntityCode = 232 // SOMALIA
	GIBRALTAR                                DXCCEntityCode = 233 // GIBRALTAR
	SOUTH_COOK_IS                            DXCCEntityCode = 234 // SOUTH COOK IS.
	SOUTH_GEORGIA_I                          DXCCEntityCode = 235 // SOUTH GEORGIA I.
	GREECE                                   DXCCEntityCode = 236 // GREECE
	GREENLAND                                DXCCEntityCode = 237 // GREENLAND
	SOUTH_ORKNEY_IS                          DXCCEntityCode = 238 // SOUTH ORKNEY IS.
	HUNGARY                                  DXCCEntityCode = 239 // HUNGARY
	SOUTH_SANDWICH_IS                        DXCCEntityCode = 240 // SOUTH SANDWICH IS.
	SOUTH_SHETLAND_IS                        DXCCEntityCode = 241 // SOUTH SHETLAND IS.
	ICELAND                                  DXCCEntityCode = 242 // ICELAND
	PEOPLES_DEMOCRATIC_REP_OF_YEMEN_DELETED  DXCCEntityCode = 243 // PEOPLE'S DEMOCRATIC REP. OF YEMEN
	SOUTHERN_SUDAN_DELETED                   DXCCEntityCode = 244 // SOUTHERN SUDAN
	IRELAND                                  DXCCEntityCode = 245 // IRELAND
	SOVEREIGN_MILITARY_ORDER_OF_MALTA        DXCCEntityCode = 246 // SOVEREIGN MILITARY ORDER OF MALTA
	SPRATLY_IS                               DXCCEntityCode = 247 // SPRATLY IS.
	ITALY                                    DXCCEntityCode = 248 // ITALY
	ST_KITTS_AND_NEVIS                       DXCCEntityCode = 249 // ST. KITTS & NEVIS
	ST_HELENA                                DXCCEntityCode = 250 // ST. HELENA
	LIECHTENSTEIN                            DXCCEntityCode = 251 // LIECHTENSTEIN
	ST_PAUL_I                                DXCCEntityCode = 252 // ST. PAUL I.
	ST_PETER_AND_ST_PAUL_ROCKS               DXCCEntityCode = 253 // ST. PETER & ST. PAUL ROCKS
	LUXEMBOURG                               DXCCEntityCode = 254 // LUXEMBOURG
	ST_MAARTEN_SABA_ST_EUSTATIUS_DELETED     DXCCEntityCode = 255 // ST. MAARTEN, SABA, ST. EUSTATIUS
	MADEIRA_IS                               DXCCEntityCode = 256 // MADEIRA IS.
	MALTA                                    DXCCEntityCode = 257 // MALTA
	SUMATRA_DELETED                          DXCCEntityCode = 258 // SUMATRA
	SVALBARD                                 DXCCEntityCode = 259 // SVALBARD
	MONACO                                   DXCCEntityCode = 260 // MONACO
	SWAN_IS_DELETED                          DXCCEntityCode = 261 // SWAN IS.
	TAJIKISTAN                               DXCCEntityCode = 262 // TAJIKISTAN
	NETHERLANDS                              DXCCEntityCode = 263 // NETHERLANDS
	TANGIER_DELETED                          DXCCEntityCode = 264 // TANGIER
	NORTHERN_IRELAND                         DXCCEntityCode = 265 // NORTHERN IRELAND
	NORWAY                                   DXCCEntityCode = 266 // NORWAY
	TERRITORY_OF_NEW_GUINEA_DELETED          DXCCEntityCode = 267 // TERRITORY OF NEW GUINEA
	TIBET_DELETED                            DXCCEntityCode = 268 // TIBET
	POLAND                                   DXCCEntityCode = 269 // POLAND
	TOKELAU_IS                               DXCCEntityCode = 270 // TOKELAU IS.
	TRIESTE_DELETED                          DXCCEntityCode = 271 // TRIESTE
	PORTUGAL                                 DXCCEntityCode = 272 // PORTUGAL
	TRINDADE_AND_MARTIM_VAZ_IS               DXCCEntityCode = 273 // TRINDADE & MARTIM VAZ IS.
	TRISTAN_DA_CUNHA_AND_GOUGH_I             DXCCEntityCode = 274 // TRISTAN DA CUNHA & GOUGH I.
	ROMANIA                                  DXCCEntityCode = 275 // ROMANIA
	TROMELIN_I                               DXCCEntityCode = 276 // TROMELIN I.
	ST_PIERRE_AND_MIQUELON                   DXCCEntityCode = 277 // ST. PIERRE & MIQUELON
	SAN_MARINO                               DXCCEntityCode = 278 // SAN MARINO
	SCOTLAND                                 DXCCEntityCode = 279 // SCOTLAND
	TURKMENISTAN                             DXCCEntityCode = 280 // TURKMENISTAN
	SPAIN                                    DXCCEntityCode = 281 // SPAIN
	TUVALU                                   DXCCEntityCode = 282 // TUVALU
	UK_SOVEREIGN_BASE_AREAS_ON_CYPRUS        DXCCEntityCode = 283 // UK SOVEREIGN BASE AREAS ON CYPRUS
	SWEDEN                                   DXCCEntityCode = 284 // SWEDEN
	VIRGIN_IS                                DXCCEntityCode = 285 // VIRGIN IS.
	UGANDA                                   DXCCEntityCode = 286 // UGANDA
	SWITZERLAND                              DXCCEntityCode = 287 // SWITZERLAND
	UKRAINE                                  DXCCEntityCode = 288 // UKRAINE
	UNITED_NATIONS_HQ                        DXCCEntityCode = 289 // UNITED NATIONS HQ
	UNITED_STATES_OF_AMERICA                 DXCCEntityCode = 291 // UNITED STATES OF AMERICA
	UZBEKISTAN                               DXCCEntityCode = 292 // UZBEKISTAN
	VIET_NAM                                 DXCCEntityCode = 293 // VIET NAM
	WALES                                    DXCCEntityCode = 294 // WALES
	VATICAN                                  DXCCEntityCode = 295 // VATICAN
	SERBIA                                   DXCCEntityCode = 296 // SERBIA
	WAKE_I                                   DXCCEntityCode = 297 // WAKE I.
	WALLIS_AND_FUTUNA_IS                     DXCCEntityCode = 298 // WALLIS & FUTUNA IS.
	WEST_MALAYSIA                            DXCCEntityCode = 299 // WEST MALAYSIA
	W_KIRIBATI_GILBERT_IS                    DXCCEntityCode = 301 // W. KIRIBATI (GILBERT IS. )
	WESTERN_SAHARA                           DXCCEntityCode = 302 // WESTERN SAHARA
	WILLIS_I                                 DXCCEntityCode = 303 // WILLIS I.
	BAHRAIN                                  DXCCEntityCode = 304 // BAHRAIN
	BANGLADESH                               DXCCEntityCode = 305 // BANGLADESH
	BHUTAN                                   DXCCEntityCode = 306 // BHUTAN
	ZANZIBAR_DELETED                         DXCCEntityCode = 307 // ZANZIBAR
	COSTA_RICA                               DXCCEntityCode = 308 // COSTA RICA
	MYANMAR                                  DXCCEntityCode = 309 // MYANMAR
	CAMBODIA                                 DXCCEntityCode = 312 // CAMBODIA
	SRI_LANKA                                DXCCEntityCode = 315 // SRI LANKA
	CHINA                                    DXCCEntityCode = 318 // CHINA
	HONG_KONG                                DXCCEntityCode = 321 // HONG KONG
	INDIA                                    DXCCEntityCode = 324 // INDIA
	INDONESIA                                DXCCEntityCode = 327 // INDONESIA
	IRAN                                     DXCCEntityCode = 330 // IRAN
	IRAQ                                     DXCCEntityCode = 333 // IRAQ
	ISRAEL                                   DXCCEntityCode = 336 // ISRAEL
	JAPAN                                    DXCCEntityCode = 339 // JAPAN
	JORDAN                                   DXCCEntityCode = 342 // JORDAN
	DEMOCRATIC_PEOPLES_REP_OF_KOREA          DXCCEntityCode = 344 // DEMOCRATIC PEOPLE'S REP. OF KOREA
	BRUNEI_DARUSSALAM                        DXCCEntityCode = 345 // BRUNEI DARUSSALAM
	KUWAIT                                   DXCCEntityCode = 348 // KUWAIT
	LEBANON                                  DXCCEntityCode = 354 // LEBANON
	MONGOLIA                                 DXCCEntityCode = 363 // MONGOLIA
	NEPAL                                    DXCCEntityCode = 369 // NEPAL
	OMAN                                     DXCCEntityCode = 370 // OMAN
	PAKISTAN                                 DXCCEntityCode = 372 // PAKISTAN
	PHILIPPINES                              DXCCEntityCode = 375 // PHILIPPINES
	QATAR                                    DXCCEntityCode = 376 // QATAR
	SAUDI_ARABIA                             DXCCEntityCode = 378 // SAUDI ARABIA
	SEYCHELLES                               DXCCEntityCode = 379 // SEYCHELLES
	SINGAPORE                                DXCCEntityCode = 381 // SINGAPORE
	DJIBOUTI                                 DXCCEntityCode = 382 // DJIBOUTI
	SYRIA                                    DXCCEntityCode = 384 // SYRIA
	TAIWAN                                   DXCCEntityCode = 386 // TAIWAN
	THAILAND                                 DXCCEntityCode = 387 // THAILAND
	TURKEY                                   DXCCEntityCode = 390 // TURKEY
	UNITED_ARAB_EMIRATES                     DXCCEntityCode = 391 // UNITED ARAB EMIRATES
	ALGERIA                                  DXCCEntityCode = 400 // ALGERIA
	ANGOLA                                   DXCCEntityCode = 401 // ANGOLA
	BOTSWANA                                 DXCCEntityCode = 402 // BOTSWANA
	BURUNDI                                  DXCCEntityCode = 404 // BURUNDI
	CAMEROON                                 DXCCEntityCode = 406 // CAMEROON
	CENTRAL_AFRICA                           DXCCEntityCode = 408 // CENTRAL AFRICA
	CAPE_VERDE                               DXCCEntityCode = 409 // CAPE VERDE
	CHAD                                     DXCCEntityCode = 410 // CHAD
	COMOROS                                  DXCCEntityCode = 411 // COMOROS
	REPUBLIC_OF_THE_CONGO                    DXCCEntityCode = 412 // REPUBLIC OF THE CONGO
	DEMOCRATIC_REPUBLIC_OF_THE_CONGO         DXCCEntityCode = 414 // DEMOCRATIC REPUBLIC OF THE CONGO
	BENIN                                    DXCCEntityCode = 416 // BENIN
	GABON                                    DXCCEntityCode = 420 // GABON
	THE_GAMBIA                               DXCCEntityCode = 422 // THE GAMBIA
	GHANA                                    DXCCEntityCode = 424 // GHANA
	COTE_DIVOIRE                             DXCCEntityCode = 428 // COTE D'IVOIRE
	KENYA                                    DXCCEntityCode = 430 // KENYA
	LESOTHO                                  DXCCEntityCode = 432 // LESOTHO
	LIBERIA                                  DXCCEntityCode = 434 // LIBERIA
	LIBYA                                    DXCCEntityCode = 436 // LIBYA
	MADAGASCAR                               DXCCEntityCode = 438 // MADAGASCAR
	MALAWI                                   DXCCEntityCode = 440 // MALAWI
	MALI                                     DXCCEntityCode = 442 // MALI
	MAURITANIA                               DXCCEntityCode = 444 // MAURITANIA
	MOROCCO                                  DXCCEntityCode = 446 // MOROCCO
	NIGERIA                                  DXCCEntityCode = 450 // NIGERIA
	ZIMBABWE                                 DXCCEntityCode = 452 // ZIMBABWE
	REUNION_I                                DXCCEntityCode = 453 // REUNION I.
	RWANDA                                   DXCCEntityCode = 454 // RWANDA
	SENEGAL                                  DXCCEntityCode = 456 // SENEGAL
	SIERRA_LEONE                             DXCCEntityCode = 458 // SIERRA LEONE
	ROTUMA_I                                 DXCCEntityCode = 460 // ROTUMA I.
	REPUBLIC_OF_SOUTH_AFRICA                 DXCCEntityCode = 462 // REPUBLIC OF SOUTH AFRICA
	NAMIBIA                                  DXCCEntityCode = 464 // NAMIBIA
	SUDAN                                    DXCCEntityCode = 466 // SUDAN
	KINGDOM_OF_ESWATINI                      DXCCEntityCode = 468 // KINGDOM OF ESWATINI
	TANZANIA                                 DXCCEntityCode = 470 // TANZANIA
	TUNISIA                                  DXCCEntityCode = 474 // TUNISIA
	EGYPT                                    DXCCEntityCode = 478 // EGYPT
	BURKINA_FASO                             DXCCEntityCode = 480 // BURKINA FASO
	ZAMBIA                                   DXCCEntityCode = 482 // ZAMBIA
	TOGO                                     DXCCEntityCode = 483 // TOGO
	WALVIS_BAY_DELETED                       DXCCEntityCode = 488 // WALVIS BAY
	CONWAY_REEF                              DXCCEntityCode = 489 // CONWAY REEF
	BANABA_I_OCEAN_I                         DXCCEntityCode = 490 // BANABA I. (OCEAN I.)
	YEMEN                                    DXCCEntityCode = 492 // YEMEN
	PENGUIN_IS_DELETED                       DXCCEntityCode = 493 // PENGUIN IS.
	CROATIA                                  DXCCEntityCode = 497 // CROATIA
	SLOVENIA                                 DXCCEntityCode = 499 // SLOVENIA
	BOSNIA_HERZEGOVINA                       DXCCEntityCode = 501 // BOSNIA-HERZEGOVINA
	NORTH_MACEDONIA_REPUBLIC_OF              DXCCEntityCode = 502 // NORTH MACEDONIA (REPUBLIC OF)
	CZECH_REPUBLIC                           DXCCEntityCode = 503 // CZECH REPUBLIC
	SLOVAK_REPUBLIC                          DXCCEntityCode = 504 // SLOVAK REPUBLIC
	PRATAS_I                                 DXCCEntityCode = 505 // PRATAS I.
	SCARBOROUGH_REEF                         DXCCEntityCode = 506 // SCARBOROUGH REEF
	TEMOTU_PROVINCE                          DXCCEntityCode = 507 // TEMOTU PROVINCE
	AUSTRAL_I                                DXCCEntityCode = 508 // AUSTRAL I.
	MARQUESAS_IS                             DXCCEntityCode = 509 // MARQUESAS IS.
	PALESTINE                                DXCCEntityCode = 510 // PALESTINE
	TIMOR_LESTE                              DXCCEntityCode = 511 // TIMOR-LESTE
	CHESTERFIELD_IS                          DXCCEntityCode = 512 // CHESTERFIELD IS.
	DUCIE_I                                  DXCCEntityCode = 513 // DUCIE I.
	MONTENEGRO                               DXCCEntityCode = 514 // MONTENEGRO
	SWAINS_I                                 DXCCEntityCode = 515 // SWAINS I.
	SAINT_BARTHELEMY                         DXCCEntityCode = 516 // SAINT BARTHELEMY
	CURACAO                                  DXCCEntityCode = 517 // CURACAO
	SINT_MAARTEN                             DXCCEntityCode = 518 // SINT MAARTEN
	SABA_AND_ST_EUSTATIUS                    DXCCEntityCode = 519 // SABA & ST. EUSTATIUS
	BONAIRE                                  DXCCEntityCode = 520 // BONAIRE
	SOUTH_SUDAN_REPUBLIC_OF                  DXCCEntityCode = 521 // SOUTH SUDAN (REPUBLIC OF)
	REPUBLIC_OF_KOSOVO                       DXCCEntityCode = 522 // REPUBLIC OF KOSOVO
)
