// DO NOT EDIT
// Code generated by ./cmd/codegen/codegen

// This file contains CURRENTLY valid constants.
// It is not a full list of all possible historic and/or future values.

package arrlsection

var (
	AL  ARRLSection = "AL"  // AL    = Alabama
	AK  ARRLSection = "AK"  // AK    = Alaska
	AB  ARRLSection = "AB"  // AB    = Alberta
	AR  ARRLSection = "AR"  // AR    = Arkansas
	AZ  ARRLSection = "AZ"  // AZ    = Arizona
	BC  ARRLSection = "BC"  // BC    = British Columbia
	CO  ARRLSection = "CO"  // CO    = Colorado
	CT  ARRLSection = "CT"  // CT    = Connecticut
	DE  ARRLSection = "DE"  // DE    = Delaware
	EB  ARRLSection = "EB"  // EB    = East Bay
	EMA ARRLSection = "EMA" // EMA   = Eastern Massachusetts
	ENY ARRLSection = "ENY" // ENY   = Eastern New York
	EPA ARRLSection = "EPA" // EPA   = Eastern Pennsylvania
	EWA ARRLSection = "EWA" // EWA   = Eastern Washington
	GA  ARRLSection = "GA"  // GA    = Georgia
	GH  ARRLSection = "GH"  // GH    = Golden Horseshoe
	ID  ARRLSection = "ID"  // ID    = Idaho
	IL  ARRLSection = "IL"  // IL    = Illinois
	IN  ARRLSection = "IN"  // IN    = Indiana
	IA  ARRLSection = "IA"  // IA    = Iowa
	KS  ARRLSection = "KS"  // KS    = Kansas
	KY  ARRLSection = "KY"  // KY    = Kentucky
	LAX ARRLSection = "LAX" // LAX   = Los Angeles
	LA  ARRLSection = "LA"  // LA    = Louisiana
	ME  ARRLSection = "ME"  // ME    = Maine
	MB  ARRLSection = "MB"  // MB    = Manitoba
	MDC ARRLSection = "MDC" // MDC   = Maryland-DC
	MI  ARRLSection = "MI"  // MI    = Michigan
	MN  ARRLSection = "MN"  // MN    = Minnesota
	MS  ARRLSection = "MS"  // MS    = Mississippi
	MO  ARRLSection = "MO"  // MO    = Missouri
	MT  ARRLSection = "MT"  // MT    = Montana
	NE  ARRLSection = "NE"  // NE    = Nebraska
	NV  ARRLSection = "NV"  // NV    = Nevada
	NB  ARRLSection = "NB"  // NB    = New Brunswick
	NH  ARRLSection = "NH"  // NH    = New Hampshire
	NM  ARRLSection = "NM"  // NM    = New Mexico
	NLI ARRLSection = "NLI" // NLI   = New York City-Long Island
	NL  ARRLSection = "NL"  // NL    = Newfoundland/Labrador
	NC  ARRLSection = "NC"  // NC    = North Carolina
	ND  ARRLSection = "ND"  // ND    = North Dakota
	NTX ARRLSection = "NTX" // NTX   = North Texas
	NFL ARRLSection = "NFL" // NFL   = Northern Florida
	NNJ ARRLSection = "NNJ" // NNJ   = Northern New Jersey
	NNY ARRLSection = "NNY" // NNY   = Northern New York
	NS  ARRLSection = "NS"  // NS    = Nova Scotia
	OH  ARRLSection = "OH"  // OH    = Ohio
	OK  ARRLSection = "OK"  // OK    = Oklahoma
	ONE ARRLSection = "ONE" // ONE   = Ontario East
	ONN ARRLSection = "ONN" // ONN   = Ontario North
	ONS ARRLSection = "ONS" // ONS   = Ontario South
	ORG ARRLSection = "ORG" // ORG   = Orange
	OR  ARRLSection = "OR"  // OR    = Oregon
	PAC ARRLSection = "PAC" // PAC   = Pacific
	PE  ARRLSection = "PE"  // PE    = Prince Edward Island
	PR  ARRLSection = "PR"  // PR    = Puerto Rico
	QC  ARRLSection = "QC"  // QC    = Quebec
	RI  ARRLSection = "RI"  // RI    = Rhode Island
	SV  ARRLSection = "SV"  // SV    = Sacramento Valley
	SDG ARRLSection = "SDG" // SDG   = San Diego
	SF  ARRLSection = "SF"  // SF    = San Francisco
	SJV ARRLSection = "SJV" // SJV   = San Joaquin Valley
	SB  ARRLSection = "SB"  // SB    = Santa Barbara
	SCV ARRLSection = "SCV" // SCV   = Santa Clara Valley
	SK  ARRLSection = "SK"  // SK    = Saskatchewan
	SC  ARRLSection = "SC"  // SC    = South Carolina
	SD  ARRLSection = "SD"  // SD    = South Dakota
	STX ARRLSection = "STX" // STX   = South Texas
	SFL ARRLSection = "SFL" // SFL   = Southern Florida
	SNJ ARRLSection = "SNJ" // SNJ   = Southern New Jersey
	TN  ARRLSection = "TN"  // TN    = Tennessee
	TER ARRLSection = "TER" // TER   = Territories
	VI  ARRLSection = "VI"  // VI    = US Virgin Islands
	UT  ARRLSection = "UT"  // UT    = Utah
	VT  ARRLSection = "VT"  // VT    = Vermont
	VA  ARRLSection = "VA"  // VA    = Virginia
	WCF ARRLSection = "WCF" // WCF   = West Central Florida
	WTX ARRLSection = "WTX" // WTX   = West Texas
	WV  ARRLSection = "WV"  // WV    = West Virginia
	WMA ARRLSection = "WMA" // WMA   = Western Massachusetts
	WNY ARRLSection = "WNY" // WNY   = Western New York
	WPA ARRLSection = "WPA" // WPA   = Western Pennsylvania
	WWA ARRLSection = "WWA" // WWA   = Western Washington
	WI  ARRLSection = "WI"  // WI    = Wisconsin
	WY  ARRLSection = "WY"  // WY    = Wyoming
)
