// DO NOT EDIT
// Code generated by ./cmd/codegen/codegen

// This file contains CURRENTLY valid constants.
// It is not a full list of all possible historic and/or future values.

package qslrcvd

var (
	Y QSLRcvd = "Y" // Y = yes (confirmed)
	N QSLRcvd = "N" // N = no
	R QSLRcvd = "R" // R = requested
	I QSLRcvd = "I" // I = ignore or invalid
)
