// DO NOT EDIT
// Code generated by ./cmd/codegen/codegen

// This file contains CURRENTLY valid constants.
// It is not a full list of all possible historic and/or future values.

package continent

var (
	NA Continent = "NA" // NA = North America
	SA Continent = "SA" // SA = South America
	EU Continent = "EU" // EU = Europe
	AF Continent = "AF" // AF = Africa
	OC Continent = "OC" // OC = Oceania
	AS Continent = "AS" // AS = Asia
	AN Continent = "AN" // AN = Antarctica
)
