// DO NOT EDIT
// Code generated by ./cmd/codegen/codegen

// This file contains CURRENTLY valid constants.
// It is not a full list of all possible historic and/or future values.

package awardsponsor

var (
	ADIF  AwardSponsorPrefix = "ADIF_"  // ADIF_   = ADIF Development Group
	ARI   AwardSponsorPrefix = "ARI_"   // ARI_    = ARI - l'Associazione Radioamatori Italiani
	ARRL  AwardSponsorPrefix = "ARRL_"  // ARRL_   = ARRL - American Radio Relay League
	CQ    AwardSponsorPrefix = "CQ_"    // CQ_     = CQ Magazine
	DARC  AwardSponsorPrefix = "DARC_"  // DARC_   = DARC - Deutscher Amateur-Radio-Club e.V.
	EQSL  AwardSponsorPrefix = "EQSL_"  // EQSL_   = eQSL
	IARU  AwardSponsorPrefix = "IARU_"  // IARU_   = IARU - International Amateur Radio Union
	JARL  AwardSponsorPrefix = "JARL_"  // JARL_   = JARL - Japan Amateur Radio League
	RSGB  AwardSponsorPrefix = "RSGB_"  // RSGB_   = RSGB - Radio Society of Great Britain
	TAG   AwardSponsorPrefix = "TAG_"   // TAG_    = TAG - Tambov award group
	WABAG AwardSponsorPrefix = "WABAG_" // WABAG_  = WAB - Worked all Britain
)
