// DO NOT EDIT
// Code generated by ./cmd/codegen/codegen

// This file contains CURRENTLY valid constants.
// It is not a full list of all possible historic and/or future values.

package contest

var (
	Contest_070_160M_SPRINT       Contest = "070-160M-SPRINT"       // 070-160M-SPRINT          = PODXS Great Pumpkin Sprint
	Contest_070_3_DAY             Contest = "070-3-DAY"             // 070-3-DAY                = PODXS Three Day Weekend
	Contest_070_31_FLAVORS        Contest = "070-31-FLAVORS"        // 070-31-FLAVORS           = PODXS 31 Flavors
	Contest_070_40M_SPRINT        Contest = "070-40M-SPRINT"        // 070-40M-SPRINT           = PODXS 40m Firecracker Sprint
	Contest_070_80M_SPRINT        Contest = "070-80M-SPRINT"        // 070-80M-SPRINT           = PODXS 80m Jay Hudak Memorial Sprint
	Contest_070_PSKFEST           Contest = "070-PSKFEST"           // 070-PSKFEST              = PODXS PSKFest
	Contest_070_ST_PATS_DAY       Contest = "070-ST-PATS-DAY"       // 070-ST-PATS-DAY          = PODXS St. Patricks Day
	Contest_070_VALENTINE_SPRINT  Contest = "070-VALENTINE-SPRINT"  // 070-VALENTINE-SPRINT     = PODXS Valentine Sprint
	Contest_10_RTTY               Contest = "10-RTTY"               // 10-RTTY                  = Ten-Meter RTTY Contest (2011 onwards)
	Contest_1010_OPEN_SEASON      Contest = "1010-OPEN-SEASON"      // 1010-OPEN-SEASON         = Open Season Ten Meter QSO Party
	Contest_7QP                   Contest = "7QP"                   // 7QP                      = 7th-Area QSO Party
	Contest_AL_QSO_PARTY          Contest = "AL-QSO-PARTY"          // AL-QSO-PARTY             = Alabama QSO Party
	Contest_ALL_ASIAN_DX_CW       Contest = "ALL-ASIAN-DX-CW"       // ALL-ASIAN-DX-CW          = JARL All Asian DX Contest (CW)
	Contest_ALL_ASIAN_DX_PHONE    Contest = "ALL-ASIAN-DX-PHONE"    // ALL-ASIAN-DX-PHONE       = JARL All Asian DX Contest (PHONE)
	Contest_ANARTS_RTTY           Contest = "ANARTS-RTTY"           // ANARTS-RTTY              = ANARTS WW RTTY
	Contest_ANATOLIAN_RTTY        Contest = "ANATOLIAN-RTTY"        // ANATOLIAN-RTTY           = Anatolian WW RTTY
	Contest_AP_SPRINT             Contest = "AP-SPRINT"             // AP-SPRINT                = Asia - Pacific Sprint
	Contest_AR_QSO_PARTY          Contest = "AR-QSO-PARTY"          // AR-QSO-PARTY             = Arkansas QSO Party
	Contest_ARI_DX                Contest = "ARI-DX"                // ARI-DX                   = ARI DX Contest
	Contest_ARI_EME               Contest = "ARI-EME"               // ARI-EME                  = ARI Italian EME Trophy
	Contest_ARI_IAC_13CM          Contest = "ARI-IAC-13CM"          // ARI-IAC-13CM             = ARI Italian Activity Contest (13cm+)
	Contest_ARI_IAC_23CM          Contest = "ARI-IAC-23CM"          // ARI-IAC-23CM             = ARI Italian Activity Contest (23cm)
	Contest_ARI_IAC_6M            Contest = "ARI-IAC-6M"            // ARI-IAC-6M               = ARI Italian Activity Contest (6m)
	Contest_ARI_IAC_UHF           Contest = "ARI-IAC-UHF"           // ARI-IAC-UHF              = ARI Italian Activity Contest (UHF)
	Contest_ARI_IAC_VHF           Contest = "ARI-IAC-VHF"           // ARI-IAC-VHF              = ARI Italian Activity Contest (VHF)
	Contest_ARRL_10               Contest = "ARRL-10"               // ARRL-10                  = ARRL 10 Meter Contest
	Contest_ARRL_10_GHZ           Contest = "ARRL-10-GHZ"           // ARRL-10-GHZ              = ARRL 10 GHz and Up Contest
	Contest_ARRL_160              Contest = "ARRL-160"              // ARRL-160                 = ARRL 160 Meter Contest
	Contest_ARRL_222              Contest = "ARRL-222"              // ARRL-222                 = ARRL 222 MHz and Up Distance Contest
	Contest_ARRL_DIGI             Contest = "ARRL-DIGI"             // ARRL-DIGI                = ARRL International Digital Contest
	Contest_ARRL_DX_CW            Contest = "ARRL-DX-CW"            // ARRL-DX-CW               = ARRL International DX Contest (CW)
	Contest_ARRL_DX_SSB           Contest = "ARRL-DX-SSB"           // ARRL-DX-SSB              = ARRL International DX Contest (Phone)
	Contest_ARRL_EME              Contest = "ARRL-EME"              // ARRL-EME                 = ARRL EME contest
	Contest_ARRL_FIELD_DAY        Contest = "ARRL-FIELD-DAY"        // ARRL-FIELD-DAY           = ARRL Field Day
	Contest_ARRL_RR_CW            Contest = "ARRL-RR-CW"            // ARRL-RR-CW               = ARRL Rookie Roundup (CW)
	Contest_ARRL_RR_RTTY          Contest = "ARRL-RR-RTTY"          // ARRL-RR-RTTY             = ARRL Rookie Roundup (RTTY)
	Contest_ARRL_RR_SSB           Contest = "ARRL-RR-SSB"           // ARRL-RR-SSB              = ARRL Rookie Roundup (Phone)
	Contest_ARRL_RTTY             Contest = "ARRL-RTTY"             // ARRL-RTTY                = ARRL RTTY Round-Up
	Contest_ARRL_SCR              Contest = "ARRL-SCR"              // ARRL-SCR                 = ARRL School Club Roundup
	Contest_ARRL_SS_CW            Contest = "ARRL-SS-CW"            // ARRL-SS-CW               = ARRL November Sweepstakes (CW)
	Contest_ARRL_SS_SSB           Contest = "ARRL-SS-SSB"           // ARRL-SS-SSB              = ARRL November Sweepstakes (Phone)
	Contest_ARRL_UHF_AUG          Contest = "ARRL-UHF-AUG"          // ARRL-UHF-AUG             = ARRL August UHF Contest
	Contest_ARRL_VHF_JAN          Contest = "ARRL-VHF-JAN"          // ARRL-VHF-JAN             = ARRL January VHF Sweepstakes
	Contest_ARRL_VHF_JUN          Contest = "ARRL-VHF-JUN"          // ARRL-VHF-JUN             = ARRL June VHF QSO Party
	Contest_ARRL_VHF_SEP          Contest = "ARRL-VHF-SEP"          // ARRL-VHF-SEP             = ARRL September VHF QSO Party
	Contest_AZ_QSO_PARTY          Contest = "AZ-QSO-PARTY"          // AZ-QSO-PARTY             = Arizona QSO Party
	Contest_BARTG_RTTY            Contest = "BARTG-RTTY"            // BARTG-RTTY               = BARTG Spring RTTY Contest
	Contest_BARTG_SPRINT          Contest = "BARTG-SPRINT"          // BARTG-SPRINT             = BARTG Sprint Contest
	Contest_BC_QSO_PARTY          Contest = "BC-QSO-PARTY"          // BC-QSO-PARTY             = British Columbia QSO Party
	Contest_CA_QSO_PARTY          Contest = "CA-QSO-PARTY"          // CA-QSO-PARTY             = California QSO Party
	Contest_CIS_DX                Contest = "CIS-DX"                // CIS-DX                   = CIS DX Contest
	Contest_CO_QSO_PARTY          Contest = "CO-QSO-PARTY"          // CO-QSO-PARTY             = Colorado QSO Party
	Contest_CQ_160_CW             Contest = "CQ-160-CW"             // CQ-160-CW                = CQ WW 160 Meter DX Contest (CW)
	Contest_CQ_160_SSB            Contest = "CQ-160-SSB"            // CQ-160-SSB               = CQ WW 160 Meter DX Contest (SSB)
	Contest_CQ_M                  Contest = "CQ-M"                  // CQ-M                     = CQ-M International DX Contest
	Contest_CQ_VHF                Contest = "CQ-VHF"                // CQ-VHF                   = CQ World-Wide VHF Contest
	Contest_CQ_WPX_CW             Contest = "CQ-WPX-CW"             // CQ-WPX-CW                = CQ WW WPX Contest (CW)
	Contest_CQ_WPX_RTTY           Contest = "CQ-WPX-RTTY"           // CQ-WPX-RTTY              = CQ/RJ WW RTTY WPX Contest
	Contest_CQ_WPX_SSB            Contest = "CQ-WPX-SSB"            // CQ-WPX-SSB               = CQ WW WPX Contest (SSB)
	Contest_CQ_WW_CW              Contest = "CQ-WW-CW"              // CQ-WW-CW                 = CQ WW DX Contest (CW)
	Contest_CQ_WW_RTTY            Contest = "CQ-WW-RTTY"            // CQ-WW-RTTY               = CQ/RJ WW RTTY DX Contest
	Contest_CQ_WW_SSB             Contest = "CQ-WW-SSB"             // CQ-WW-SSB                = CQ WW DX Contest (SSB)
	Contest_CT_QSO_PARTY          Contest = "CT-QSO-PARTY"          // CT-QSO-PARTY             = Connecticut QSO Party
	Contest_CVA_DX_CW             Contest = "CVA-DX-CW"             // CVA-DX-CW                = Concurso Verde e Amarelo DX CW Contest
	Contest_CVA_DX_SSB            Contest = "CVA-DX-SSB"            // CVA-DX-SSB               = Concurso Verde e Amarelo DX CW Contest
	Contest_CWOPS_CW_OPEN         Contest = "CWOPS-CW-OPEN"         // CWOPS-CW-OPEN            = CWops CW Open Competition
	Contest_CWOPS_CWT             Contest = "CWOPS-CWT"             // CWOPS-CWT                = CWops Mini-CWT Test
	Contest_DARC_FT4              Contest = "DARC-FT4"              // DARC-FT4                 = DARC FT4 Contest
	Contest_DARC_WAEDC_CW         Contest = "DARC-WAEDC-CW"         // DARC-WAEDC-CW            = WAE DX Contest (CW)
	Contest_DARC_WAEDC_RTTY       Contest = "DARC-WAEDC-RTTY"       // DARC-WAEDC-RTTY          = WAE DX Contest (RTTY)
	Contest_DARC_WAEDC_SSB        Contest = "DARC-WAEDC-SSB"        // DARC-WAEDC-SSB           = WAE DX Contest (SSB)
	Contest_DARC_WAG              Contest = "DARC-WAG"              // DARC-WAG                 = DARC Worked All Germany
	Contest_DE_QSO_PARTY          Contest = "DE-QSO-PARTY"          // DE-QSO-PARTY             = Delaware QSO Party
	Contest_DL_DX_RTTY            Contest = "DL-DX-RTTY"            // DL-DX-RTTY               = DL-DX RTTY Contest
	Contest_DMC_RTTY              Contest = "DMC-RTTY"              // DMC-RTTY                 = DMC RTTY Contest
	Contest_EA_CNCW               Contest = "EA-CNCW"               // EA-CNCW                  = Concurso Nacional de Telegrafía
	Contest_EA_DME                Contest = "EA-DME"                // EA-DME                   = Municipios Españoles
	Contest_EA_MAJESTAD_CW        Contest = "EA-MAJESTAD-CW"        // EA-MAJESTAD-CW           = His Majesty The King of Spain CW Contest (2022 and later)
	Contest_EA_MAJESTAD_SSB       Contest = "EA-MAJESTAD-SSB"       // EA-MAJESTAD-SSB          = His Majesty The King of Spain SSB Contest (2022 and later)
	Contest_EA_PSK63              Contest = "EA-PSK63"              // EA-PSK63                 = EA PSK63
	Contest_EA_SMRE_CW            Contest = "EA-SMRE-CW"            // EA-SMRE-CW               = Su Majestad El Rey de España - CW (2021 and earlier)
	Contest_EA_SMRE_SSB           Contest = "EA-SMRE-SSB"           // EA-SMRE-SSB              = Su Majestad El Rey de España - SSB (2021 and earlier)
	Contest_EA_VHF_ATLANTIC       Contest = "EA-VHF-ATLANTIC"       // EA-VHF-ATLANTIC          = Atlántico V-UHF
	Contest_EA_VHF_COM            Contest = "EA-VHF-COM"            // EA-VHF-COM               = Combinado de V-UHF
	Contest_EA_VHF_COSTA_SOL      Contest = "EA-VHF-COSTA-SOL"      // EA-VHF-COSTA-SOL         = Costa del Sol V-UHF
	Contest_EA_VHF_EA             Contest = "EA-VHF-EA"             // EA-VHF-EA                = Nacional VHF
	Contest_EA_VHF_EA1RCS         Contest = "EA-VHF-EA1RCS"         // EA-VHF-EA1RCS            = Segovia EA1RCS V-UHF
	Contest_EA_VHF_QSL            Contest = "EA-VHF-QSL"            // EA-VHF-QSL               = QSL V-UHF & 50MHz
	Contest_EA_VHF_SADURNI        Contest = "EA-VHF-SADURNI"        // EA-VHF-SADURNI           = Sant Sadurni V-UHF
	Contest_EA_WW_RTTY            Contest = "EA-WW-RTTY"            // EA-WW-RTTY               = Unión de Radioaficionados Españoles RTTY Contest
	Contest_EPC_PSK63             Contest = "EPC-PSK63"             // EPC-PSK63                = PSK63 QSO Party
	Contest_EU_SPRINT             Contest = "EU SPRINT"             // EU SPRINT                = EU Sprint
	Contest_EU_HF                 Contest = "EU-HF"                 // EU-HF                    = EU HF Championship
	Contest_EU_PSK_DX             Contest = "EU-PSK-DX"             // EU-PSK-DX                = EU PSK DX Contest
	Contest_EUCW160M              Contest = "EUCW160M"              // EUCW160M                 = European CW Association 160m CW Party
	Contest_FALL_SPRINT           Contest = "FALL SPRINT"           // FALL SPRINT              = FISTS Fall Sprint
	Contest_FL_QSO_PARTY          Contest = "FL-QSO-PARTY"          // FL-QSO-PARTY             = Florida QSO Party
	Contest_GA_QSO_PARTY          Contest = "GA-QSO-PARTY"          // GA-QSO-PARTY             = Georgia QSO Party
	Contest_HA_DX                 Contest = "HA-DX"                 // HA-DX                    = Hungarian DX Contest
	Contest_HELVETIA              Contest = "HELVETIA"              // HELVETIA                 = Helvetia Contest
	Contest_HI_QSO_PARTY          Contest = "HI-QSO-PARTY"          // HI-QSO-PARTY             = Hawaiian QSO Party
	Contest_HOLYLAND              Contest = "HOLYLAND"              // HOLYLAND                 = IARC Holyland Contest
	Contest_IA_QSO_PARTY          Contest = "IA-QSO-PARTY"          // IA-QSO-PARTY             = Iowa QSO Party
	Contest_IARU_FIELD_DAY        Contest = "IARU-FIELD-DAY"        // IARU-FIELD-DAY           = DARC IARU Region 1 Field Day
	Contest_IARU_HF               Contest = "IARU-HF"               // IARU-HF                  = IARU HF World Championship
	Contest_ICWC_MST              Contest = "ICWC-MST"              // ICWC-MST                 = ICWC Medium Speed Test
	Contest_ID_QSO_PARTY          Contest = "ID-QSO-PARTY"          // ID-QSO-PARTY             = Idaho QSO Party
	Contest_IL_QSO_PARTY          Contest = "IL QSO PARTY"          // IL QSO PARTY             = Illinois QSO Party
	Contest_IN_QSO_PARTY          Contest = "IN-QSO-PARTY"          // IN-QSO-PARTY             = Indiana QSO Party
	Contest_JARTS_WW_RTTY         Contest = "JARTS-WW-RTTY"         // JARTS-WW-RTTY            = JARTS WW RTTY
	Contest_JIDX_CW               Contest = "JIDX-CW"               // JIDX-CW                  = Japan International DX Contest (CW)
	Contest_JIDX_SSB              Contest = "JIDX-SSB"              // JIDX-SSB                 = Japan International DX Contest (SSB)
	Contest_JT_DX_RTTY            Contest = "JT-DX-RTTY"            // JT-DX-RTTY               = Mongolian RTTY DX Contest
	Contest_K1USN_SSO             Contest = "K1USN-SSO"             // K1USN-SSO                = K1USN Slow Speed Open
	Contest_K1USN_SST             Contest = "K1USN-SST"             // K1USN-SST                = K1USN Slow Speed Test
	Contest_KS_QSO_PARTY          Contest = "KS-QSO-PARTY"          // KS-QSO-PARTY             = Kansas QSO Party
	Contest_KY_QSO_PARTY          Contest = "KY-QSO-PARTY"          // KY-QSO-PARTY             = Kentucky QSO Party
	Contest_LA_QSO_PARTY          Contest = "LA-QSO-PARTY"          // LA-QSO-PARTY             = Louisiana QSO Party
	Contest_LDC_RTTY              Contest = "LDC-RTTY"              // LDC-RTTY                 = DRCG Long Distance Contest (RTTY)
	Contest_LZ_DX                 Contest = "LZ DX"                 // LZ DX                    = LZ DX Contest
	Contest_MAR_QSO_PARTY         Contest = "MAR-QSO-PARTY"         // MAR-QSO-PARTY            = Maritimes QSO Party
	Contest_MD_QSO_PARTY          Contest = "MD-QSO-PARTY"          // MD-QSO-PARTY             = Maryland QSO Party
	Contest_ME_QSO_PARTY          Contest = "ME-QSO-PARTY"          // ME-QSO-PARTY             = Maine QSO Party
	Contest_MI_QSO_PARTY          Contest = "MI-QSO-PARTY"          // MI-QSO-PARTY             = Michigan QSO Party
	Contest_MIDATLANTIC_QSO_PARTY Contest = "MIDATLANTIC-QSO-PARTY" // MIDATLANTIC-QSO-PARTY    = Mid-Atlantic QSO Party
	Contest_MN_QSO_PARTY          Contest = "MN-QSO-PARTY"          // MN-QSO-PARTY             = Minnesota QSO Party
	Contest_MO_QSO_PARTY          Contest = "MO-QSO-PARTY"          // MO-QSO-PARTY             = Missouri QSO Party
	Contest_MS_QSO_PARTY          Contest = "MS-QSO-PARTY"          // MS-QSO-PARTY             = Mississippi QSO Party
	Contest_MT_QSO_PARTY          Contest = "MT-QSO-PARTY"          // MT-QSO-PARTY             = Montana QSO Party
	Contest_NA_SPRINT_CW          Contest = "NA-SPRINT-CW"          // NA-SPRINT-CW             = North America Sprint (CW)
	Contest_NA_SPRINT_RTTY        Contest = "NA-SPRINT-RTTY"        // NA-SPRINT-RTTY           = North America Sprint (RTTY)
	Contest_NA_SPRINT_SSB         Contest = "NA-SPRINT-SSB"         // NA-SPRINT-SSB            = North America Sprint (Phone)
	Contest_NAQP_CW               Contest = "NAQP-CW"               // NAQP-CW                  = North America QSO Party (CW)
	Contest_NAQP_RTTY             Contest = "NAQP-RTTY"             // NAQP-RTTY                = North America QSO Party (RTTY)
	Contest_NAQP_SSB              Contest = "NAQP-SSB"              // NAQP-SSB                 = North America QSO Party (Phone)
	Contest_NC_QSO_PARTY          Contest = "NC-QSO-PARTY"          // NC-QSO-PARTY             = North Carolina QSO Party
	Contest_ND_QSO_PARTY          Contest = "ND-QSO-PARTY"          // ND-QSO-PARTY             = North Dakota QSO Party
	Contest_NE_QSO_PARTY          Contest = "NE-QSO-PARTY"          // NE-QSO-PARTY             = Nebraska QSO Party
	Contest_NEQP                  Contest = "NEQP"                  // NEQP                     = New England QSO Party
	Contest_NH_QSO_PARTY          Contest = "NH-QSO-PARTY"          // NH-QSO-PARTY             = New Hampshire QSO Party
	Contest_NJ_QSO_PARTY          Contest = "NJ-QSO-PARTY"          // NJ-QSO-PARTY             = New Jersey QSO Party
	Contest_NM_QSO_PARTY          Contest = "NM-QSO-PARTY"          // NM-QSO-PARTY             = New Mexico QSO Party
	Contest_NRAU_BALTIC_CW        Contest = "NRAU-BALTIC-CW"        // NRAU-BALTIC-CW           = NRAU-Baltic Contest (CW)
	Contest_NRAU_BALTIC_SSB       Contest = "NRAU-BALTIC-SSB"       // NRAU-BALTIC-SSB          = NRAU-Baltic Contest (SSB)
	Contest_NV_QSO_PARTY          Contest = "NV-QSO-PARTY"          // NV-QSO-PARTY             = Nevada QSO Party
	Contest_NY_QSO_PARTY          Contest = "NY-QSO-PARTY"          // NY-QSO-PARTY             = New York QSO Party
	Contest_OCEANIA_DX_CW         Contest = "OCEANIA-DX-CW"         // OCEANIA-DX-CW            = Oceania DX Contest (CW)
	Contest_OCEANIA_DX_SSB        Contest = "OCEANIA-DX-SSB"        // OCEANIA-DX-SSB           = Oceania DX Contest (SSB)
	Contest_OH_QSO_PARTY          Contest = "OH-QSO-PARTY"          // OH-QSO-PARTY             = Ohio QSO Party
	Contest_OK_DX_RTTY            Contest = "OK-DX-RTTY"            // OK-DX-RTTY               = Czech Radio Club OK DX Contest
	Contest_OK_OM_DX              Contest = "OK-OM-DX"              // OK-OM-DX                 = Czech Radio Club OK-OM DX Contest
	Contest_OK_QSO_PARTY          Contest = "OK-QSO-PARTY"          // OK-QSO-PARTY             = Oklahoma QSO Party
	Contest_OMISS_QSO_PARTY       Contest = "OMISS-QSO-PARTY"       // OMISS-QSO-PARTY          = Old Man International Sideband Society QSO Party
	Contest_ON_QSO_PARTY          Contest = "ON-QSO-PARTY"          // ON-QSO-PARTY             = Ontario QSO Party
	Contest_OR_QSO_PARTY          Contest = "OR-QSO-PARTY"          // OR-QSO-PARTY             = Oregon QSO Party
	Contest_PA_QSO_PARTY          Contest = "PA-QSO-PARTY"          // PA-QSO-PARTY             = Pennsylvania QSO Party
	Contest_PACC                  Contest = "PACC"                  // PACC                     = Dutch PACC Contest
	Contest_PCC                   Contest = "PCC"                   // PCC                      = PCCPro CW Contest
	Contest_PSK_DEATHMATCH        Contest = "PSK-DEATHMATCH"        // PSK-DEATHMATCH           = MDXA PSK DeathMatch (2005-2010)
	Contest_QC_QSO_PARTY          Contest = "QC-QSO-PARTY"          // QC-QSO-PARTY             = Quebec QSO Party
	Contest_RAC_CANADA_DAY        Contest = "RAC-CANADA-DAY"        // RAC-CANADA-DAY           = RAC Canada Day Contest
	Contest_RAC_CANADA_WINTER     Contest = "RAC-CANADA-WINTER"     // RAC-CANADA-WINTER        = RAC Canada Winter Contest
	Contest_RDAC                  Contest = "RDAC"                  // RDAC                     = Russian District Award Contest
	Contest_RDXC                  Contest = "RDXC"                  // RDXC                     = Russian DX Contest
	Contest_REF_160M              Contest = "REF-160M"              // REF-160M                 = Reseau des Emetteurs Francais 160m Contest
	Contest_REF_CW                Contest = "REF-CW"                // REF-CW                   = Reseau des Emetteurs Francais Contest (CW)
	Contest_REF_SSB               Contest = "REF-SSB"               // REF-SSB                  = Reseau des Emetteurs Francais Contest (SSB)
	Contest_REP_PORTUGAL_DAY_HF   Contest = "REP-PORTUGAL-DAY-HF"   // REP-PORTUGAL-DAY-HF      = Rede dos Emissores Portugueses Portugal Day HF Contest
	Contest_RI_QSO_PARTY          Contest = "RI-QSO-PARTY"          // RI-QSO-PARTY             = Rhode Island QSO Party
	Contest_RSGB_160              Contest = "RSGB-160"              // RSGB-160                 = 1.8MHz Contest
	Contest_RSGB_21_28_CW         Contest = "RSGB-21/28-CW"         // RSGB-21/28-CW            = 21/28 MHz Contest (CW)
	Contest_RSGB_21_28_SSB        Contest = "RSGB-21/28-SSB"        // RSGB-21/28-SSB           = 21/28 MHz Contest (SSB)
	Contest_RSGB_80M_CC           Contest = "RSGB-80M-CC"           // RSGB-80M-CC              = 80m Club Championships
	Contest_RSGB_AFS_CW           Contest = "RSGB-AFS-CW"           // RSGB-AFS-CW              = Affiliated Societies Team Contest (CW)
	Contest_RSGB_AFS_SSB          Contest = "RSGB-AFS-SSB"          // RSGB-AFS-SSB             = Affiliated Societies Team Contest (SSB)
	Contest_RSGB_CLUB_CALLS       Contest = "RSGB-CLUB-CALLS"       // RSGB-CLUB-CALLS          = Club Calls
	Contest_RSGB_COMMONWEALTH     Contest = "RSGB-COMMONWEALTH"     // RSGB-COMMONWEALTH        = Commonwealth Contest
	Contest_RSGB_IOTA             Contest = "RSGB-IOTA"             // RSGB-IOTA                = IOTA Contest
	Contest_RSGB_LOW_POWER        Contest = "RSGB-LOW-POWER"        // RSGB-LOW-POWER           = Low Power Field Day
	Contest_RSGB_NFD              Contest = "RSGB-NFD"              // RSGB-NFD                 = National Field Day
	Contest_RSGB_ROPOCO           Contest = "RSGB-ROPOCO"           // RSGB-ROPOCO              = RoPoCo
	Contest_RSGB_SSB_FD           Contest = "RSGB-SSB-FD"           // RSGB-SSB-FD              = SSB Field Day
	Contest_RUSSIAN_RTTY          Contest = "RUSSIAN-RTTY"          // RUSSIAN-RTTY             = Russian Radio RTTY Worldwide Contest
	Contest_SAC_CW                Contest = "SAC-CW"                // SAC-CW                   = Scandinavian Activity Contest (CW)
	Contest_SAC_SSB               Contest = "SAC-SSB"               // SAC-SSB                  = Scandinavian Activity Contest (SSB)
	Contest_SARTG_RTTY            Contest = "SARTG-RTTY"            // SARTG-RTTY               = SARTG WW RTTY
	Contest_SC_QSO_PARTY          Contest = "SC-QSO-PARTY"          // SC-QSO-PARTY             = South Carolina QSO Party
	Contest_SCC_RTTY              Contest = "SCC-RTTY"              // SCC-RTTY                 = SCC RTTY Championship
	Contest_SD_QSO_PARTY          Contest = "SD-QSO-PARTY"          // SD-QSO-PARTY             = South Dakota QSO Party
	Contest_SMP_AUG               Contest = "SMP-AUG"               // SMP-AUG                  = SSA Portabeltest
	Contest_SMP_MAY               Contest = "SMP-MAY"               // SMP-MAY                  = SSA Portabeltest
	Contest_SP_DX_RTTY            Contest = "SP-DX-RTTY"            // SP-DX-RTTY               = PRC SPDX Contest (RTTY)
	Contest_SPAR_WINTER_FD        Contest = "SPAR-WINTER-FD"        // SPAR-WINTER-FD           = SPAR Winter Field Day(2016 and earlier)
	Contest_SPDXCONTEST           Contest = "SPDXCONTEST"           // SPDXCONTEST              = SP DX Contest
	Contest_SPRING_SPRINT         Contest = "SPRING SPRINT"         // SPRING SPRINT            = FISTS Spring Sprint
	Contest_SR_MARATHON           Contest = "SR-MARATHON"           // SR-MARATHON              = Scottish-Russian Marathon
	Contest_STEW_PERRY            Contest = "STEW-PERRY"            // STEW-PERRY               = Stew Perry Topband Distance Challenge
	Contest_SUMMER_SPRINT         Contest = "SUMMER SPRINT"         // SUMMER SPRINT            = FISTS Summer Sprint
	Contest_TARA_GRID_DIP         Contest = "TARA-GRID-DIP"         // TARA-GRID-DIP            = TARA Grid Dip PSK-RTTY Shindig
	Contest_TARA_RTTY             Contest = "TARA-RTTY"             // TARA-RTTY                = TARA RTTY Mêlée
	Contest_TARA_RUMBLE           Contest = "TARA-RUMBLE"           // TARA-RUMBLE              = TARA Rumble PSK Contest
	Contest_TARA_SKIRMISH         Contest = "TARA-SKIRMISH"         // TARA-SKIRMISH            = TARA Skirmish Digital Prefix Contest
	Contest_TEN_RTTY              Contest = "TEN-RTTY"              // TEN-RTTY                 = Ten-Meter RTTY Contest (before 2011)
	Contest_TMC_RTTY              Contest = "TMC-RTTY"              // TMC-RTTY                 = The Makrothen Contest
	Contest_TN_QSO_PARTY          Contest = "TN-QSO-PARTY"          // TN-QSO-PARTY             = Tennessee QSO Party
	Contest_TX_QSO_PARTY          Contest = "TX-QSO-PARTY"          // TX-QSO-PARTY             = Texas QSO Party
	Contest_UBA_DX_CW             Contest = "UBA-DX-CW"             // UBA-DX-CW                = UBA Contest (CW)
	Contest_UBA_DX_SSB            Contest = "UBA-DX-SSB"            // UBA-DX-SSB               = UBA Contest (SSB)
	Contest_UK_DX_BPSK63          Contest = "UK-DX-BPSK63"          // UK-DX-BPSK63             = European PSK Club BPSK63 Contest
	Contest_UK_DX_RTTY            Contest = "UK-DX-RTTY"            // UK-DX-RTTY               = UK DX RTTY Contest
	Contest_UKR_CHAMP_RTTY        Contest = "UKR-CHAMP-RTTY"        // UKR-CHAMP-RTTY           = Open Ukraine RTTY Championship
	Contest_UKRAINIAN_DX          Contest = "UKRAINIAN DX"          // UKRAINIAN DX             = Ukrainian DX
	Contest_UKSMG_6M_MARATHON     Contest = "UKSMG-6M-MARATHON"     // UKSMG-6M-MARATHON        = UKSMG 6m Marathon
	Contest_UKSMG_SUMMER_ES       Contest = "UKSMG-SUMMER-ES"       // UKSMG-SUMMER-ES          = UKSMG Summer Es Contest
	Contest_US_COUNTIES_QSO       Contest = "US-COUNTIES-QSO"       // US-COUNTIES-QSO          = Mobile Amateur Awards Club
	Contest_UT_QSO_PARTY          Contest = "UT-QSO-PARTY"          // UT-QSO-PARTY             = Utah QSO Party
	Contest_VA_QSO_PARTY          Contest = "VA-QSO-PARTY"          // VA-QSO-PARTY             = Virginia QSO Party
	Contest_VENEZ_IND_DAY         Contest = "VENEZ-IND-DAY"         // VENEZ-IND-DAY            = RCV Venezuelan Independence Day Contest
	Contest_VOLTA_RTTY            Contest = "VOLTA-RTTY"            // VOLTA-RTTY               = Alessandro Volta RTTY DX Contest
	Contest_VT_QSO_PARTY          Contest = "VT-QSO-PARTY"          // VT-QSO-PARTY             = Vermont QSO Party
	Contest_WA_QSO_PARTY          Contest = "WA-QSO-PARTY"          // WA-QSO-PARTY             = Washington QSO Party
	Contest_WFD                   Contest = "WFD"                   // WFD                      = Winter Field Day (2017 and later)
	Contest_WI_QSO_PARTY          Contest = "WI-QSO-PARTY"          // WI-QSO-PARTY             = Wisconsin QSO Party
	Contest_WIA_HARRY_ANGEL       Contest = "WIA-HARRY ANGEL"       // WIA-HARRY ANGEL          = WIA Harry Angel Memorial 80m Sprint
	Contest_WIA_JMMFD             Contest = "WIA-JMMFD"             // WIA-JMMFD                = WIA John Moyle Memorial Field Day
	Contest_WIA_OCDX              Contest = "WIA-OCDX"              // WIA-OCDX                 = WIA Oceania DX (OCDX) Contest
	Contest_WIA_REMEMBRANCE       Contest = "WIA-REMEMBRANCE"       // WIA-REMEMBRANCE          = WIA Remembrance Day
	Contest_WIA_ROSS_HULL         Contest = "WIA-ROSS HULL"         // WIA-ROSS HULL            = WIA Ross Hull Memorial VHF/UHF Contest
	Contest_WIA_TRANS_TASMAN      Contest = "WIA-TRANS TASMAN"      // WIA-TRANS TASMAN         = WIA Trans Tasman Low Bands Challenge
	Contest_WIA_VHF_UHF_FD        Contest = "WIA-VHF/UHF FD"        // WIA-VHF/UHF FD           = WIA VHF UHF Field Days
	Contest_WIA_VK_SHIRES         Contest = "WIA-VK SHIRES"         // WIA-VK SHIRES            = WIA VK Shires
	Contest_WINTER_SPRINT         Contest = "WINTER SPRINT"         // WINTER SPRINT            = FISTS Winter Sprint
	Contest_WV_QSO_PARTY          Contest = "WV-QSO-PARTY"          // WV-QSO-PARTY             = West Virginia QSO Party
	Contest_WW_DIGI               Contest = "WW-DIGI"               // WW-DIGI                  = World Wide Digi DX Contest
	Contest_WY_QSO_PARTY          Contest = "WY-QSO-PARTY"          // WY-QSO-PARTY             = Wyoming QSO Party
	Contest_XE_INTL_RTTY          Contest = "XE-INTL-RTTY"          // XE-INTL-RTTY             = Mexico International Contest (RTTY)
	Contest_YOHFDX                Contest = "YOHFDX"                // YOHFDX                   = YODX HF contest
	Contest_YUDXC                 Contest = "YUDXC"                 // YUDXC                    = YU DX Contest
)
