// GENERATED CODE; DO NOT EDIT
// ADIF: 3.1.6 Proposed

package submode

var (
	SubMode8PSK1000       SubMode = "8PSK1000"       //
	SubMode8PSK1000F      SubMode = "8PSK1000F"      //
	SubMode8PSK1200F      SubMode = "8PSK1200F"      //
	SubMode8PSK125        SubMode = "8PSK125"        //
	SubMode8PSK125F       SubMode = "8PSK125F"       //
	SubMode8PSK125FL      SubMode = "8PSK125FL"      //
	SubMode8PSK250        SubMode = "8PSK250"        //
	SubMode8PSK250F       SubMode = "8PSK250F"       //
	SubMode8PSK250FL      SubMode = "8PSK250FL"      //
	SubMode8PSK500        SubMode = "8PSK500"        //
	SubMode8PSK500F       SubMode = "8PSK500F"       //
	SubModeAMTORFEC       SubMode = "AMTORFEC"       //
	SubModeASCI           SubMode = "ASCI"           //
	SubModeC4FM           SubMode = "C4FM"           // C4FM 4-level FSK See the Propagation_Mode enumeration section for examples of representing C4FM voice transmissions.
	SubModeCHIP128        SubMode = "CHIP128"        //
	SubModeCHIP64         SubMode = "CHIP64"         //
	SubModeDMR            SubMode = "DMR"            // Digital Mobile Radio See the Propagation_Mode enumeration section for examples of representing DMR voice transmissions.
	SubModeDOM_M          SubMode = "DOM-M"          //
	SubModeDOM11          SubMode = "DOM11"          //
	SubModeDOM16          SubMode = "DOM16"          //
	SubModeDOM22          SubMode = "DOM22"          //
	SubModeDOM4           SubMode = "DOM4"           //
	SubModeDOM44          SubMode = "DOM44"          //
	SubModeDOM5           SubMode = "DOM5"           //
	SubModeDOM8           SubMode = "DOM8"           //
	SubModeDOM88          SubMode = "DOM88"          //
	SubModeDOMINOEX       SubMode = "DOMINOEX"       //
	SubModeDOMINOF        SubMode = "DOMINOF"        //
	SubModeDSTAR          SubMode = "DSTAR"          // Digital Smart Technologies for Amateur Radio See the Propagation_Mode enumeration section for examples of representing DSTAR voice transmissions.
	SubModeFMHELL         SubMode = "FMHELL"         //
	SubModeFREEDV         SubMode = "FREEDV"         // Digital voice mode for HF radio implemented with open source
	SubModeFSK31          SubMode = "FSK31"          //
	SubModeFSKH105        SubMode = "FSKH105"        //
	SubModeFSKH245        SubMode = "FSKH245"        //
	SubModeFSKHELL        SubMode = "FSKHELL"        //
	SubModeFSQCALL        SubMode = "FSQCALL"        // FSQCall protocol used with FSQ (Fast Simple QSO) transmission mode
	SubModeFST4           SubMode = "FST4"           // This is a digital mode supported by the WSJT-X software
	SubModeFST4W          SubMode = "FST4W"          // This is a digital mode supported by the WSJT-X software that is for quasi-beacon transmissions of WSPR-style messages
	SubModeFT4            SubMode = "FT4"            // FT4 is a digital mode designed specifically for radio contesting
	SubModeGTOR           SubMode = "GTOR"           //
	SubModeHELL80         SubMode = "HELL80"         //
	SubModeHELLX5         SubMode = "HELLX5"         //
	SubModeHELLX9         SubMode = "HELLX9"         //
	SubModeHFSK           SubMode = "HFSK"           //
	SubModeISCAT_A        SubMode = "ISCAT-A"        //
	SubModeISCAT_B        SubMode = "ISCAT-B"        //
	SubModeJS8            SubMode = "JS8"            // Jordan Sherer designed 8-FSK modulation
	SubModeJT4A           SubMode = "JT4A"           //
	SubModeJT4B           SubMode = "JT4B"           //
	SubModeJT4C           SubMode = "JT4C"           //
	SubModeJT4D           SubMode = "JT4D"           //
	SubModeJT4E           SubMode = "JT4E"           //
	SubModeJT4F           SubMode = "JT4F"           //
	SubModeJT4G           SubMode = "JT4G"           //
	SubModeJT65A          SubMode = "JT65A"          //
	SubModeJT65B          SubMode = "JT65B"          //
	SubModeJT65B2         SubMode = "JT65B2"         //
	SubModeJT65C          SubMode = "JT65C"          //
	SubModeJT65C2         SubMode = "JT65C2"         //
	SubModeJT9_1          SubMode = "JT9-1"          //
	SubModeJT9_10         SubMode = "JT9-10"         //
	SubModeJT9_2          SubMode = "JT9-2"          //
	SubModeJT9_30         SubMode = "JT9-30"         //
	SubModeJT9_5          SubMode = "JT9-5"          //
	SubModeJT9A           SubMode = "JT9A"           //
	SubModeJT9B           SubMode = "JT9B"           //
	SubModeJT9C           SubMode = "JT9C"           //
	SubModeJT9D           SubMode = "JT9D"           //
	SubModeJT9E           SubMode = "JT9E"           //
	SubModeJT9E_FAST      SubMode = "JT9E FAST"      //
	SubModeJT9F           SubMode = "JT9F"           //
	SubModeJT9F_FAST      SubMode = "JT9F FAST"      //
	SubModeJT9G           SubMode = "JT9G"           //
	SubModeJT9G_FAST      SubMode = "JT9G FAST"      //
	SubModeJT9H           SubMode = "JT9H"           //
	SubModeJT9H_FAST      SubMode = "JT9H FAST"      //
	SubModeJTMS           SubMode = "JTMS"           //
	SubModeLSB            SubMode = "LSB"            // Amplitude modulated voice telephony, lower-sideband, suppressed-carrier
	SubModeM17            SubMode = "M17"            // Digital radio protocol using the Codec 2 voice encoder
	SubModeMFSK11         SubMode = "MFSK11"         //
	SubModeMFSK128        SubMode = "MFSK128"        //
	SubModeMFSK128L       SubMode = "MFSK128L"       //
	SubModeMFSK16         SubMode = "MFSK16"         //
	SubModeMFSK22         SubMode = "MFSK22"         //
	SubModeMFSK31         SubMode = "MFSK31"         //
	SubModeMFSK32         SubMode = "MFSK32"         //
	SubModeMFSK4          SubMode = "MFSK4"          //
	SubModeMFSK64         SubMode = "MFSK64"         //
	SubModeMFSK64L        SubMode = "MFSK64L"        //
	SubModeMFSK8          SubMode = "MFSK8"          //
	SubModeNAVTEX         SubMode = "NAVTEX"         //
	SubModeOLIVIA_16_1000 SubMode = "OLIVIA 16/1000" //
	SubModeOLIVIA_16_500  SubMode = "OLIVIA 16/500"  //
	SubModeOLIVIA_32_1000 SubMode = "OLIVIA 32/1000" //
	SubModeOLIVIA_4_125   SubMode = "OLIVIA 4/125"   //
	SubModeOLIVIA_4_250   SubMode = "OLIVIA 4/250"   //
	SubModeOLIVIA_8_250   SubMode = "OLIVIA 8/250"   //
	SubModeOLIVIA_8_500   SubMode = "OLIVIA 8/500"   //
	SubModeOPERA_BEACON   SubMode = "OPERA-BEACON"   //
	SubModeOPERA_QSO      SubMode = "OPERA-QSO"      //
	SubModePAC2           SubMode = "PAC2"           //
	SubModePAC3           SubMode = "PAC3"           //
	SubModePAC4           SubMode = "PAC4"           //
	SubModePAX2           SubMode = "PAX2"           //
	SubModePCW            SubMode = "PCW"            // Coherent CW
	SubModePSK10          SubMode = "PSK10"          //
	SubModePSK1000        SubMode = "PSK1000"        //
	SubModePSK1000RC2     SubMode = "PSK1000RC2"     //
	SubModePSK125         SubMode = "PSK125"         //
	SubModePSK125RC10     SubMode = "PSK125RC10"     //
	SubModePSK125RC12     SubMode = "PSK125RC12"     //
	SubModePSK125RC16     SubMode = "PSK125RC16"     //
	SubModePSK125RC4      SubMode = "PSK125RC4"      //
	SubModePSK125RC5      SubMode = "PSK125RC5"      //
	SubModePSK250         SubMode = "PSK250"         //
	SubModePSK250RC2      SubMode = "PSK250RC2"      //
	SubModePSK250RC3      SubMode = "PSK250RC3"      //
	SubModePSK250RC5      SubMode = "PSK250RC5"      //
	SubModePSK250RC6      SubMode = "PSK250RC6"      //
	SubModePSK250RC7      SubMode = "PSK250RC7"      //
	SubModePSK31          SubMode = "PSK31"          //
	SubModePSK500         SubMode = "PSK500"         //
	SubModePSK500RC2      SubMode = "PSK500RC2"      //
	SubModePSK500RC3      SubMode = "PSK500RC3"      //
	SubModePSK500RC4      SubMode = "PSK500RC4"      //
	SubModePSK63          SubMode = "PSK63"          //
	SubModePSK63F         SubMode = "PSK63F"         //
	SubModePSK63RC10      SubMode = "PSK63RC10"      //
	SubModePSK63RC20      SubMode = "PSK63RC20"      //
	SubModePSK63RC32      SubMode = "PSK63RC32"      //
	SubModePSK63RC4       SubMode = "PSK63RC4"       //
	SubModePSK63RC5       SubMode = "PSK63RC5"       //
	SubModePSK800RC2      SubMode = "PSK800RC2"      //
	SubModePSKAM10        SubMode = "PSKAM10"        //
	SubModePSKAM31        SubMode = "PSKAM31"        //
	SubModePSKAM50        SubMode = "PSKAM50"        //
	SubModePSKFEC31       SubMode = "PSKFEC31"       //
	SubModePSKHELL        SubMode = "PSKHELL"        //
	SubModeQ65            SubMode = "Q65"            //
	SubModeQPSK125        SubMode = "QPSK125"        //
	SubModeQPSK250        SubMode = "QPSK250"        //
	SubModeQPSK31         SubMode = "QPSK31"         //
	SubModeQPSK500        SubMode = "QPSK500"        //
	SubModeQPSK63         SubMode = "QPSK63"         //
	SubModeQRA64A         SubMode = "QRA64A"         //
	SubModeQRA64B         SubMode = "QRA64B"         //
	SubModeQRA64C         SubMode = "QRA64C"         //
	SubModeQRA64D         SubMode = "QRA64D"         //
	SubModeQRA64E         SubMode = "QRA64E"         //
	SubModeROS_EME        SubMode = "ROS-EME"        //
	SubModeROS_HF         SubMode = "ROS-HF"         //
	SubModeROS_MF         SubMode = "ROS-MF"         //
	SubModeSCAMP_FAST     SubMode = "SCAMP_FAST"     // SCAMP fast FSK
	SubModeSCAMP_OO       SubMode = "SCAMP_OO"       // SCAMP single modulated tone on/off keying
	SubModeSCAMP_OO_SLW   SubMode = "SCAMP_OO_SLW"   // SCAMP single modulated tone on/off slow keying
	SubModeSCAMP_SLOW     SubMode = "SCAMP_SLOW"     // SCAMP slow FSK
	SubModeSCAMP_VSLOW    SubMode = "SCAMP_VSLOW"    // SCAMP very slow FSK
	SubModeSIM31          SubMode = "SIM31"          //
	SubModeSITORB         SubMode = "SITORB"         //
	SubModeSLOWHELL       SubMode = "SLOWHELL"       //
	SubModeTHOR_M         SubMode = "THOR-M"         //
	SubModeTHOR100        SubMode = "THOR100"        //
	SubModeTHOR11         SubMode = "THOR11"         //
	SubModeTHOR16         SubMode = "THOR16"         //
	SubModeTHOR22         SubMode = "THOR22"         //
	SubModeTHOR25X4       SubMode = "THOR25X4"       //
	SubModeTHOR4          SubMode = "THOR4"          //
	SubModeTHOR5          SubMode = "THOR5"          //
	SubModeTHOR50X1       SubMode = "THOR50X1"       //
	SubModeTHOR50X2       SubMode = "THOR50X2"       //
	SubModeTHOR8          SubMode = "THOR8"          //
	SubModeTHRBX          SubMode = "THRBX"          //
	SubModeTHRBX1         SubMode = "THRBX1"         //
	SubModeTHRBX2         SubMode = "THRBX2"         //
	SubModeTHRBX4         SubMode = "THRBX4"         //
	SubModeTHROB1         SubMode = "THROB1"         //
	SubModeTHROB2         SubMode = "THROB2"         //
	SubModeTHROB4         SubMode = "THROB4"         //
	SubModeUSB            SubMode = "USB"            // Amplitude modulated voice telephony, upper-sideband, suppressed-carrier
	SubModeVARA_FM_1200   SubMode = "VARA FM 1200"   // Channel adaptive high-speed modem for FM transceivers
	SubModeVARA_FM_9600   SubMode = "VARA FM 9600"   // Channel adaptive high-speed modem for FM transceivers
	SubModeVARA_HF        SubMode = "VARA HF"        // Channel adaptive high-speed modem for HF
	SubModeVARA_SATELLITE SubMode = "VARA SATELLITE" // Channel adaptive high-speed modem for satellite operations
)
