// GENERATED CODE; DO NOT EDIT
// ADIF: 3.1.6 Proposed

package submode

var (
	SubMode8PSK1000       SubMode = "8PSK1000"       //
	SubMode8PSK1000F      SubMode = "8PSK1000F"      //
	SubMode8PSK1200F      SubMode = "8PSK1200F"      //
	SubMode8PSK125        SubMode = "8PSK125"        //
	SubMode8PSK125F       SubMode = "8PSK125F"       //
	SubMode8PSK125FL      SubMode = "8PSK125FL"      //
	SubMode8PSK250        SubMode = "8PSK250"        //
	SubMode8PSK250F       SubMode = "8PSK250F"       //
	SubMode8PSK250FL      SubMode = "8PSK250FL"      //
	SubMode8PSK500        SubMode = "8PSK500"        //
	SubMode8PSK500F       SubMode = "8PSK500F"       //
	SubModeAMTORFEC       SubMode = "AMTORFEC"       //
	SubModeASCI           SubMode = "ASCI"           //
	SubModeC4FM           SubMode = "C4FM"           // C4FM 4-level FSK See the Propagation_Mode enumeration section for examples of representing C4FM voice transmissions.
	SubModeCHIP128        SubMode = "CHIP128"        //
	SubModeCHIP64         SubMode = "CHIP64"         //
	SubModeDMR            SubMode = "DMR"            // Digital Mobile Radio See the Propagation_Mode enumeration section for examples of representing DMR voice transmissions.
	SubModeDOM_M          SubMode = "DOM-M"          //
	SubModeDOM11          SubMode = "DOM11"          //
	SubModeDOM16          SubMode = "DOM16"          //
	SubModeDOM22          SubMode = "DOM22"          //
	SubModeDOM4           SubMode = "DOM4"           //
	SubModeDOM44          SubMode = "DOM44"          //
	SubModeDOM5           SubMode = "DOM5"           //
	SubModeDOM8           SubMode = "DOM8"           //
	SubModeDOM88          SubMode = "DOM88"          //
	SubModeDOMINOEX       SubMode = "DOMINOEX"       //
	SubModeDOMINOF        SubMode = "DOMINOF"        //
	SubModeDSTAR          SubMode = "DSTAR"          // Digital Smart Technologies for Amateur Radio See the Propagation_Mode enumeration section for examples of representing DSTAR voice transmissions.
	SubModeFMHELL         SubMode = "FMHELL"         //
	SubModeFREEDV         SubMode = "FREEDV"         // Digital voice mode for HF radio implemented with open source
	SubModeFSK31          SubMode = "FSK31"          //
	SubModeFSKH105        SubMode = "FSKH105"        //
	SubModeFSKH245        SubMode = "FSKH245"        //
	SubModeFSKHELL        SubMode = "FSKHELL"        //
	SubModeFSQCALL        SubMode = "FSQCALL"        // FSQCall protocol used with FSQ (Fast Simple QSO) transmission mode
	SubModeFST4           SubMode = "FST4"           // This is a digital mode supported by the WSJT-X software
	SubModeFST4W          SubMode = "FST4W"          // This is a digital mode supported by the WSJT-X software that is for quasi-beacon transmissions of WSPR-style messages
	SubModeFT4            SubMode = "FT4"            // FT4 is a digital mode designed specifically for radio contesting
	SubModeGTOR           SubMode = "GTOR"           //
	SubModeHELL80         SubMode = "HELL80"         //
	SubModeHELLX5         SubMode = "HELLX5"         //
	SubModeHELLX9         SubMode = "HELLX9"         //
	SubModeHFSK           SubMode = "HFSK"           //
	SubModeISCAT_A        SubMode = "ISCAT-A"        //
	SubModeISCAT_B        SubMode = "ISCAT-B"        //
	SubModeJS8            SubMode = "JS8"            // Jordan Sherer designed 8-FSK modulation
	SubModeJT4A           SubMode = "JT4A"           //
	SubModeJT4B           SubMode = "JT4B"           //
	SubModeJT4C           SubMode = "JT4C"           //
	SubModeJT4D           SubMode = "JT4D"           //
	SubModeJT4E           SubMode = "JT4E"           //
	SubModeJT4F           SubMode = "JT4F"           //
	SubModeJT4G           SubMode = "JT4G"           //
	SubModeJT65A          SubMode = "JT65A"          //
	SubModeJT65B          SubMode = "JT65B"          //
	SubModeJT65B2         SubMode = "JT65B2"         //
	SubModeJT65C          SubMode = "JT65C"          //
	SubModeJT65C2         SubMode = "JT65C2"         //
	SubModeJT9_1          SubMode = "JT9-1"          //
	SubModeJT9_10         SubMode = "JT9-10"         //
	SubModeJT9_2          SubMode = "JT9-2"          //
	SubModeJT9_30         SubMode = "JT9-30"         //
	SubModeJT9_5          SubMode = "JT9-5"          //
	SubModeJT9A           SubMode = "JT9A"           //
	SubModeJT9B           SubMode = "JT9B"           //
	SubModeJT9C           SubMode = "JT9C"           //
	SubModeJT9D           SubMode = "JT9D"           //
	SubModeJT9E           SubMode = "JT9E"           //
	SubModeJT9E_FAST      SubMode = "JT9E FAST"      //
	SubModeJT9F           SubMode = "JT9F"           //
	SubModeJT9F_FAST      SubMode = "JT9F FAST"      //
	SubModeJT9G           SubMode = "JT9G"           //
	SubModeJT9G_FAST      SubMode = "JT9G FAST"      //
	SubModeJT9H           SubMode = "JT9H"           //
	SubModeJT9H_FAST      SubMode = "JT9H FAST"      //
	SubModeJTMS           SubMode = "JTMS"           //
	SubModeLSB            SubMode = "LSB"            // Amplitude modulated voice telephony, lower-sideband, suppressed-carrier
	SubModeM17            SubMode = "M17"            // Digital radio protocol using the Codec 2 voice encoder
	SubModeMFSK11         SubMode = "MFSK11"         //
	SubModeMFSK128        SubMode = "MFSK128"        //
	SubModeMFSK128L       SubMode = "MFSK128L"       //
	SubModeMFSK16         SubMode = "MFSK16"         //
	SubModeMFSK22         SubMode = "MFSK22"         //
	SubModeMFSK31         SubMode = "MFSK31"         //
	SubModeMFSK32         SubMode = "MFSK32"         //
	SubModeMFSK4          SubMode = "MFSK4"          //
	SubModeMFSK64         SubMode = "MFSK64"         //
	SubModeMFSK64L        SubMode = "MFSK64L"        //
	SubModeMFSK8          SubMode = "MFSK8"          //
	SubModeNAVTEX         SubMode = "NAVTEX"         //
	SubModeOLIVIA_16_1000 SubMode = "OLIVIA 16/1000" //
	SubModeOLIVIA_16_500  SubMode = "OLIVIA 16/500"  //
	SubModeOLIVIA_32_1000 SubMode = "OLIVIA 32/1000" //
	SubModeOLIVIA_4_125   SubMode = "OLIVIA 4/125"   //
	SubModeOLIVIA_4_250   SubMode = "OLIVIA 4/250"   //
	SubModeOLIVIA_8_250   SubMode = "OLIVIA 8/250"   //
	SubModeOLIVIA_8_500   SubMode = "OLIVIA 8/500"   //
	SubModeOPERA_BEACON   SubMode = "OPERA-BEACON"   //
	SubModeOPERA_QSO      SubMode = "OPERA-QSO"      //
	SubModePAC2           SubMode = "PAC2"           //
	SubModePAC3           SubMode = "PAC3"           //
	SubModePAC4           SubMode = "PAC4"           //
	SubModePAX2           SubMode = "PAX2"           //
	SubModePCW            SubMode = "PCW"            // Coherent CW
	SubModePSK10          SubMode = "PSK10"          //
	SubModePSK1000        SubMode = "PSK1000"        //
	SubModePSK1000RC2     SubMode = "PSK1000RC2"     //
	SubModePSK125         SubMode = "PSK125"         //
	SubModePSK125RC10     SubMode = "PSK125RC10"     //
	SubModePSK125RC12     SubMode = "PSK125RC12"     //
	SubModePSK125RC16     SubMode = "PSK125RC16"     //
	SubModePSK125RC4      SubMode = "PSK125RC4"      //
	SubModePSK125RC5      SubMode = "PSK125RC5"      //
	SubModePSK250         SubMode = "PSK250"         //
	SubModePSK250RC2      SubMode = "PSK250RC2"      //
	SubModePSK250RC3      SubMode = "PSK250RC3"      //
	SubModePSK250RC5      SubMode = "PSK250RC5"      //
	SubModePSK250RC6      SubMode = "PSK250RC6"      //
	SubModePSK250RC7      SubMode = "PSK250RC7"      //
	SubModePSK31          SubMode = "PSK31"          //
	SubModePSK500         SubMode = "PSK500"         //
	SubModePSK500RC2      SubMode = "PSK500RC2"      //
	SubModePSK500RC3      SubMode = "PSK500RC3"      //
	SubModePSK500RC4      SubMode = "PSK500RC4"      //
	SubModePSK63          SubMode = "PSK63"          //
	SubModePSK63F         SubMode = "PSK63F"         //
	SubModePSK63RC10      SubMode = "PSK63RC10"      //
	SubModePSK63RC20      SubMode = "PSK63RC20"      //
	SubModePSK63RC32      SubMode = "PSK63RC32"      //
	SubModePSK63RC4       SubMode = "PSK63RC4"       //
	SubModePSK63RC5       SubMode = "PSK63RC5"       //
	SubModePSK800RC2      SubMode = "PSK800RC2"      //
	SubModePSKAM10        SubMode = "PSKAM10"        //
	SubModePSKAM31        SubMode = "PSKAM31"        //
	SubModePSKAM50        SubMode = "PSKAM50"        //
	SubModePSKFEC31       SubMode = "PSKFEC31"       //
	SubModePSKHELL        SubMode = "PSKHELL"        //
	SubModeQ65            SubMode = "Q65"            //
	SubModeQPSK125        SubMode = "QPSK125"        //
	SubModeQPSK250        SubMode = "QPSK250"        //
	SubModeQPSK31         SubMode = "QPSK31"         //
	SubModeQPSK500        SubMode = "QPSK500"        //
	SubModeQPSK63         SubMode = "QPSK63"         //
	SubModeQRA64A         SubMode = "QRA64A"         //
	SubModeQRA64B         SubMode = "QRA64B"         //
	SubModeQRA64C         SubMode = "QRA64C"         //
	SubModeQRA64D         SubMode = "QRA64D"         //
	SubModeQRA64E         SubMode = "QRA64E"         //
	SubModeROS_EME        SubMode = "ROS-EME"        //
	SubModeROS_HF         SubMode = "ROS-HF"         //
	SubModeROS_MF         SubMode = "ROS-MF"         //
	SubModeSCAMP_FAST     SubMode = "SCAMP_FAST"     // SCAMP fast FSK
	SubModeSCAMP_OO       SubMode = "SCAMP_OO"       // SCAMP single modulated tone on/off keying
	SubModeSCAMP_OO_SLW   SubMode = "SCAMP_OO_SLW"   // SCAMP single modulated tone on/off slow keying
	SubModeSCAMP_SLOW     SubMode = "SCAMP_SLOW"     // SCAMP slow FSK
	SubModeSCAMP_VSLOW    SubMode = "SCAMP_VSLOW"    // SCAMP very slow FSK
	SubModeSIM31          SubMode = "SIM31"          //
	SubModeSITORB         SubMode = "SITORB"         //
	SubModeSLOWHELL       SubMode = "SLOWHELL"       //
	SubModeTHOR_M         SubMode = "THOR-M"         //
	SubModeTHOR100        SubMode = "THOR100"        //
	SubModeTHOR11         SubMode = "THOR11"         //
	SubModeTHOR16         SubMode = "THOR16"         //
	SubModeTHOR22         SubMode = "THOR22"         //
	SubModeTHOR25X4       SubMode = "THOR25X4"       //
	SubModeTHOR4          SubMode = "THOR4"          //
	SubModeTHOR5          SubMode = "THOR5"          //
	SubModeTHOR50X1       SubMode = "THOR50X1"       //
	SubModeTHOR50X2       SubMode = "THOR50X2"       //
	SubModeTHOR8          SubMode = "THOR8"          //
	SubModeTHRBX          SubMode = "THRBX"          //
	SubModeTHRBX1         SubMode = "THRBX1"         //
	SubModeTHRBX2         SubMode = "THRBX2"         //
	SubModeTHRBX4         SubMode = "THRBX4"         //
	SubModeTHROB1         SubMode = "THROB1"         //
	SubModeTHROB2         SubMode = "THROB2"         //
	SubModeTHROB4         SubMode = "THROB4"         //
	SubModeUSB            SubMode = "USB"            // Amplitude modulated voice telephony, upper-sideband, suppressed-carrier
	SubModeVARA_FM_1200   SubMode = "VARA FM 1200"   // Channel adaptive high-speed modem for FM transceivers
	SubModeVARA_FM_9600   SubMode = "VARA FM 9600"   // Channel adaptive high-speed modem for FM transceivers
	SubModeVARA_HF        SubMode = "VARA HF"        // Channel adaptive high-speed modem for HF
	SubModeVARA_SATELLITE SubMode = "VARA SATELLITE" // Channel adaptive high-speed modem for satellite operations
)

/*
var SubModeMap = map[submode.SubMode]spec.SubmodeSpec{"8PSK1000":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"8PSK1000", Mode:"PSK", Description:""}, "8PSK1000F":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"8PSK1000F", Mode:"PSK", Description:""}, "8PSK1200F":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"8PSK1200F", Mode:"PSK", Description:""}, "8PSK125":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"8PSK125", Mode:"PSK", Description:""}, "8PSK125F":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"8PSK125F", Mode:"PSK", Description:""}, "8PSK125FL":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"8PSK125FL", Mode:"PSK", Description:""}, "8PSK250":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"8PSK250", Mode:"PSK", Description:""}, "8PSK250F":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"8PSK250F", Mode:"PSK", Description:""}, "8PSK250FL":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"8PSK250FL", Mode:"PSK", Description:""}, "8PSK500":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"8PSK500", Mode:"PSK", Description:""}, "8PSK500F":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"8PSK500F", Mode:"PSK", Description:""}, "AMTORFEC":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"AMTORFEC", Mode:"TOR", Description:""}, "ASCI":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"ASCI", Mode:"RTTY", Description:""}, "C4FM":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"C4FM", Mode:"DIGITALVOICE", Description:"C4FM 4-level FSK See the Propagation_Mode enumeration section for examples of representing C4FM voice transmissions."}, "CHIP128":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"CHIP128", Mode:"CHIP", Description:""}, "CHIP64":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"CHIP64", Mode:"CHIP", Description:""}, "DMR":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"DMR", Mode:"DIGITALVOICE", Description:"Digital Mobile Radio See the Propagation_Mode enumeration section for examples of representing DMR voice transmissions."}, "DOM-M":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"DOM-M", Mode:"DOMINO", Description:""}, "DOM11":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"DOM11", Mode:"DOMINO", Description:""}, "DOM16":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"DOM16", Mode:"DOMINO", Description:""}, "DOM22":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"DOM22", Mode:"DOMINO", Description:""}, "DOM4":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"DOM4", Mode:"DOMINO", Description:""}, "DOM44":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"DOM44", Mode:"DOMINO", Description:""}, "DOM5":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"DOM5", Mode:"DOMINO", Description:""}, "DOM8":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"DOM8", Mode:"DOMINO", Description:""}, "DOM88":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"DOM88", Mode:"DOMINO", Description:""}, "DOMINOEX":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"DOMINOEX", Mode:"DOMINO", Description:""}, "DOMINOF":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"DOMINOF", Mode:"DOMINO", Description:""}, "DSTAR":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"DSTAR", Mode:"DIGITALVOICE", Description:"Digital Smart Technologies for Amateur Radio See the Propagation_Mode enumeration section for examples of representing DSTAR voice transmissions."}, "FMHELL":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"FMHELL", Mode:"HELL", Description:""}, "FREEDV":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"FREEDV", Mode:"DIGITALVOICE", Description:"Digital voice mode for HF radio implemented with open source"}, "FSK31":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"FSK31", Mode:"PSK", Description:""}, "FSKH105":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"FSKH105", Mode:"HELL", Description:""}, "FSKH245":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"FSKH245", Mode:"HELL", Description:""}, "FSKHELL":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"FSKHELL", Mode:"HELL", Description:""}, "FSQCALL":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"FSQCALL", Mode:"MFSK", Description:"FSQCall protocol used with FSQ (Fast Simple QSO) transmission mode"}, "FST4":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"FST4", Mode:"MFSK", Description:"This is a digital mode supported by the WSJT-X software"}, "FST4W":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"FST4W", Mode:"MFSK", Description:"This is a digital mode supported by the WSJT-X software that is for quasi-beacon transmissions of WSPR-style messages"}, "FT4":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"FT4", Mode:"MFSK", Description:"FT4 is a digital mode designed specifically for radio contesting"}, "GTOR":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"GTOR", Mode:"TOR", Description:""}, "HELL80":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"HELL80", Mode:"HELL", Description:""}, "HELLX5":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"HELLX5", Mode:"HELL", Description:""}, "HELLX9":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"HELLX9", Mode:"HELL", Description:""}, "HFSK":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"HFSK", Mode:"HELL", Description:""}, "ISCAT-A":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"ISCAT-A", Mode:"ISCAT", Description:""}, "ISCAT-B":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"ISCAT-B", Mode:"ISCAT", Description:""}, "JS8":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"JS8", Mode:"MFSK", Description:"Jordan Sherer designed 8-FSK modulation"}, "JT4A":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"JT4A", Mode:"JT4", Description:""}, "JT4B":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"JT4B", Mode:"JT4", Description:""}, "JT4C":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"JT4C", Mode:"JT4", Description:""}, "JT4D":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"JT4D", Mode:"JT4", Description:""}, "JT4E":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"JT4E", Mode:"JT4", Description:""}, "JT4F":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"JT4F", Mode:"JT4", Description:""}, "JT4G":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"JT4G", Mode:"JT4", Description:""}, "JT65A":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"JT65A", Mode:"JT65", Description:""}, "JT65B":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"JT65B", Mode:"JT65", Description:""}, "JT65B2":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"JT65B2", Mode:"JT65", Description:""}, "JT65C":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"JT65C", Mode:"JT65", Description:""}, "JT65C2":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"JT65C2", Mode:"JT65", Description:""}, "JT9-1":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"JT9-1", Mode:"JT9", Description:""}, "JT9-10":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"JT9-10", Mode:"JT9", Description:""}, "JT9-2":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"JT9-2", Mode:"JT9", Description:""}, "JT9-30":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"JT9-30", Mode:"JT9", Description:""}, "JT9-5":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"JT9-5", Mode:"JT9", Description:""}, "JT9A":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"JT9A", Mode:"JT9", Description:""}, "JT9B":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"JT9B", Mode:"JT9", Description:""}, "JT9C":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"JT9C", Mode:"JT9", Description:""}, "JT9D":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"JT9D", Mode:"JT9", Description:""}, "JT9E":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"JT9E", Mode:"JT9", Description:""}, "JT9E FAST":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"JT9E FAST", Mode:"JT9", Description:""}, "JT9F":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"JT9F", Mode:"JT9", Description:""}, "JT9F FAST":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"JT9F FAST", Mode:"JT9", Description:""}, "JT9G":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"JT9G", Mode:"JT9", Description:""}, "JT9G FAST":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"JT9G FAST", Mode:"JT9", Description:""}, "JT9H":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"JT9H", Mode:"JT9", Description:""}, "JT9H FAST":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"JT9H FAST", Mode:"JT9", Description:""}, "JTMS":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"JTMS", Mode:"MFSK", Description:""}, "LSB":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"LSB", Mode:"SSB", Description:"Amplitude modulated voice telephony, lower-sideband, suppressed-carrier"}, "M17":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"M17", Mode:"DIGITALVOICE", Description:"Digital radio protocol using the Codec 2 voice encoder"}, "MFSK11":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"MFSK11", Mode:"MFSK", Description:""}, "MFSK128":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"MFSK128", Mode:"MFSK", Description:""}, "MFSK128L":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"MFSK128L", Mode:"MFSK", Description:""}, "MFSK16":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"MFSK16", Mode:"MFSK", Description:""}, "MFSK22":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"MFSK22", Mode:"MFSK", Description:""}, "MFSK31":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"MFSK31", Mode:"MFSK", Description:""}, "MFSK32":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"MFSK32", Mode:"MFSK", Description:""}, "MFSK4":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"MFSK4", Mode:"MFSK", Description:""}, "MFSK64":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"MFSK64", Mode:"MFSK", Description:""}, "MFSK64L":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"MFSK64L", Mode:"MFSK", Description:""}, "MFSK8":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"MFSK8", Mode:"MFSK", Description:""}, "NAVTEX":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"NAVTEX", Mode:"TOR", Description:""}, "OLIVIA 16/1000":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"OLIVIA 16/1000", Mode:"OLIVIA", Description:""}, "OLIVIA 16/500":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"OLIVIA 16/500", Mode:"OLIVIA", Description:""}, "OLIVIA 32/1000":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"OLIVIA 32/1000", Mode:"OLIVIA", Description:""}, "OLIVIA 4/125":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"OLIVIA 4/125", Mode:"OLIVIA", Description:""}, "OLIVIA 4/250":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"OLIVIA 4/250", Mode:"OLIVIA", Description:""}, "OLIVIA 8/250":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"OLIVIA 8/250", Mode:"OLIVIA", Description:""}, "OLIVIA 8/500":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"OLIVIA 8/500", Mode:"OLIVIA", Description:""}, "OPERA-BEACON":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"OPERA-BEACON", Mode:"OPERA", Description:""}, "OPERA-QSO":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"OPERA-QSO", Mode:"OPERA", Description:""}, "PAC2":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"PAC2", Mode:"PAC", Description:""}, "PAC3":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"PAC3", Mode:"PAC", Description:""}, "PAC4":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"PAC4", Mode:"PAC", Description:""}, "PAX2":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"PAX2", Mode:"PAX", Description:""}, "PCW":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"PCW", Mode:"CW", Description:"Coherent CW"}, "PSK10":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"PSK10", Mode:"PSK", Description:""}, "PSK1000":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"PSK1000", Mode:"PSK", Description:""}, "PSK1000RC2":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"PSK1000RC2", Mode:"PSK", Description:""}, "PSK125":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"PSK125", Mode:"PSK", Description:""}, "PSK125RC10":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"PSK125RC10", Mode:"PSK", Description:""}, "PSK125RC12":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"PSK125RC12", Mode:"PSK", Description:""}, "PSK125RC16":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"PSK125RC16", Mode:"PSK", Description:""}, "PSK125RC4":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"PSK125RC4", Mode:"PSK", Description:""}, "PSK125RC5":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"PSK125RC5", Mode:"PSK", Description:""}, "PSK250":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"PSK250", Mode:"PSK", Description:""}, "PSK250RC2":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"PSK250RC2", Mode:"PSK", Description:""}, "PSK250RC3":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"PSK250RC3", Mode:"PSK", Description:""}, "PSK250RC5":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"PSK250RC5", Mode:"PSK", Description:""}, "PSK250RC6":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"PSK250RC6", Mode:"PSK", Description:""}, "PSK250RC7":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"PSK250RC7", Mode:"PSK", Description:""}, "PSK31":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"PSK31", Mode:"PSK", Description:""}, "PSK500":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"PSK500", Mode:"PSK", Description:""}, "PSK500RC2":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"PSK500RC2", Mode:"PSK", Description:""}, "PSK500RC3":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"PSK500RC3", Mode:"PSK", Description:""}, "PSK500RC4":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"PSK500RC4", Mode:"PSK", Description:""}, "PSK63":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"PSK63", Mode:"PSK", Description:""}, "PSK63F":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"PSK63F", Mode:"PSK", Description:""}, "PSK63RC10":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"PSK63RC10", Mode:"PSK", Description:""}, "PSK63RC20":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"PSK63RC20", Mode:"PSK", Description:""}, "PSK63RC32":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"PSK63RC32", Mode:"PSK", Description:""}, "PSK63RC4":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"PSK63RC4", Mode:"PSK", Description:""}, "PSK63RC5":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"PSK63RC5", Mode:"PSK", Description:""}, "PSK800RC2":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"PSK800RC2", Mode:"PSK", Description:""}, "PSKAM10":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"PSKAM10", Mode:"PSK", Description:""}, "PSKAM31":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"PSKAM31", Mode:"PSK", Description:""}, "PSKAM50":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"PSKAM50", Mode:"PSK", Description:""}, "PSKFEC31":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"PSKFEC31", Mode:"PSK", Description:""}, "PSKHELL":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"PSKHELL", Mode:"HELL", Description:""}, "Q65":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"Q65", Mode:"MFSK", Description:""}, "QPSK125":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"QPSK125", Mode:"PSK", Description:""}, "QPSK250":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"QPSK250", Mode:"PSK", Description:""}, "QPSK31":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"QPSK31", Mode:"PSK", Description:""}, "QPSK500":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"QPSK500", Mode:"PSK", Description:""}, "QPSK63":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"QPSK63", Mode:"PSK", Description:""}, "QRA64A":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"QRA64A", Mode:"QRA64", Description:""}, "QRA64B":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"QRA64B", Mode:"QRA64", Description:""}, "QRA64C":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"QRA64C", Mode:"QRA64", Description:""}, "QRA64D":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"QRA64D", Mode:"QRA64", Description:""}, "QRA64E":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"QRA64E", Mode:"QRA64", Description:""}, "ROS-EME":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"ROS-EME", Mode:"ROS", Description:""}, "ROS-HF":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"ROS-HF", Mode:"ROS", Description:""}, "ROS-MF":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"ROS-MF", Mode:"ROS", Description:""}, "SCAMP_FAST":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"SCAMP_FAST", Mode:"FSK", Description:"SCAMP fast FSK"}, "SCAMP_OO":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"SCAMP_OO", Mode:"MTONE", Description:"SCAMP single modulated tone on/off keying"}, "SCAMP_OO_SLW":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"SCAMP_OO_SLW", Mode:"MTONE", Description:"SCAMP single modulated tone on/off slow keying"}, "SCAMP_SLOW":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"SCAMP_SLOW", Mode:"FSK", Description:"SCAMP slow FSK"}, "SCAMP_VSLOW":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"SCAMP_VSLOW", Mode:"FSK", Description:"SCAMP very slow FSK"}, "SIM31":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"SIM31", Mode:"PSK", Description:""}, "SITORB":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"SITORB", Mode:"TOR", Description:""}, "SLOWHELL":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"SLOWHELL", Mode:"HELL", Description:""}, "THOR-M":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"THOR-M", Mode:"THOR", Description:""}, "THOR100":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"THOR100", Mode:"THOR", Description:""}, "THOR11":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"THOR11", Mode:"THOR", Description:""}, "THOR16":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"THOR16", Mode:"THOR", Description:""}, "THOR22":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"THOR22", Mode:"THOR", Description:""}, "THOR25X4":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"THOR25X4", Mode:"THOR", Description:""}, "THOR4":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"THOR4", Mode:"THOR", Description:""}, "THOR5":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"THOR5", Mode:"THOR", Description:""}, "THOR50X1":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"THOR50X1", Mode:"THOR", Description:""}, "THOR50X2":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"THOR50X2", Mode:"THOR", Description:""}, "THOR8":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"THOR8", Mode:"THOR", Description:""}, "THRBX":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"THRBX", Mode:"THRB", Description:""}, "THRBX1":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"THRBX1", Mode:"THRB", Description:""}, "THRBX2":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"THRBX2", Mode:"THRB", Description:""}, "THRBX4":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"THRBX4", Mode:"THRB", Description:""}, "THROB1":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"THROB1", Mode:"THRB", Description:""}, "THROB2":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"THROB2", Mode:"THRB", Description:""}, "THROB4":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"THROB4", Mode:"THRB", Description:""}, "USB":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"USB", Mode:"SSB", Description:"Amplitude modulated voice telephony, upper-sideband, suppressed-carrier"}, "VARA FM 1200":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"VARA FM 1200", Mode:"DYNAMIC", Description:"Channel adaptive high-speed modem for FM transceivers"}, "VARA FM 9600":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"VARA FM 9600", Mode:"DYNAMIC", Description:"Channel adaptive high-speed modem for FM transceivers"}, "VARA HF":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"VARA HF", Mode:"DYNAMIC", Description:"Channel adaptive high-speed modem for HF"}, "VARA SATELLITE":spec.SubmodeSpec{EnumerationName:"Submode", IsImportOnly:false, Comments:"", Id:"VARA SATELLITE", Mode:"DYNAMIC", Description:"Channel adaptive high-speed modem for satellite operations"}}
*/
