// DO NOT EDIT
// Code generated by ./cmd/codegen/codegen

// This file contains CURRENTLY valid constants.
// It is not a full list of all possible historic and/or future values.

package adifield

var (
	ADIF_VER                   Field = "ADIF_VER"                   // ADIF_VER                       = Header: identifies the version of ADIF used in this file in the format X.Y.Z where X is an integer designating the ADIF epoch Y is an integer between 0 and 9 designating the major version Z is an integer between 0 and 9 designating the minor version
	CREATED_TIMESTAMP          Field = "CREATED_TIMESTAMP"          // CREATED_TIMESTAMP              = Header: identifies the UTC date and time that the file was created in the format of 15 characters YYYYMMDD HHMMSS where YYYYMMDD is a Date data type HHMMSS is a 6 character Time data type
	PROGRAMID                  Field = "PROGRAMID"                  // PROGRAMID                      = Header: identifies the name of the logger, converter, or utility that created or processed this ADIF file
	PROGRAMVERSION             Field = "PROGRAMVERSION"             // PROGRAMVERSION                 = Header: identifies the version of the logger, converter, or utility that created or processed this ADIF file
	USERDEF1                   Field = "USERDEF1"                   // USERDEF1                       = Header: specifies the name and optional enumeration or range of the nth user-defined field, where n is a positive integer The name of a user-defined field may not be an ADIF Field name contain a comma a colon an open-angle-bracket or close-angle-bracket character an open-curly-bracket or close-curly-bracket character begin or end with a space character
	ADDRESS                    Field = "ADDRESS"                    // ADDRESS                        = Record: the contacted station's complete mailing address: full name, street address, city, postal code, and country
	ADDRESS_INTL               Field = "ADDRESS_INTL"               // ADDRESS_INTL                   = Record: the contacted station's complete mailing address: full name, street address, city, postal code, and country
	AGE                        Field = "AGE"                        // AGE                            = Record: the contacted station's operator's age in years in the range 0 to 120 (inclusive)
	ALTITUDE                   Field = "ALTITUDE"                   // ALTITUDE                       = Record: the height of the contacted station in meters relative to Mean Sea Level (MSL). For example 1.5 km is <ALTITUDE:4>1500 and 10.5 m is <ALTITUDE:4>10.5
	ANT_AZ                     Field = "ANT_AZ"                     // ANT_AZ                         = Record: the logging station's antenna azimuth, in degrees with a value between 0 to 360 (inclusive). Values outside this range are import-only and must be normalized for export (e.g. 370 is exported as 10). True north is 0 degrees with values increasing in a clockwise direction.
	ANT_EL                     Field = "ANT_EL"                     // ANT_EL                         = Record: the logging station's antenna elevation, in degrees with a value between -90 to 90 (inclusive). Values outside this range are import-only and must be normalized for export (e.g. 100 is exported as 80). The horizon is 0 degrees with values increasing as the angle moves in an upward direction.
	ANT_PATH                   Field = "ANT_PATH"                   // ANT_PATH                       = Record: the signal path
	ARRL_SECT                  Field = "ARRL_SECT"                  // ARRL_SECT                      = Record: the contacted station's ARRL section
	AWARD_SUBMITTED            Field = "AWARD_SUBMITTED"            // AWARD_SUBMITTED                = Record: the list of awards submitted to a sponsor. note that this field might not be used in a QSO record. It might be used to convey information about a user's "Award Account" between an award sponsor and the user. For example, AA6YQ might submit a request for awards by sending the following: <CALL:5>AA6YQ <AWARD_SUBMITTED:64>ADIF_CENTURY_BASIC,ADIF_CENTURY_SILVER,ADIF_SPECTRUM_100-160m
	AWARD_GRANTED              Field = "AWARD_GRANTED"              // AWARD_GRANTED                  = Record: the list of awards granted by a sponsor. note that this field might not be used in a QSO record. It might be used to convey information about a user's "Award Account" between an award sponsor and the user. For example, in response to a request "send me a list of the awards granted to AA6YQ", this might be received: <CALL:5>AA6YQ <AWARD_GRANTED:64>ADIF_CENTURY_BASIC,ADIF_CENTURY_SILVER,ADIF_SPECTRUM_100-160m
	A_INDEX                    Field = "A_INDEX"                    // A_INDEX                        = Record: the geomagnetic A index at the time of the QSO in the range 0 to 400 (inclusive)
	BAND                       Field = "BAND"                       // BAND                           = Record: QSO Band
	BAND_RX                    Field = "BAND_RX"                    // BAND_RX                        = Record: in a split frequency QSO, the logging station's receiving band
	CALL                       Field = "CALL"                       // CALL                           = Record: the contacted station's callsign
	CHECK                      Field = "CHECK"                      // CHECK                          = Record: contest check (e.g. for ARRL Sweepstakes)
	CLASS                      Field = "CLASS"                      // CLASS                          = Record: contest class (e.g. for ARRL Field Day)
	CLUBLOG_QSO_UPLOAD_DATE    Field = "CLUBLOG_QSO_UPLOAD_DATE"    // CLUBLOG_QSO_UPLOAD_DATE        = Record: the date the QSO was last uploaded to the Club Log online service
	CLUBLOG_QSO_UPLOAD_STATUS  Field = "CLUBLOG_QSO_UPLOAD_STATUS"  // CLUBLOG_QSO_UPLOAD_STATUS      = Record: the upload status of the QSO on the Club Log online service
	CNTY                       Field = "CNTY"                       // CNTY                           = Record: the contacted station's Secondary Administrative Subdivision (e.g. US county, JA Gun), in the specified format
	CNTY_ALT                   Field = "CNTY_ALT"                   // CNTY_ALT                       = Record: a semicolon (;) delimited, unordered list of Secondary Administrative Subdivision Alt codes for the contacted station See the Data Type for details.
	COMMENT                    Field = "COMMENT"                    // COMMENT                        = Record: comment field for QSO for a message to be incorporated in a paper or electronic QSL for the contacted station's operator, use the QSLMSG field recommended use: information of interest to the contacted station's operator
	COMMENT_INTL               Field = "COMMENT_INTL"               // COMMENT_INTL                   = Record: comment field for QSO for a message to be incorporated in a paper or electronic QSL for the contacted station's operator, use the QSLMSG_INTL field recommended use: information of interest to the contacted station's operator
	CONT                       Field = "CONT"                       // CONT                           = Record: the contacted station's Continent
	CONTACTED_OP               Field = "CONTACTED_OP"               // CONTACTED_OP                   = Record: the callsign of the individual operating the contacted station
	CONTEST_ID                 Field = "CONTEST_ID"                 // CONTEST_ID                     = Record: QSO Contest Identifier use enumeration values for interoperability
	COUNTRY                    Field = "COUNTRY"                    // COUNTRY                        = Record: the contacted station's DXCC entity name
	COUNTRY_INTL               Field = "COUNTRY_INTL"               // COUNTRY_INTL                   = Record: the contacted station's DXCC entity name
	CQZ                        Field = "CQZ"                        // CQZ                            = Record: the contacted station's CQ Zone in the range 1 to 40 (inclusive)
	CREDIT_SUBMITTED           Field = "CREDIT_SUBMITTED"           // CREDIT_SUBMITTED               = Record: the list of credits sought for this QSO Use of data type AwardList and enumeration Award are import-only
	CREDIT_GRANTED             Field = "CREDIT_GRANTED"             // CREDIT_GRANTED                 = Record: the list of credits granted to this QSO Use of data type AwardList and enumeration Award are import-only
	DARC_DOK                   Field = "DARC_DOK"                   // DARC_DOK                       = Record: the contacted station's DARC DOK (District Location Code) A DOK comprises letters and numbers, e.g. <DARC_DOK:3>A01
	DCL_QSLRDATE               Field = "DCL_QSLRDATE"               // DCL_QSLRDATE                   = Record: date QSL received from DCL (only valid if DCL_QSL_RCVD is Y, I, or V)(V import-only)
	DCL_QSLSDATE               Field = "DCL_QSLSDATE"               // DCL_QSLSDATE                   = Record: date QSL sent to DCL (only valid if DCL_QSL_SENT is Y, Q, or I)
	DCL_QSL_RCVD               Field = "DCL_QSL_RCVD"               // DCL_QSL_RCVD                   = Record: DCL QSL received status Default Value: N
	DCL_QSL_SENT               Field = "DCL_QSL_SENT"               // DCL_QSL_SENT                   = Record: DCL QSL sent status Default Value: N
	DISTANCE                   Field = "DISTANCE"                   // DISTANCE                       = Record: the distance between the logging station and the contacted station in kilometers via the specified signal path with a value greater than or equal to 0
	DXCC                       Field = "DXCC"                       // DXCC                           = Record: the contacted station's DXCC Entity Code <DXCC:1>0 means that the contacted station is known not to be within a DXCC entity.
	EMAIL                      Field = "EMAIL"                      // EMAIL                          = Record: the contacted station's email address
	EQ_CALL                    Field = "EQ_CALL"                    // EQ_CALL                        = Record: the contacted station's owner's callsign
	EQSL_QSLRDATE              Field = "EQSL_QSLRDATE"              // EQSL_QSLRDATE                  = Record: date QSL received from eQSL.cc (only valid if EQSL_QSL_RCVD is Y, I, or V)(V import-only)
	EQSL_QSLSDATE              Field = "EQSL_QSLSDATE"              // EQSL_QSLSDATE                  = Record: date QSL sent to eQSL.cc (only valid if EQSL_QSL_SENT is Y, Q, or I)
	EQSL_QSL_RCVD              Field = "EQSL_QSL_RCVD"              // EQSL_QSL_RCVD                  = Record: eQSL.cc QSL received status instead of V (import-only) use <CREDIT_GRANTED:42>CQWAZ:eqsl,CQWAZ_BAND:eqsl,CQWAZ_MODE:eqsl Default Value: N
	EQSL_QSL_SENT              Field = "EQSL_QSL_SENT"              // EQSL_QSL_SENT                  = Record: eQSL.cc QSL sent status Default Value: N
	FISTS                      Field = "FISTS"                      // FISTS                          = Record: the contacted station's FISTS CW Club member number with a value greater than 0.
	FISTS_CC                   Field = "FISTS_CC"                   // FISTS_CC                       = Record: the contacted station's FISTS CW Club Century Certificate (CC) number with a value greater than 0.
	FORCE_INIT                 Field = "FORCE_INIT"                 // FORCE_INIT                     = Record: new EME "initial"
	FREQ                       Field = "FREQ"                       // FREQ                           = Record: QSO frequency in Megahertz
	FREQ_RX                    Field = "FREQ_RX"                    // FREQ_RX                        = Record: in a split frequency QSO, the logging station's receiving frequency in Megahertz
	GRIDSQUARE                 Field = "GRIDSQUARE"                 // GRIDSQUARE                     = Record: the contacted station's 2-character, 4-character, 6-character, or 8-character Maidenhead Grid Square For 10 or 12 character locators, store the first 8 characters in GRIDSQUARE and the additional 2 or 4 characters in the GRIDSQUARE_EXT field
	GRIDSQUARE_EXT             Field = "GRIDSQUARE_EXT"             // GRIDSQUARE_EXT                 = Record: for a contacted station's 10-character Maidenhead locator, supplements the GRIDSQUARE field by containing characters 9 and 10. For a contacted station's 12-character Maidenhead locator, supplements the GRIDSQUARE field by containing characters 9, 10, 11 and 12. Characters 9 and 10 are case-insensitive ASCII letters in the range A-X. Characters 11 and 12 are Digits in the range 0 to 9. On export, the field length must be 2 or 4. On import, if the field length is greater than 4, the additional characters must be ignored. Example of exporting the 10-character locator FN01MH42BQ: <GRIDSQUARE:8>FN01MH42 <GRIDSQUARE_EXT:2>BQ
	HAMLOGEU_QSO_UPLOAD_DATE   Field = "HAMLOGEU_QSO_UPLOAD_DATE"   // HAMLOGEU_QSO_UPLOAD_DATE       = Record: the date the QSO was last uploaded to the HAMLOG.EU online service
	HAMLOGEU_QSO_UPLOAD_STATUS Field = "HAMLOGEU_QSO_UPLOAD_STATUS" // HAMLOGEU_QSO_UPLOAD_STATUS     = Record: the upload status of the QSO on the HAMLOG.EU online service
	HAMQTH_QSO_UPLOAD_DATE     Field = "HAMQTH_QSO_UPLOAD_DATE"     // HAMQTH_QSO_UPLOAD_DATE         = Record: the date the QSO was last uploaded to the HamQTH.com online service
	HAMQTH_QSO_UPLOAD_STATUS   Field = "HAMQTH_QSO_UPLOAD_STATUS"   // HAMQTH_QSO_UPLOAD_STATUS       = Record: the upload status of the QSO on the HamQTH.com online service
	HRDLOG_QSO_UPLOAD_DATE     Field = "HRDLOG_QSO_UPLOAD_DATE"     // HRDLOG_QSO_UPLOAD_DATE         = Record: the date the QSO was last uploaded to the HRDLog.net online service
	HRDLOG_QSO_UPLOAD_STATUS   Field = "HRDLOG_QSO_UPLOAD_STATUS"   // HRDLOG_QSO_UPLOAD_STATUS       = Record: the upload status of the QSO on the HRDLog.net online service
	IOTA                       Field = "IOTA"                       // IOTA                           = Record: the contacted station's IOTA designator, in format CC-XXX, where CC is a member of the Continent enumeration XXX is the island group designator, where 1 <= XXX <= 999 [use leading zeroes]
	IOTA_ISLAND_ID             Field = "IOTA_ISLAND_ID"             // IOTA_ISLAND_ID                 = Record: the contacted station's IOTA Island Identifier, an 8-digit integer in the range 1 to 99999999 [leading zeroes optional]
	ITUZ                       Field = "ITUZ"                       // ITUZ                           = Record: the contacted station's ITU zone in the range 1 to 90 (inclusive)
	K_INDEX                    Field = "K_INDEX"                    // K_INDEX                        = Record: the geomagnetic K index at the time of the QSO in the range 0 to 9 (inclusive)
	LAT                        Field = "LAT"                        // LAT                            = Record: the contacted station's latitude
	LON                        Field = "LON"                        // LON                            = Record: the contacted station's longitude
	LOTW_QSLRDATE              Field = "LOTW_QSLRDATE"              // LOTW_QSLRDATE                  = Record: date QSL received from ARRL Logbook of the World (only valid if LOTW_QSL_RCVD is Y, I, or V)(V import-only)
	LOTW_QSLSDATE              Field = "LOTW_QSLSDATE"              // LOTW_QSLSDATE                  = Record: date QSL sent to ARRL Logbook of the World (only valid if LOTW_QSL_SENT is Y, Q, or I)
	LOTW_QSL_RCVD              Field = "LOTW_QSL_RCVD"              // LOTW_QSL_RCVD                  = Record: ARRL Logbook of the World QSL received status instead of V (import-only) use <CREDIT_GRANTED:39>DXCC:lotw,DXCC_BAND:lotw,DXCC_MODE:lotw Default Value: N
	LOTW_QSL_SENT              Field = "LOTW_QSL_SENT"              // LOTW_QSL_SENT                  = Record: ARRL Logbook of the World QSL sent status Default Value: N
	MAX_BURSTS                 Field = "MAX_BURSTS"                 // MAX_BURSTS                     = Record: maximum length of meteor scatter bursts heard by the logging station, in seconds with a value greater than or equal to 0
	MODE                       Field = "MODE"                       // MODE                           = Record: QSO Mode
	MORSE_KEY_INFO             Field = "MORSE_KEY_INFO"             // MORSE_KEY_INFO                 = Record: details of the contacted station's Morse key (e.g. make, model, etc). Example: <MORSE_KEY_INFO:16>Begali Sculpture
	MORSE_KEY_TYPE             Field = "MORSE_KEY_TYPE"             // MORSE_KEY_TYPE                 = Record: the contacted station's Morse key type (e.g. straight key, bug, etc). Example for a dual-lever paddle: <MORSE_KEY_TYPE:3>DLP
	MS_SHOWER                  Field = "MS_SHOWER"                  // MS_SHOWER                      = Record: For Meteor Scatter QSOs, the name of the meteor shower in progress
	MY_ALTITUDE                Field = "MY_ALTITUDE"                // MY_ALTITUDE                    = Record: the height of the logging station in meters relative to Mean Sea Level (MSL). For example 1.5 km is <MY_ALTITUDE:4>1500 and 10.5 m is <MY_ALTITUDE:4>10.5
	MY_ANTENNA                 Field = "MY_ANTENNA"                 // MY_ANTENNA                     = Record: the logging station's antenna
	MY_ANTENNA_INTL            Field = "MY_ANTENNA_INTL"            // MY_ANTENNA_INTL                = Record: the logging station's antenna
	MY_ARRL_SECT               Field = "MY_ARRL_SECT"               // MY_ARRL_SECT                   = Record: the logging station's ARRL section
	MY_CITY                    Field = "MY_CITY"                    // MY_CITY                        = Record: the logging station's city
	MY_CITY_INTL               Field = "MY_CITY_INTL"               // MY_CITY_INTL                   = Record: the logging station's city
	MY_CNTY                    Field = "MY_CNTY"                    // MY_CNTY                        = Record: the logging station's Secondary Administrative Subdivision (e.g. US county, JA Gun), in the specified format
	MY_CNTY_ALT                Field = "MY_CNTY_ALT"                // MY_CNTY_ALT                    = Record: a semicolon (;) delimited, unordered list of Secondary Administrative Subdivision Alt codes for the logging station See the Data Type for details.
	MY_COUNTRY                 Field = "MY_COUNTRY"                 // MY_COUNTRY                     = Record: the logging station's DXCC entity name
	MY_COUNTRY_INTL            Field = "MY_COUNTRY_INTL"            // MY_COUNTRY_INTL                = Record: the logging station's DXCC entity name
	MY_CQ_ZONE                 Field = "MY_CQ_ZONE"                 // MY_CQ_ZONE                     = Record: the logging station's CQ Zone in the range 1 to 40 (inclusive)
	MY_DARC_DOK                Field = "MY_DARC_DOK"                // MY_DARC_DOK                    = Record: the logging station's DARC DOK (District Location Code) A DOK comprises letters and numbers, e.g. <MY_DARC_DOK:3>A01
	MY_DXCC                    Field = "MY_DXCC"                    // MY_DXCC                        = Record: the logging station's DXCC Entity Code <MY_DXCC:1>0 means that the logging station is known not to be within a DXCC entity.
	MY_FISTS                   Field = "MY_FISTS"                   // MY_FISTS                       = Record: the logging station's FISTS CW Club member number with a value greater than 0.
	MY_GRIDSQUARE              Field = "MY_GRIDSQUARE"              // MY_GRIDSQUARE                  = Record: the logging station's 2-character, 4-character, 6-character, or 8-character Maidenhead Grid Square For 10 or 12 character locators, store the first 8 characters in MY_GRIDSQUARE and the additional 2 or 4 characters in the MY_GRIDSQUARE_EXT field
	MY_GRIDSQUARE_EXT          Field = "MY_GRIDSQUARE_EXT"          // MY_GRIDSQUARE_EXT              = Record: for a logging station's 10-character Maidenhead locator, supplements the MY_GRIDSQUARE field by containing characters 9 and 10. For a logging station's 12-character Maidenhead locator, supplements the MY_GRIDSQUARE field by containing characters 9, 10, 11 and 12. Characters 9 and 10 are case-insensitive ASCII letters in the range A-X. Characters 11 and 12 are Digits in the range 0 to 9. On export, the field length must be 2 or 4. On import, if the field length is greater than 4, the additional characters must be ignored. Example of exporting the 10-character locator FN01MH42BQ: <MY_GRIDSQUARE:8>FN01MH42 <MY_GRIDSQUARE_EXT:2>BQ
	MY_IOTA                    Field = "MY_IOTA"                    // MY_IOTA                        = Record: the logging station's IOTA designator, in format CC-XXX, where CC is a member of the Continent enumeration XXX is the island group designator, where 1 <= XXX <= 999 [use leading zeroes]
	MY_IOTA_ISLAND_ID          Field = "MY_IOTA_ISLAND_ID"          // MY_IOTA_ISLAND_ID              = Record: the logging station's IOTA Island Identifier, an 8-digit integer in the range 1 to 99999999 [leading zeroes optional]
	MY_ITU_ZONE                Field = "MY_ITU_ZONE"                // MY_ITU_ZONE                    = Record: the logging station's ITU zone in the range 1 to 90 (inclusive)
	MY_LAT                     Field = "MY_LAT"                     // MY_LAT                         = Record: the logging station's latitude
	MY_LON                     Field = "MY_LON"                     // MY_LON                         = Record: the logging station's longitude
	MY_MORSE_KEY_INFO          Field = "MY_MORSE_KEY_INFO"          // MY_MORSE_KEY_INFO              = Record: details of the logging station's Morse key (e.g. make, model, etc). Example: <MY_MORSE_KEY_INFO:16>Begali Sculpture
	MY_MORSE_KEY_TYPE          Field = "MY_MORSE_KEY_TYPE"          // MY_MORSE_KEY_TYPE              = Record: the logging station's Morse key type (e.g. straight key, bug, etc). Example for a dual-lever paddle: <MY_MORSE_KEY_TYPE:3>DLP
	MY_NAME                    Field = "MY_NAME"                    // MY_NAME                        = Record: the logging operator's name
	MY_NAME_INTL               Field = "MY_NAME_INTL"               // MY_NAME_INTL                   = Record: the logging operator's name
	MY_POSTAL_CODE             Field = "MY_POSTAL_CODE"             // MY_POSTAL_CODE                 = Record: the logging station's postal code
	MY_POSTAL_CODE_INTL        Field = "MY_POSTAL_CODE_INTL"        // MY_POSTAL_CODE_INTL            = Record: the logging station's postal code
	MY_POTA_REF                Field = "MY_POTA_REF"                // MY_POTA_REF                    = Record: a comma-delimited list of one or more of the logging station's POTA (Parks on the Air) reference(s). Examples: <MY_POTA_REF:6>K-0059 <MY_POTA_REF:7>K-10000 <MY_POTA_REF:40>K-0817,K-4566,K-4576,K-4573,K-4578@US-WY
	MY_RIG                     Field = "MY_RIG"                     // MY_RIG                         = Record: description of the logging station's equipment
	MY_RIG_INTL                Field = "MY_RIG_INTL"                // MY_RIG_INTL                    = Record: description of the logging station's equipment
	MY_SIG                     Field = "MY_SIG"                     // MY_SIG                         = Record: special interest activity or event
	MY_SIG_INTL                Field = "MY_SIG_INTL"                // MY_SIG_INTL                    = Record: special interest activity or event
	MY_SIG_INFO                Field = "MY_SIG_INFO"                // MY_SIG_INFO                    = Record: special interest activity or event information
	MY_SIG_INFO_INTL           Field = "MY_SIG_INFO_INTL"           // MY_SIG_INFO_INTL               = Record: special interest activity or event information
	MY_SOTA_REF                Field = "MY_SOTA_REF"                // MY_SOTA_REF                    = Record: the logging station's International SOTA Reference.
	MY_STATE                   Field = "MY_STATE"                   // MY_STATE                       = Record: the code for the logging station's Primary Administrative Subdivision (e.g. US State, JA Island, VE Province)
	MY_STREET                  Field = "MY_STREET"                  // MY_STREET                      = Record: the logging station's street
	MY_STREET_INTL             Field = "MY_STREET_INTL"             // MY_STREET_INTL                 = Record: the logging station's street
	MY_USACA_COUNTIES          Field = "MY_USACA_COUNTIES"          // MY_USACA_COUNTIES              = Record: two US counties in the case where the logging station is located on a border between two counties, representing counties that the contacted station may claim for the CQ Magazine USA-CA award program. E.g. MA,Franklin:MA,Hampshire
	MY_VUCC_GRIDS              Field = "MY_VUCC_GRIDS"              // MY_VUCC_GRIDS                  = Record: two or four adjacent Maidenhead grid locators, each four or six characters long, representing the logging station's grid squares that the contacted station may claim for the ARRL VUCC award program. E.g. EN98,FM08,EM97,FM07
	MY_WWFF_REF                Field = "MY_WWFF_REF"                // MY_WWFF_REF                    = Record: the logging station's WWFF (World Wildlife Flora & Fauna) reference
	NAME                       Field = "NAME"                       // NAME                           = Record: the contacted station's operator's name
	NAME_INTL                  Field = "NAME_INTL"                  // NAME_INTL                      = Record: the contacted station's operator's name
	NOTES                      Field = "NOTES"                      // NOTES                          = Record: QSO notes recommended use: information of interest to the logging station's operator
	NOTES_INTL                 Field = "NOTES_INTL"                 // NOTES_INTL                     = Record: QSO notes recommended use: information of interest to the logging station's operator
	NR_BURSTS                  Field = "NR_BURSTS"                  // NR_BURSTS                      = Record: the number of meteor scatter bursts heard by the logging station with a value greater than or equal to 0
	NR_PINGS                   Field = "NR_PINGS"                   // NR_PINGS                       = Record: the number of meteor scatter pings heard by the logging station with a value greater than or equal to 0
	OPERATOR                   Field = "OPERATOR"                   // OPERATOR                       = Record: the logging operator's callsign if STATION_CALLSIGN is absent, OPERATOR shall be treated as both the logging station's callsign and the logging operator's callsign
	OWNER_CALLSIGN             Field = "OWNER_CALLSIGN"             // OWNER_CALLSIGN                 = Record: the callsign of the owner of the station used to log the contact (the callsign of the OPERATOR's host) if OWNER_CALLSIGN is absent, STATION_CALLSIGN shall be treated as both the logging station's callsign and the callsign of the owner of the station
	PFX                        Field = "PFX"                        // PFX                            = Record: the contacted station's WPX prefix
	POTA_REF                   Field = "POTA_REF"                   // POTA_REF                       = Record: a comma-delimited list of one or more of the contacted station's POTA (Parks on the Air) reference(s). Examples: <POTA_REF:6>K-5033 <POTA_REF:13>VE-5082@CA-AB <POTA_REF:40>K-0817,K-4566,K-4576,K-4573,K-4578@US-WY
	PRECEDENCE                 Field = "PRECEDENCE"                 // PRECEDENCE                     = Record: contest precedence (e.g. for ARRL Sweepstakes)
	PROP_MODE                  Field = "PROP_MODE"                  // PROP_MODE                      = Record: QSO propagation mode
	PUBLIC_KEY                 Field = "PUBLIC_KEY"                 // PUBLIC_KEY                     = Record: public encryption key
	QRZCOM_QSO_DOWNLOAD_DATE   Field = "QRZCOM_QSO_DOWNLOAD_DATE"   // QRZCOM_QSO_DOWNLOAD_DATE       = Record: date QSO downloaded from QRZ.COM logbook
	QRZCOM_QSO_DOWNLOAD_STATUS Field = "QRZCOM_QSO_DOWNLOAD_STATUS" // QRZCOM_QSO_DOWNLOAD_STATUS     = Record: QRZ.COM logbook QSO download status
	QRZCOM_QSO_UPLOAD_DATE     Field = "QRZCOM_QSO_UPLOAD_DATE"     // QRZCOM_QSO_UPLOAD_DATE         = Record: the date the QSO was last uploaded to the QRZ.COM online service
	QRZCOM_QSO_UPLOAD_STATUS   Field = "QRZCOM_QSO_UPLOAD_STATUS"   // QRZCOM_QSO_UPLOAD_STATUS       = Record: the upload status of the QSO on the QRZ.COM online service
	QSLMSG                     Field = "QSLMSG"                     // QSLMSG                         = Record: a message for the contacted station's operator to be incorporated in a paper or electronic QSL
	QSLMSG_INTL                Field = "QSLMSG_INTL"                // QSLMSG_INTL                    = Record: a message for the contacted station's operator to be incorporated in a paper or electronic QSL
	QSLMSG_RCVD                Field = "QSLMSG_RCVD"                // QSLMSG_RCVD                    = Record: a message addressed to the logging station's operator incorporated in a paper or electronic QSL
	QSLRDATE                   Field = "QSLRDATE"                   // QSLRDATE                       = Record: QSL received date (only valid if QSL_RCVD is Y, I, or V)(V import-only)
	QSLSDATE                   Field = "QSLSDATE"                   // QSLSDATE                       = Record: QSL sent date (only valid if QSL_SENT is Y, Q, or I)
	QSL_RCVD                   Field = "QSL_RCVD"                   // QSL_RCVD                       = Record: QSL received status instead of V (import-only) use <CREDIT_GRANTED:39>DXCC:card,DXCC_BAND:card,DXCC_MODE:card Default Value: N
	QSL_RCVD_VIA               Field = "QSL_RCVD_VIA"               // QSL_RCVD_VIA                   = Record: if QSL_RCVD is set to 'Y' or 'V', the means by which the QSL was received by the logging station; otherwise, the means by which the logging station requested or intends to request that the QSL be conveyed. (Note: 'V' is import-only) use of M (manager) is import-only
	QSL_SENT                   Field = "QSL_SENT"                   // QSL_SENT                       = Record: QSL sent status Default Value: N
	QSL_SENT_VIA               Field = "QSL_SENT_VIA"               // QSL_SENT_VIA                   = Record: if QSL_SENT is set to 'Y', the means by which the QSL was sent by the logging station; otherwise, the means by which the logging station intends to convey the QSL use of M (manager) is import-only
	QSL_VIA                    Field = "QSL_VIA"                    // QSL_VIA                        = Record: the contacted station's QSL route
	QSO_COMPLETE               Field = "QSO_COMPLETE"               // QSO_COMPLETE                   = Record: indicates whether the QSO was complete from the perspective of the logging station Y - yes N - no NIL - not heard ? - uncertain
	QSO_DATE                   Field = "QSO_DATE"                   // QSO_DATE                       = Record: date on which the QSO started
	QSO_DATE_OFF               Field = "QSO_DATE_OFF"               // QSO_DATE_OFF                   = Record: date on which the QSO ended
	QSO_RANDOM                 Field = "QSO_RANDOM"                 // QSO_RANDOM                     = Record: indicates whether the QSO was random or scheduled
	QTH                        Field = "QTH"                        // QTH                            = Record: the contacted station's city
	QTH_INTL                   Field = "QTH_INTL"                   // QTH_INTL                       = Record: the contacted station's city
	REGION                     Field = "REGION"                     // REGION                         = Record: the contacted station's WAE or CQ entity contained within a DXCC entity. the value None indicates that the WAE or CQ entity is the DXCC entity in the DXCC field. nothing can be inferred from the absence of the REGION field
	RIG                        Field = "RIG"                        // RIG                            = Record: description of the contacted station's equipment
	RIG_INTL                   Field = "RIG_INTL"                   // RIG_INTL                       = Record: description of the contacted station's equipment
	RST_RCVD                   Field = "RST_RCVD"                   // RST_RCVD                       = Record: signal report from the contacted station
	RST_SENT                   Field = "RST_SENT"                   // RST_SENT                       = Record: signal report sent to the contacted station
	RX_PWR                     Field = "RX_PWR"                     // RX_PWR                         = Record: the contacted station's transmitter power in Watts with a value greater than or equal to 0
	SAT_MODE                   Field = "SAT_MODE"                   // SAT_MODE                       = Record: satellite mode - a code representing the satellite's uplink band and downlink band
	SAT_NAME                   Field = "SAT_NAME"                   // SAT_NAME                       = Record: name of satellite
	SFI                        Field = "SFI"                        // SFI                            = Record: the solar flux at the time of the QSO in the range 0 to 300 (inclusive).
	SIG                        Field = "SIG"                        // SIG                            = Record: the name of the contacted station's special activity or interest group
	SIG_INTL                   Field = "SIG_INTL"                   // SIG_INTL                       = Record: the name of the contacted station's special activity or interest group
	SIG_INFO                   Field = "SIG_INFO"                   // SIG_INFO                       = Record: information associated with the contacted station's activity or interest group
	SIG_INFO_INTL              Field = "SIG_INFO_INTL"              // SIG_INFO_INTL                  = Record: information associated with the contacted station's activity or interest group
	SILENT_KEY                 Field = "SILENT_KEY"                 // SILENT_KEY                     = Record: 'Y' indicates that the contacted station's operator is now a Silent Key.
	SKCC                       Field = "SKCC"                       // SKCC                           = Record: the contacted station's Straight Key Century Club (SKCC) member information
	SOTA_REF                   Field = "SOTA_REF"                   // SOTA_REF                       = Record: the contacted station's International SOTA Reference.
	SRX                        Field = "SRX"                        // SRX                            = Record: contest QSO received serial number with a value greater than or equal to 0
	SRX_STRING                 Field = "SRX_STRING"                 // SRX_STRING                     = Record: contest QSO received information use Cabrillo format to convey contest information for which ADIF fields are not specified in the event of a conflict between information in a dedicated contest field and this field, information in the dedicated contest field shall prevail
	STATE                      Field = "STATE"                      // STATE                          = Record: the code for the contacted station's Primary Administrative Subdivision (e.g. US State, JA Island, VE Province)
	STATION_CALLSIGN           Field = "STATION_CALLSIGN"           // STATION_CALLSIGN               = Record: the logging station's callsign (the callsign used over the air) if STATION_CALLSIGN is absent, OPERATOR shall be treated as both the logging station's callsign and the logging operator's callsign
	STX                        Field = "STX"                        // STX                            = Record: contest QSO transmitted serial number with a value greater than or equal to 0
	STX_STRING                 Field = "STX_STRING"                 // STX_STRING                     = Record: contest QSO transmitted information use Cabrillo format to convey contest information for which ADIF fields are not specified in the event of a conflict between information in a dedicated contest field and this field, information in the dedicated contest field shall prevail
	SUBMODE                    Field = "SUBMODE"                    // SUBMODE                        = Record: QSO Submode use enumeration values for interoperability
	SWL                        Field = "SWL"                        // SWL                            = Record: indicates that the QSO information pertains to an SWL report
	TEN_TEN                    Field = "TEN_TEN"                    // TEN_TEN                        = Record: Ten-Ten number with a value greater than 0
	TIME_OFF                   Field = "TIME_OFF"                   // TIME_OFF                       = Record: HHMM or HHMMSS in UTC in the absence of <QSO_DATE_OFF>, the QSO duration is less than 24 hours. For example, the following is a QSO starting at 14 July 2020 23:55 and finishing at 15 July 2020 01:00: <QSO_DATE:8>20200714 <TIME_ON:4>2355 <TIME_OFF:4>0100
	TIME_ON                    Field = "TIME_ON"                    // TIME_ON                        = Record: HHMM or HHMMSS in UTC
	TX_PWR                     Field = "TX_PWR"                     // TX_PWR                         = Record: the logging station's power in Watts with a value greater than or equal to 0
	UKSMG                      Field = "UKSMG"                      // UKSMG                          = Record: the contacted station's UKSMG member number with a value greater than 0
	USACA_COUNTIES             Field = "USACA_COUNTIES"             // USACA_COUNTIES                 = Record: two US counties in the case where the contacted station is located on a border between two counties, representing counties credited to the QSO for the CQ Magazine USA-CA award program. E.g. MA,Franklin:MA,Hampshire
	VUCC_GRIDS                 Field = "VUCC_GRIDS"                 // VUCC_GRIDS                     = Record: two or four adjacent Maidenhead grid locators, each four or six characters long, representing the contacted station's grid squares credited to the QSO for the ARRL VUCC award program. E.g. EN98,FM08,EM97,FM07
	WEB                        Field = "WEB"                        // WEB                            = Record: the contacted station's URL
	WWFF_REF                   Field = "WWFF_REF"                   // WWFF_REF                       = Record: the contacted station's WWFF (World Wildlife Flora & Fauna) reference
)
