name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25'

    - name: Run tests
      run: go test -v ./...

    - name: Install goimports
      run: go install golang.org/x/tools/cmd/goimports@latest

    - name: Add go bin to PATH
      run: echo "$HOME/go/bin" >> $GITHUB_PATH

    - name: Run generate
      run: |
        go generate ./...
        if [ -n "$(git status --porcelain)" ]; then
          echo "Generated files are not up to date. Please run go generate ./... and commit changes."
          exit 1
        fi
